
== 2.0

This section lists the new features, enhancements and fixed issues for
2.0 release.

[[features-20]]
=== New Features and Changes

The following are the new features and changes introduced with 2.0
release.

* New Elastic Memory(Enterprise Edition Only): By default, Hazelcast
stores your distributed data (map entries, queue items) into Java heap
which is subject to garbage collection. As your heap gets bigger,
garbage collection might cause your application to pause tens of
seconds, badly effecting your application performance and response
times. Elastic Memory is Hazelcast with off-heap memory storage to avoid
GC pauses. Even if you have terabytes of cache in-memory with lots of
updates, GC will have almost no effect; resulting in more predictable
latency and throughput.
* Security Framework(Enterprise Edition Only): Hazelcast Security is
JAAS based pluggable security framework which can be used to
authenticate both cluster members and clients and do access control
checks on client operations. With the security framework, take control
of who can be part of the cluster or connect as client and which
operations are allowed or not.
* Native C# Client(Enterprise Edition Only): Just like our Native Java
Client, it supports all map, multimap, queue, topic operations including
listeners and queries.
* Distributed Backups: Data owned by a member will be evenly backed up
by all the other members. In other word, every member takes equal
responsibility to backup every other member. This leads to better memory
usage and less influence in the cluster when you add/remove members. The
new backup system makes it possible to form backup-groups so that you
can have backups and owners fall into different groups.
* Parallel IO: Number of socket selector threads can be configured. You
can have more IO threads, if you have good number of CPU/cores and
high-throughput network.
* Connection Management: Hazelcast 2.0 is more tolerant to connection
failures. On connection failure it tries to repair it before declaring
the member as dead. So now it is ok to have short socket disconnections.
No problem if your virtual server migrates to a new host.
* Listeners such as migration, membership and map indexes can be added
with configuration.
* New Event Objects: Event Listeners for Queue/List/Set/Topic were
delivering the item itself on event methods. That’s why the items had to
be deserialized by Hazelcast Threads before invoking the listeners.
Sometimes this was causing class loader problems too. With 2.0, we have
introduced new event containers for Queue/List/Set and Topic just like
Map has EntryEvent. The new listeners now receive ItemEvent and Message
objects respectively. The actual items are deserialized only if you call
the appropriate get method on the event objects. This is where we brake
the compatibility with the older versions of Hazelcast.
* ClientConfig API: We had too many of factory methods to instantiate a
HazelcastClient. Now all we need
`isHazelcastClient.newHazelcastClient(ClientConfig)`.
* SSL communication support among cluster members.
* Distributed MultiMap value collection can be either List or Set.
* SuperClient is renamed to LiteMember to avoid confusion. Be careful!
It is a member, not a client.
* New `IMap.set(key, value, ttl, TimeUnit)` implementation, which is
optimized `put(key, value)` operation as `Set` does not return the old
value.
* `HazelcastInstance.getLifecycleService().kill()` will forcefully kill
the member. Useful for testing.
* `forceUnlock`, to unlock the locked entry from any member and any thread
regardless of the owner.
* Enum type query support: As an example;
`new SqlPredicate (“level = Level.WARNING”)`

=== Fixes

The following are the fixed issues and enhancements for 2.0 release.

* [459], [471], [567], [574], [582], [629], [632], [646], [666], [686],
[669], [690], [692], [693], [695], [698], [705], [708], [711], [714],
[715], [719], [721], [722], [727], [728], [729], [730], [731], [732],
[733], [735], [738], [739], [740], [741], [742], [747], [751], [752],
[758], [759], [760], [761], [765], [767], [770], [773], [779], [781],
[782], [783], [787], [795], [796]
