
== 2.6.1

The following are the fixed issues and enhancements for 2.6.1 release.

* The method `set(Key, Value, 0, Timeunit)` applies the configured TTL
values where it should cancel eviction. Also, the method
`set(Key, Value)` should apply the inherited TTL if exists. [585]
* Operations like `contains()` should use a specific executor service.
Calling the default executor service may cause a deadlock. [579]
* Empty array for the predicate `in` throws exception. [573]
* The methods `ILock.destroy()` and `ISemaphore.destroy()` throw
exceptions on Hazelcast 2.5. [566]
* `NullPointerException` in `com.hazelcast.nio.ConnectionManager` in
Hazelcast 2.5. [530]
* Hazelcast instance does not start with TCP configuration in Hazelcast
2.5 when the hosts are not reachable. [523]
* Hazelcast source archives in Maven central repository does not contain
the Java source files but the class files. [514]
* There is an unexpected store call behavior in Hazelcast 2.6. Every
time when the method `get()` is used in a transaction and when the
method `commit()` is called, it throws ``Duplicated key order_id''
exception. [506]
* When the method `getInstances()` on HazelcastInstance is called
(acquired via `HazelcastClient.newHazelcastClient(clientConfig)`), the
collection is retrieved. After some time, `NullPointerException` is
thrown when the same method is called. [478]
* There are some formatting problems when using SQL predicates with
date. [473]
* There is a memory leak in the member when clients are connected. An
`OutofMemoryException` is thrown related to a client authentication
failure. [450]
* Hazelcast client’s `putAll()` method throws `NullPointerException`
when called with an empty map. [397]
* The `InputStream` in the `XmlConfigBuilder` can never be closed. If
the constructor which provides an XML file is used, it creates a new
`FileInputStream`. There is no ability to close this input stream after
it is created. [390]
* The heartbeat timer for Hazelcast client does not run again after a
`NullPointerException`. [382]
* The queue `SysmteLogService.joinLogs` holds some data and causes
memory consumption. [325]
* Doing a read of a value not modified in a transaction causes the
listener to fire an update for that entry. [311]
