
== 2.6.1

The following are the fixed issues and enhancements for 2.6.1 release.

* The method `set(Key, Value, 0, Timeunit)` applies the configured TTL
values where it should cancel eviction. Also, the method
`set(Key, Value)` should apply the inherited TTL if exists. https://github.com/hazelcast/hazelcast/issues/585[#585]
* Operations like `contains()` should use a specific executor service.
Calling the default executor service may cause a deadlock. https://github.com/hazelcast/hazelcast/issues/579[#579]
* Empty array for the predicate `in` throws exception. https://github.com/hazelcast/hazelcast/issues/573[#573]
* The methods `ILock.destroy()` and `ISemaphore.destroy()` throw
exceptions on Hazelcast 2.5. https://github.com/hazelcast/hazelcast/issues/566[#566]
* `NullPointerException` in `com.hazelcast.nio.ConnectionManager` in
Hazelcast 2.5. https://github.com/hazelcast/hazelcast/issues/530[#530]
* Hazelcast instance does not start with TCP configuration in Hazelcast
2.5 when the hosts are not reachable. https://github.com/hazelcast/hazelcast/issues/523[#523]
* Hazelcast source archives in Maven central repository does not contain
the Java source files but the class files. https://github.com/hazelcast/hazelcast/issues/514[#514]
* There is an unexpected store call behavior in Hazelcast 2.6. Every
time when the method `get()` is used in a transaction and when the
method `commit()` is called, it throws ``Duplicated key order_id''
exception. https://github.com/hazelcast/hazelcast/issues/506[#506]
* When the method `getInstances()` on HazelcastInstance is called
(acquired via `HazelcastClient.newHazelcastClient(clientConfig)`), the
collection is retrieved. After some time, `NullPointerException` is
thrown when the same method is called. https://github.com/hazelcast/hazelcast/issues/478[#478]
* There are some formatting problems when using SQL predicates with
date. https://github.com/hazelcast/hazelcast/issues/473[#473]
* There is a memory leak in the member when clients are connected. An
`OutofMemoryException` is thrown related to a client authentication
failure. https://github.com/hazelcast/hazelcast/issues/450[#450]
* Hazelcast client’s `putAll()` method throws `NullPointerException`
when called with an empty map. https://github.com/hazelcast/hazelcast/issues/397[#397]
* The `InputStream` in the `XmlConfigBuilder` can never be closed. If
the constructor which provides an XML file is used, it creates a new
`FileInputStream`. There is no ability to close this input stream after
it is created. https://github.com/hazelcast/hazelcast/issues/390[#390]
* The heartbeat timer for Hazelcast client does not run again after a
`NullPointerException`. https://github.com/hazelcast/hazelcast/issues/382[#382]
* The queue `SysmteLogService.joinLogs` holds some data and causes
memory consumption. https://github.com/hazelcast/hazelcast/issues/325[#325]
* Doing a read of a value not modified in a transaction causes the
listener to fire an update for that entry. https://github.com/hazelcast/hazelcast/issues/311[#311]
