
== 3.0.3

This section lists the new features, enhancements and fixed issues for
3.0 and 3.0.x releases.

[[features-303]]
=== New Features

This section provides the new features introduced with Hazelcast 3.0
release.

* Multi-thread execution: Operations are now executed by multiple
threads (by factor of processor cores). With Hazelcast 2, there was a
only single thread.
* SPI: Service Programming Interface for developing new partitioned
services, data structures. All Hazelcast data structures like Map, Queue
are reimplemented with SPI.
* IdentifiedDataSerializable: A slightly optimized version of
DataSerializable that does not use class name and reflection for
de-serialization.
* Portable Serialization: Another Serialization interface that does not
use reflection and can navigate through binary data and
fetch/query/index individual field without having any reflection or
whole object de-serialization.
* Custom Serialization: Support for custom serialization that can be
plugged into Hazelcast.
* Entry Processor: Executing an EntryProcessor on the key or on all
entries. Hazelcast implicitly locks the entree and guarantees no
migration while the execution of the Processor.
* In-Memory Format: Support for storing entries in Binary, Object and
Cached format.
* Continuous Query: Support for listeners that register with a query and
are notified when there is a change on the Map that matches the Query.
* Interceptors: Ability to intercept the Map operation before/after it
is actually executed.
* Lazy Indexing:Ability to index existing items in the map. No need to
add indexes at the very beginning.
* Queue: No more dependency on the distributed map
* Queue: Scales really well as you have thousands of separate queues.
* Queue: Persistence Support for persistence with QueueStore.
* Multimap: Values can be Set/List/Queue.
* Topic: Support for global ordering where all Nodes receive all
messages in the same order.
* Distributed Transaction: Support for both 1-phase (local) and 2 phase
transactions with a totally new API.
* New Binary Protocol: A new binary protocol based on portable
serialization. The same protocol is used for Java/C/C# and other
clients.
* Smart client: Support for dummy and smart client. A dummy client will
maintain a connection to only one member, whereas the smart client can
route the operations to the node that owns the data.

[[fixes-303]]
=== Fixes

This section lists issues solved for 3.0 and 3.0.x releases.

* A class cannot be LifecycleListener and MigrationListener at the same
time. https://github.com/hazelcast/hazelcast/issues/970[#970]
* EntryProcessor does not fire entry events.
https://github.com/hazelcast/hazelcast/issues/950[#950]
* `IMap.localKeySet()` is very slow after upgrade to 3.0.
https://github.com/hazelcast/hazelcast/issues/946[#946]
* Eviction logic error for `USED_HEAP_PERCENTAGE` and `USED_HEAP_SIZE`.
https://github.com/hazelcast/hazelcast/issues/891[#891]
* Failed to execute SqlPredicate with LIKE and OR keywords on the same
field of the class.
https://github.com/hazelcast/hazelcast/issues/885[#885]
* Infinite loop in native client when cluster is gone.
https://github.com/hazelcast/hazelcast/issues/821[#821]
* TransactionalMap: DistributedObjectListener is not working.
https://github.com/hazelcast/hazelcast/issues/812[#812]
* Could not find PortableFactory for factoryId: -3.
https://github.com/hazelcast/hazelcast/issues/800[#800]
* Eviction occurs when it is not expected to occur.
https://github.com/hazelcast/hazelcast/issues/776[#776]
* Possible dead-lock while updating an entry which loaded by map-loader.
https://github.com/hazelcast/hazelcast/issues/768[#768]
* `IMap.destroy()` clears map instead of destroy.
https://github.com/hazelcast/hazelcast/issues/764[#764]
* `IMap.destroy()` throws an exception on client.
https://github.com/hazelcast/hazelcast/issues/726[#726]
* Client replace method issue.
https://github.com/hazelcast/hazelcast/issues/724[#724]
* Classloader issue in deserialization.
https://github.com/hazelcast/hazelcast/issues/723[#723]
* JMX preDeregister of some beans throws HazelcastIsNotActiveException
during `shutdownAll()`.
https://github.com/hazelcast/hazelcast/issues/713[#713]
* Optional sequencing support for Hazelcast write-behind implementation
is needed. https://github.com/hazelcast/hazelcast/issues/712[#712]
* ManagementService.destroy fails to find HazelcastMBean on shutdown.
https://github.com/hazelcast/hazelcast/issues/683[#683]
* Client `getDistributedObject()` does not work.
https://github.com/hazelcast/hazelcast/issues/678[#678]
* Spring ManagedContext does not run on the local node when a task is
executed. https://github.com/hazelcast/hazelcast/issues/659[#659]
* MemberLeftException during SqlPredicate search.
https://github.com/hazelcast/hazelcast/issues/654[#654]
* NearCacheConfig: maxSize = 0 is no longer interpreted as
`Integer.MAX_VALUE`.
https://github.com/hazelcast/hazelcast/issues/650[#650]
* `statistics-enabled` is missing for most items in the XSD scheme.
https://github.com/hazelcast/hazelcast/issues/642[#642]
* Could not find PortableFactory for factoryId: 1095521605 on
SqlPredicate query.
https://github.com/hazelcast/hazelcast/issues/617[#617]
* `Map.containsKey()` should delay eviction.
https://github.com/hazelcast/hazelcast/issues/614[#614]
* Error when serializing portable nested inside other types: Could not
find PortableFactory for factoryId: 0.
https://github.com/hazelcast/hazelcast/issues/600[#600]
* Client related configuration improvements.
https://github.com/hazelcast/hazelcast/issues/599[#599]
* Index on `enum` properties does not work.
https://github.com/hazelcast/hazelcast/issues/597[#597]
* Executing Query operation with a heavy CRUD load throws an
IllegalArgumentException.
https://github.com/hazelcast/hazelcast/issues/596[#596]
* `Map.set()` always calls the `onAdded` entry event.
https://github.com/hazelcast/hazelcast/issues/589[#589]
* Client throws `Could not register listener' often - Near Cache entries
get never invalidated after.
https://github.com/hazelcast/hazelcast/issues/584[#584]
* Unexpected authentication exception.
https://github.com/hazelcast/hazelcast/issues/576[#576]
* Map `clear` does not call MapStore.
https://github.com/hazelcast/hazelcast/issues/572[#572]
* Transactional collections should check the transaction state to
validate proper access.
https://github.com/hazelcast/hazelcast/issues/568[#568]
* Client threads are not destroyed on authentication failures.
https://github.com/hazelcast/hazelcast/issues/555[#555]
* Map index from configuration is not working.
https://github.com/hazelcast/hazelcast/issues/553[#553]
* Client disconnects and never tries to reconnect.
https://github.com/hazelcast/hazelcast/issues/538[#538]
* Map local entry listener gives no Value on `entryEvicted`.
https://github.com/hazelcast/hazelcast/issues/537[#537]
* The method `map.getAll()` is not working if entry does not exist via
Client. https://github.com/hazelcast/hazelcast/issues/535[#535]
* EC2 Auto discovery bug: Instances do not see each other.
https://github.com/hazelcast/hazelcast/issues/516[#516]
* Custom types (other than primitives, string, date, enum, etc) can not
be queried. https://github.com/hazelcast/hazelcast/issues/503[#503]
* OOME is thrown when queues are not explicitly destroyed.
https://github.com/hazelcast/hazelcast/issues/417[#417]
* The method `loadAll` is called redundantly on a new node joining the
cluster. https://github.com/hazelcast/hazelcast/issues/341[#341]
* Support for Hibernate 4.0 cache is needed.
https://github.com/hazelcast/hazelcast/issues/72[#72]
* Add a functionality that performs entry processings.
https://github.com/hazelcast/hazelcast/issues/71[#71]
* Support for JVM system property reference in Hazelcast XML is needed.
https://github.com/hazelcast/hazelcast/issues/59[#59]
* Support `invalidation-only` 2nd level cache for Hibernate.
https://github.com/hazelcast/hazelcast/issues/57[#57]
* Hazelcast resource adapter does not work on WebSphere 6.1/7.
https://github.com/hazelcast/hazelcast/issues/37[#37]
