
== 3.1.8

This section lists the new features, enhancements and fixed issues for
3.1 and 3.1.x releases.

[[features-318]]
=== New Features

This section provides the new features introduced with Hazelcast 3.1
release.

* Elastic Memory (Enterprise Extensions Only) is now available.
* Hazelcast Security is now available.
* Hazelcast JCA integration is back.
* Controlled Partitioning: Controlled Partitioning is the ability to
control the partition of certain DistributedObjects like the IQueue,
IAtomicLong or ILock. This will make collocating related data easier.
Hazelcast map also supports custom partitioning strategies. A
PartitioningStrategy can be defined in map configuration.
* TransactionalMap now supports `keySet()`, `keySet(predicate)`,
`values()` and `values(predicate)` methods.
* Eviction based on USED_HEAP_PERCENTAGE or USED_HEAP_SIZE now takes
account real heap memory size consumed by map.
* SqlPredicate now supports ’' as escape character.
* SqlPredicate now supports regular expressions using REGEX keyword. For
example, `map.values(new SqlPredicate("name REGEX .*earl$"))`.
* Hazelcast queue now supports QueueStoreFactory that will be used to
create custom QueueStores for persistent queues. QueueStoreFactory is
similar to map’s MapStoreFactory.
* TransactionalQueue now supports `peek()` and `peek(timeout, timeunit)`
methods.
* Client now has SSL support.
* Client also supports custom socket implementations using SocketFactory
API. A custom socket factory can be defined in ClientConfig.
* Hazelcast IList and ISet now have their own configurations. They can
be configured using config API, XML and Spring.
* `HazelcastInstance.shutdown()` method added back.
* OSGI compatibility is improved significantly.

[[fixes-318]]
=== Fixes

This section lists issues solved for 3.1 and 3.1.x releases.

* `ClassCastException` when using near cache.
https://github.com/hazelcast/hazelcast/issues/1941[[#1941]]
* Hazelcast management console does not allow update of map
configuration in runtime.
https://github.com/hazelcast/hazelcast/issues/1898[[#1898]]
* MultiMap ConcurrentModificationExceptions.
https://github.com/hazelcast/hazelcast/issues/1882[[#1882]]
* Near Cache: Race Condition.
https://github.com/hazelcast/hazelcast/issues/1861[[#1861]]
* ClientReAuthOperation cannot return response without call ID.
https://github.com/hazelcast/hazelcast/issues/1816[[#1816]]
* REST put overrides TTL from the configuration.
https://github.com/hazelcast/hazelcast/issues/1783[[#1783]]
* Management Center usage should not trigger loading of map.
https://github.com/hazelcast/hazelcast/issues/1770[[#1770]]
* ResourceAdaptor fix to handle external HazelcastInstance breaking
scheme. https://github.com/hazelcast/hazelcast/issues/1727[[#1727]]
* There is no `executeOnAllKey` for IMap, the documentation should be
changed. https://github.com/hazelcast/hazelcast/issues/1711[[#1711]]
* Memory leak; `backupCalls` record is not removed if `Future.get()` is
not called during `IMap.putAsync()` or `IMap.removeAsync()`.
https://github.com/hazelcast/hazelcast/issues/1693[[#1693]]
* `ClassCastException` when removing from Multimap.
https://github.com/hazelcast/hazelcast/issues/1667[[#1667]]
* com.hazelcast.spi.exception.RetryableHazelcastException: Map is not
ready. https://github.com/hazelcast/hazelcast/issues/1593[[#1593]]
* Member join while loading persistent maps throws NPEs.
https://github.com/hazelcast/hazelcast/issues/1577[[#1577]]
* Near cache does not work properly for null values.
https://github.com/hazelcast/hazelcast/issues/1570[[#1570]]
* Memory Leak on operation timeout.
https://github.com/hazelcast/hazelcast/issues/1559[[#1559]]
* EOFException: Remote socket is closed.
https://github.com/hazelcast/hazelcast/issues/1551[[#1551]]
* Severe NullPointerException but then everything works fine.
https://github.com/hazelcast/hazelcast/issues/1548[[#1548]]
* `IMap.putTransient(K,V)` method (without TTL) is missing.
https://github.com/hazelcast/hazelcast/issues/1526[[#1526]]
* Object is not an instance of declaring the class
com.hazelcast.query.impl.QueryException.
https://github.com/hazelcast/hazelcast/issues/1503[[#1503]]
* Setting socket timeout, Hazelcast client will throw
SocketTimeoutException.
https://github.com/hazelcast/hazelcast/issues/1435[[#1435]]
* `QueueStore.store(Long, Object)` is called multiple times from
`TransactionalQueue.offer`.
https://github.com/hazelcast/hazelcast/issues/1412[[#1412]]
* Warning: No transaction item for itemId: .
https://github.com/hazelcast/hazelcast/issues/1393[[#1393]]
* StackOverflow in `AndResultSet`.
https://github.com/hazelcast/hazelcast/issues/1349[[#1349]]
* `maxIdleSeconds` is set to DEFAULT_TTL_SECONDS in
`com.hazelcast.config.MapConfig`.
https://github.com/hazelcast/hazelcast/issues/1308[[#1308]]
* Serializer implementation registration with Spring config fails.
https://github.com/hazelcast/hazelcast/issues/1294[[#1294]]
* `ReadBackupData` on Map exposes internally stored value.
https://github.com/hazelcast/hazelcast/issues/1292[[#1292]]
* Multimap: Lock is not owned by the transaction.
https://github.com/hazelcast/hazelcast/issues/1276[[#1276]]
* Java deserialization of non-static inner classes fails.
https://github.com/hazelcast/hazelcast/issues/1265[[#1265]]
* HazelcastInstance is not injected into MapInterceptor when
HazelcastInstanceAware is implemented.
https://github.com/hazelcast/hazelcast/issues/1233[[#1233]]
* Remove `compare` optimization from map put.
https://github.com/hazelcast/hazelcast/issues/1231[[#1231]]
* Unneeded deserialization in EntryOperation.
https://github.com/hazelcast/hazelcast/issues/1182[[#1182]]
* Adding an InitialMembershipListener to ClientConfig using
`ClientConfig.addListenerConfig` throws NullPointerException.
https://github.com/hazelcast/hazelcast/issues/1181[[#1181]]
* Insufficient calculation of next key/value when doing a restore of
message queue from database.
https://github.com/hazelcast/hazelcast/issues/1165[[#1165]]
* Case insensitivity of configurations in XML.
https://github.com/hazelcast/hazelcast/issues/1152[[#1152]]
* The scheme `hazelcast-spring3.1.xsd` throws SAXParseException when
`hz:interfaces` have multiple `hz:interface` elements.
https://github.com/hazelcast/hazelcast/issues/1145[[#1145]]
* Bundle start fails due to `OSGiScriptEngineManager`.
https://github.com/hazelcast/hazelcast/issues/1136[[#1136]]
* Apparent memory leak when using near cache.
https://github.com/hazelcast/hazelcast/issues/1087[[#1087]]
* Semaphore can be initialized multiple times if permit-count = 0.
https://github.com/hazelcast/hazelcast/issues/1080[[#1080]]
* Exception when running continuous query. And non-existent key is
deleted under transaction.
https://github.com/hazelcast/hazelcast/issues/1076[[#1076]]
* Race condition between first map operation and re-populating a map
after a cluster restart.
https://github.com/hazelcast/hazelcast/issues/1070[[#1070]]
* Eviction tasks should be cancelled on `remove()`, `evict()`.
https://github.com/hazelcast/hazelcast/issues/1068[[#1068]]
* Stale cache issues when using `HazelcastLocalCacheRegionFactory`.
https://github.com/hazelcast/hazelcast/issues/1039[[#1039]]
* When multiple nodes start simultaneously, post join process duplicates
some event registrations and causes warning logs on each publish.
https://github.com/hazelcast/hazelcast/issues/1024[[#1024]]
* Multimap entry listener is called twice.
https://github.com/hazelcast/hazelcast/issues/993[[#993]]
* Clear logic on `ByteArrayObjectDataOutput` can create memory leak with
large objects. https://github.com/hazelcast/hazelcast/issues/989[[#989]]
* TransactionException: Lock is not owned by the transaction.
https://github.com/hazelcast/hazelcast/issues/988[[#988]]
* Spring schema declaration is missing.
https://github.com/hazelcast/hazelcast/issues/982[[#982]]
* Null object indexing exception.
https://github.com/hazelcast/hazelcast/issues/978[[#978]]
* Entries not changed by an EntryProcessor should not render an
EntryListener event.
https://github.com/hazelcast/hazelcast/issues/969[[#969]]
* Unlock parameter in TxnSetOperation backup operation is not
serialized. https://github.com/hazelcast/hazelcast/issues/956[[#956]]
* PartitioningStrategy is not set in HazelcastClient.
https://github.com/hazelcast/hazelcast/issues/923[[#923]]
* Enhancement request: Consider extending SqlPredicate to allow using
regexes. https://github.com/hazelcast/hazelcast/issues/914[[#914]]
* Map `getAll()` is blocked with ``Map is not ready exception''.
https://github.com/hazelcast/hazelcast/issues/887[[#887]]
* QueueStoreConfig needs a factory to support wildcard creation.
https://github.com/hazelcast/hazelcast/issues/884[[#884]]
* Data is lost when transaction manager node terminates/crashes without
preparing transaction.
https://github.com/hazelcast/hazelcast/issues/863[[#863]]
* Make `cache-null-value-seconds` customizable.
https://github.com/hazelcast/hazelcast/issues/806[[#806]]
* Reintroduce the `Instanceof` predicate.
https://github.com/hazelcast/hazelcast/issues/790[[#790]]
* Add `IMap.addEntryListener()` without key (continuous query).
https://github.com/hazelcast/hazelcast/issues/710[[#710]]
* The calculation `used_heap_percentage` should take backups into
account. https://github.com/hazelcast/hazelcast/issues/403[[#403]]
