== 3.12.2

[[enh-3122]]
=== Enhancements 

*_Hazelcast IMDG Enterprise Enhancements:_*

* Enabled the REST endpoints for the `cluster.sh`, `cp-subsystem.sh` and
`healthcheck.sh` scripts to use HTTPS. Before, they were
using HTTP. See the
link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#using-the-script-cluster-sh[cluster.sh^],
link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#cp-subsystem-management-apis[cp-subsystem.sh^]
and link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#health-check-script[healthcheck.sh^] sections.

*_Hazelcast IMDG Open Source Enhancements:_*

* Introduced complete example configurations (XML and YAML) for
Hazelcast Java client and client failover.
See the link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#configuring-declaratively[Configuring Declaratively section^].


[[fixes-3122]]
=== Fixes

* Fixed an issue where the `UNKNOWN` current runtime version in
the `JavaVersion.isAtLeast()` method was not handled properly.
To avoid having runtime functionality, that relies on
this method, broken with each new major Java release, `UNKNOWN`
as a detected current runtime version is now considered to be at least any
other version.
https://github.com/hazelcast/hazelcast/pull/15362[#15362]
* Updated the `JavaVersion` class to support JDK 13 and 14 builds.
https://github.com/hazelcast/hazelcast/pull/15354[#15354]
* Fixed the deserialization filtering for Externalizables and Deadlock in the
map index. The deserialization filter was not properly protecting against the
vulnerable Externalizable classes. The filtering has been extended.
https://github.com/hazelcast/hazelcast/issues/15346[#15346]
* Fixed an issue where the comparators were not able to act on both keys and values.
A custom paging predicate comparator may act on keys and values at the
same time even if only the keys are requested, e.g., using the `IMap.keySet()`
method. Before this fix only the keys were fetched for this method, making
comparators unable to act on values.
https://github.com/hazelcast/hazelcast/pull/15324[#15324]
* Fixed an issue where the locked entries with a time-to-live were not evicted.
With this fix, the lock operation checks if an entry has already expired.
https://github.com/hazelcast/hazelcast/pull/15310[#15310]
* Fixed an issue where the named scheduled tasks was not respecting
the `HazelcastInstanceAware` marker.
https://github.com/hazelcast/hazelcast/pull/15233[#15233]
* Fixed an issue where storing `MapStore` instances in `MapStoreConfig`
could cause member failures when the configuration is added
dynamically: When you configure the map store by the class name
and start Hazelcast with this configuration, the `MapStoreConfig#implementation`
field was altered to store the reference to the `MapStore` instance
created by Hazelcast (this meant that someone can access the created map store
instance via `MapStoreConfig#getImplementation()`). With this fix,
`MapStoreConfig` behavior has become aligned with other data structures' configuration,
i.e., it is not altered anymore and if you did not set anything as `implementation`
then `MapStoreConfig#getImplementation()` returns `null` after Hazelcast is started.
Also, this fix eliminates the side effects with the
dynamically added map configurations, potentially breaking this functionality
for the maps with map stores configured.
https://github.com/hazelcast/hazelcast/pull/15225[#15225]
* Fixed an issue where IMap's `localLockedEntryCount` metric was not considering
the entries with null values.
https://github.com/hazelcast/hazelcast/issues/15218[#15218]
* Fixed a possible `NullPointerException` for the `remove` variable in
`DeafultRecordStore`.
https://github.com/hazelcast/hazelcast/issues/15217[#15217]
* Fixed an issue where an executor was serialized multiple times when it
is sent to multiple members by a Java client. Now, it is serialized
only once as expected.
https://github.com/hazelcast/hazelcast/issues/15007[#15007]