

== 3.12

[[bc-312]]
=== Breaking Changes

* Support for JDK 6 and 7 has been dropped. The minimum Java version
that Hazelcast supports now is Java 8. See the 
https://docs.hazelcast.org/docs/3.12/manual/html-single/#supported-jvms[Supports JVMs section].

[[nf-312]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **Blue-Green and Disaster Recovery for Java Clients:** Introduced
the support for Hazelcast Java clients to switch between alternative
clusters. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#blue-green-deployment-and-disaster-recovery[Blue Green Deployment and Disaster Recovery section].

*_Hazelcast IMDG Open Source New Features:_*

* **CP Subsystem:** Implementing the https://raft.github.io/[Raft consensus algorithm],
Hazelcast introduces its CP subsystem which runs within a Hazelcast cluster and
offers linearizable implementations of Hazelcast's concurrency APIs. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#cp-subsystem[CP Subsystem chapter].
* **Querying JSON Strings:**  You can now query JSON strings stored inside your
Hazelcast clusters. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/#querying-json-strings[Querying JSON Strings section].
* **Pipelining:** Introduced pipelining mechanism using which you can send
multiple requests in parallel to Hazelcast members or clients, and read
the responses in a single step. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#pipelining[Pipelining section].
* **Support for Multiple Endpoints When Configuring Member’s Networking:** Added the
ability to configure the Hazelcast members with separate server sockets for
different protocols. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/#advanced-network-configuration[Advanced Network Configuration section].
* **YAML Configuration Support:** Added the support for configuring Hazelcast
in YAML. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/#configuring-declaratively-yaml[Configuring Declaratively with YAML section].

[[enh-312]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **Sharing Hot Restart `base-dir` among Multiple Members:** The base directory
for the Hot Restart feature (`base-dir`) is now used as a shared directory between
multiple members, and each member uses a unique sub-directory
inside this base directory. This allows using the same configuration
on all the members. Previously, each member had to use a separate directory
which complicated the deployments on cloud-like environments. During the restart,
a member tries to lock an already existing Hot Restart directory inside the base
directory. If it cannot acquire any, then it creates a fresh new directory.
See the https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html##configuring-hot-restart[Configuring Hot Restart section].
* **Lower Latencies and Higher Throughput in WAN Replication:** Improved
the design of the WAN replication mechanism to allow configuring it for
lower latencies and higher throughput. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html##tune-wr[Tuning WAN Replication For Lower Latencies and Higher Throughput section].
* **Add/Remove WAN Publishers in a Running Cluster:** Introduced the
ability to dynamically add or remove WAN publishers (target clusters).
See the https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#dynamically-adding-wan-publishers[Dynamically Adding WAN Publishers section].
* **Automatic Removal of Stale Hot Restart Data:** Introduced an option that
allows the stale Hot Restart data to be removed automatically. See the description of the
`auto-remove-stale-data` configuration element in the
https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#configuring-hot-restart[Configuring Hot Restart section].
* **Client Permission Handling When a New Member Joins:** Introduced a
declarative configuration attribute `on-join-operation` for the client
permission in the Security configuration (its programmatic configuration
equivalent is the `setOnJoinPermissionOperation()` method). This attribute
allows to choose whether a new member joining to a cluster will apply the
client permissions stored in its own configuration, or will use the ones
defined in the cluster. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/#handling-permissions-when-a-new-member-joins[Handling Permissions When a New Member Joins section].
* **Automatic Cluster Version Change after a Rolling Upgrade:** Introduced
the ability to automatically upgrade the cluster version after a rolling
upgrade. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/#upgrading-cluster-version[Upgrading Cluster Version section].
* **FIPS 140-2 Validation:** Hazelcast now can be configured to use a
FIPS 140-2 validated module. See the https://docs.hazelcast.org/docs/3.12/manual/html-single/#fips-140-2[FIPS 140-2 section].

*_Hazelcast IMDG Open Source Enhancements:_*

* **Client Instance Names and Labels:** You can now retrieve the names
of client instances on the member side. Moreover, client labels have
been introduced so that you can group your clients and/or perform special
operations for specific clients. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#defining-client-labels[Defining Client Labels section].
* **Composite Indexes:** Introduced the ability to recognize the queries
that use all the indexed properties and treat them as a composite, e.g.,
`foo = 1 and bar = 2 and foobar = 3`. See the
https://docs.hazelcast.org/docs/3.12/manual/html-single/index.html#composite-indexes[Composite Indexes section].
* **REST Endpoint Groups:** With this enhancement you can enable or disable:
** REST API completely
** Memcache protocol
** REST endpoint groups 
+
See the https://docs.hazelcast.org/docs/3.12/manual/html-single/#using-the-rest-endpoint-groups[Using the REST Endpoint Groups section].

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Improved the YAML configuration so that you can configure multiple WAN
member sockets. https://github.com/hazelcast/hazelcast/issues/14800[#14800] 
* Members now fail fast when the `max-idle-seconds` element for the entries
in a map is set to 1 second. See the note in the
https://docs.hazelcast.org/docs/latest-dev/manual/html-single/#configuring-map-eviction[Configuring Map Eviction section]
for this element. https://github.com/hazelcast/hazelcast/issues/14697[#14697]
* Removed group password from the Hazelcast’s default XML configuration file.
Also improved the non-empty password `INFO` message. It's now only logged if
security is disabled, password is not empty and password is not the Hazelcast
default one. https://github.com/hazelcast/hazelcast/pull/14603[#14603]
* Improved the code comments for the `HazelcastInstance` interface.
https://github.com/hazelcast/hazelcast/issues/14439[#14439]
* Improved the Javadoc of `HazelcastClient` so that the code comments now use
"unisocket client" instead of "dumb client".
https://github.com/hazelcast/hazelcast/issues/14213[#14213]
* Added the ability to perform an LDAP `subtree` search for groups in
Hazelcast Management Center’s LDAP authenticator.
https://github.com/hazelcast/hazelcast/issues/14118[#14118]
* Added the ability to set the `EvictionConfig.comparatorClassName()` in
the client’s declarative configuration, too.
https://github.com/hazelcast/hazelcast/issues/14093[#14093]
* Introduced the `/ready` endpoint to the REST API to allow checking a member
if it is ready to be used after it joins to the cluster.
https://github.com/hazelcast/hazelcast/issues/14089[#14089]
* Improved the syncing of XSD files. https://github.com/hazelcast/hazelcast/issues/14070[#14070]
* The `IMap.removeAll()` method now supports `PartitionPredicate`.
https://github.com/hazelcast/hazelcast/issues/12238[#12238]
* Improved the diagnostics tool so that it automatically creates the
configured directory for the diagnostic outputs.
https://github.com/hazelcast/hazelcast/issues/11946[#11946]

[[fixes-312]]
=== Fixes

* Fixed an issue where the state of member list on the clients were broken after a hot
restart in the cluster.https://github.com/hazelcast/hazelcast/issues/14839[#14839]
* Fixed an issue where the outbound pipeline was not waking up properly after 
merging the write-through changes. https://github.com/hazelcast/hazelcast/issues/14830[#14830]
* Fixed an issue where a Hazelcast Java client was not able to connect to the cluster
(which has the `advanced-network` configuration) after a split-brain syndrome
is healed. https://github.com/hazelcast/hazelcast/issues/14768[#14768]
* Fixed an issue where the `like` and `ilike` predicates didn’t catch any
entity with the `text` field containing the `\n` character.
https://github.com/hazelcast/hazelcast/issues/14751[#14751]
* Fixed an issue where ``NullPointerException``s was thrown recursively
when a client is connected to an unreachable member during a split-brain.
https://github.com/hazelcast/hazelcast/issues/14722[#14722]
* Fixed an issue where Hazelcast running on RHEL (OpenJDK8) shows `unknown gc`
in the logs, instead of `major gc` and `minor gc`.
https://github.com/hazelcast/hazelcast/issues/14701[#14701]
* Fixed an issue where the IP client selector was not working for the local clients.
https://github.com/hazelcast/hazelcast/issues/14654[#14654]
* Fixed the wording of a misleading error in the first attempt to connect to a wrongly
configured cluster. The error message has been changed to “Unable to connect to any cluster”.
https://github.com/hazelcast/hazelcast/issues/14574[#14574]
* Fixed an issue where a connection configured using `AdvancedNetworkConfig`
was not denied correctly for some inappropriate endpoints.
https://github.com/hazelcast/hazelcast/issues/14532[#14532]
* Fixed the REST service which was not working when the REST endpoint is configured
for `AdvancedNetworkConfig`. https://github.com/hazelcast/hazelcast/issues/14516[#14516]
* Fixed an issue where the `setAsync()` method was throwing `NullPointerException`.
https://github.com/hazelcast/hazelcast/issues/14445[#14445]
* Fixed an issue where the collection attributes indexed with `[any]` were causing
incorrect SQL query results, if the first data inserted to the map has no value for
the attribute or the collection is empty. https://github.com/hazelcast/hazelcast/issues/14358[#14358]
* Fixed an issue where `mapEvictionPolicy` couldn’t be specified in the JSON
configuration file. https://github.com/hazelcast/hazelcast/issues/14092[#14092]
* Fixed an issue where the rolling upgrade was failing when all members change their
IP addresses. https://github.com/hazelcast/hazelcast/issues/14088[#14088]
* Fixed an issue where the resources were not wholly cleared when destroying
`DurableExecutorService` causing some resources to be left in the heap.
https://github.com/hazelcast/hazelcast/issues/14087[#14087]
* Fixed an issue where the REST API was not handling the HTTP requests without
headers correctly: when a client sends an HTTP request without headers to the
Hazelcast REST API, the `HttpCommand` class was wrongly expecting an additional
new line. https://github.com/hazelcast/hazelcast/issues/14353[#14353]
* Fixed an issue where `QueryCache` was not returning the copies of the found
objects. https://github.com/hazelcast/hazelcast/issues/14280[#14280]
* Fixed an issue where the locks were not cleaned up after the members are
restarted. https://github.com/hazelcast/hazelcast/issues/14215[#14215]
* Fixed an issue where the MultiMap's `RemoveOperation` was iterating through
the backing collection, which caused performance degradation (when using the
`SET` collection type). https://github.com/hazelcast/hazelcast/issues/14145[#14145]
* Fixed an issue where the user code deployment feature was throwing `NullPointerException`
while loading multiple nested classes and using entry processors.
https://github.com/hazelcast/hazelcast/issues/14105[#14105]
* Fixed an issue where the newly joining members could not form a cluster
when the existing members are killed. https://github.com/hazelcast/hazelcast/issues/14051[#14051]
* Fixed an issue where the `IMap.get()` method was not resetting the idle
time counter when `read-backup-data` is enabled. https://github.com/hazelcast/hazelcast/issues/14026[#14026]
* Fixed an issue where the `addIndex()` method was performing a full copy of
entries when a new member joins the cluster, which is not needed.
https://github.com/hazelcast/hazelcast/issues/13964[#13964]
* Fixed an issue where the initialization failure of `discoveryService`
was causing some threads to remain open and the JVM could not be terminated
because of these threads. https://github.com/hazelcast/hazelcast/issues/13821[#13821]
* Fixed the discrepancy between the XSD on the website and the one in the download package.
https://github.com/hazelcast/hazelcast/issues/13011[#13011]
* `PagingPredicate` with comparator was failing to serialize when sending
from the client or member when the cluster size is more than 1. This has been
fixed by making the `PagingPredicateQuery` comparator serializable.
https://github.com/hazelcast/hazelcast/issues/12208[#12208]
* Fixed an issue where `TcpIpConnectionManager` was putting the connections in a map
under the remote endpoint bind address but not under the address to which Hazelcast
connects. https://github.com/hazelcast/hazelcast/issues/11256[#11256]

[[rdf-312]]
=== Removed/Deprecated Features

* `ILock` interface and implementation of `ILock` has been deprecated,
and `FencedLock` has been introduced.
* The original implementations of `IAtomicLong`, `IAtomicReference`,
`ISemaphore` and `ICountDownLatch` have been deprecated. Instead, the
implementations provided by the CP Subsystem have been introduced.
* The following system properties are deprecated:
** `hazelcast.rest.enabled`
** `hazelcast.mc.url.change.enabled`
** `hazelcast.memcache.enabled`
** `hazelcast.http.healthcheck.enabled`
