== 3.12.8

[[enh-3128]]
=== Enhancements

* Introduced WAN throttling mechanism: this allows
the WAN publishers to overload the WAN consumers if transferring the WAN
events takes less time than processing them in the target cluster. This
can be the case with WAN synchronization if the network latency is low
enough. It can be configured using the following properties:
** `hazelcast.wan.consumer.invocation.threshold`
** `hazelcast.wan.consumer.ack.delay.backoff.init`
** `hazelcast.wan.consumer.ack.delay.backoff.max`
** `hazelcast.wan.consumer.ack.delay.backoff.multiplier`
+
See link:https://github.com/hazelcast/hazelcast/blob/3.12.8/hazelcast/src/main/java/com/hazelcast/spi/properties/GroupProperty.java#L1056[here] for their explanations.

[[fixes-3128]]
=== Fixes

* Fixed an issue where the CP client message tasks were deserializing
the responses.
https://github.com/hazelcast/hazelcast/issues/17050[#17050]
* Fixed an issue where the split-brain protection events were triggered during the
startup of members, but before they join the cluster. With this fix,
these events will not be fired until the minimum cluster size (quorum) is met after the
member startups.
https://github.com/hazelcast/hazelcast/issues/17038[#17038]
* Fixed an issue where notifying the partition table updates to
the clients by a member was causing latencies.
https://github.com/hazelcast/hazelcast/pull/16937[#16937]
* Fixed an issue in the cache service where its pre-join
operation was considering `CacheConfig` as resolved: it
was assuming that key/value types, user customizations and
other cache configurations have been loaded. This was an issue
when the cache is not touched yet.
https://github.com/hazelcast/hazelcast/pull/16919[#16919]