== 3.12.6

[[features-3126]]
=== New Features

* Introduced Bitmap Indexes to significantly lower
index memory usage for low-cardinality columns and also to speed up
the queries and lower memory requirements for them
when the queries have multiple predicates acting on the same bitmap index.
See the link:https://docs.hazelcast.org/docs/3.12.6/manual/html-single/#bitmap-indexes[Bitmap Indexes section].


[[fixes-3126]]
=== Fixes

* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/16190[#16190]
* Fixed an issue where repetitive calls of `IMap.loadAll()`
may cause memory leaks.
https://github.com/hazelcast/hazelcast/pull/16172[#16172]
* Fixed the joining mechanism so that when the discovery
strategy is enabled, multiple join configurations are prevented.
https://github.com/hazelcast/hazelcast/pull/16143[#16143]
* Fixed an issue where a client in the `CLIENT_DISCONNECTED`
status was never receiving the changes in the cluster member attributes.
https://github.com/hazelcast/hazelcast/issues/15623[#15623]
* Fixed an issue where the `MembershipListener.memberAdded()`
method after a split-brain merge was showing a different
member order.
https://github.com/hazelcast/hazelcast/issues/15353[#15353]