== 3.12.6

[[features-3126]]
=== New Features

* Introduced Bitmap Indexes to significantly lower
index memory usage for low-cardinality columns and also to speed up
the queries and lower memory requirements for them
when the queries have multiple predicates acting on the same bitmap index.
Note that bitmap indexes usage, currently, is a good fit for
array/collection attribute indexing, rather than regular
single-valued attributes.
See the link:https://docs.hazelcast.org/docs/3.12.6/manual/html-single/#bitmap-indexes[Bitmap Indexes section].

[[enh-3126]]
=== Enhancements

* Added support for link:https://aws.amazon.com/privatelink/[AWS PrivateLink^]:
Now, Hazelcast IMDG Java client can work with Hazelcast Cloud when it uses AWS PrivateLink.


[[fixes-3126]]
=== Fixes

* Fixed the map configuration so that now the value of
`optimize-queries` element is not serialized anymore.
https://github.com/hazelcast/hazelcast/pull/16524[#16524]
* Fixed an issue where disabling the quorum had not an effect
and was still checking the presence of split-brain protection.
https://github.com/hazelcast/hazelcast/issues/16507[#16507]
* Fixed an issue where the `Imap.containsKey()` method was not
able to find Near Cached entries when it is called from a
client.
https://github.com/hazelcast/hazelcast/issues/16472[#16472]
* Fixed a race condition caused by using on-heap indexes
while indexing is in progress.
https://github.com/hazelcast/hazelcast/pull/16461[#16461]
* Fixed the issue with `setInstanceName()` when using Spring Boot
and Hazelcast client: the `getOrCreate()` method
has been added to the client configuration.
https://github.com/hazelcast/hazelcast/pull/16363[#16363]
* Fixed an issue where wildcard usage at
`CLASSPATH` was breaking the `stop.bat` and
`start.bat` scripts.
https://github.com/hazelcast/hazelcast/issues/16355[#16355]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/16190[#16190]
* Fixed an issue where repetitive calls of `IMap.loadAll()`
may cause memory leaks.
https://github.com/hazelcast/hazelcast/pull/16172[#16172]
* Fixed the joining mechanism so that when the discovery
strategy is enabled, multiple join configurations are prevented.
https://github.com/hazelcast/hazelcast/pull/16143[#16143]
* Fixed an issue where a client in the `CLIENT_DISCONNECTED`
status was never receiving the changes in the cluster member attributes.
https://github.com/hazelcast/hazelcast/issues/15623[#15623]
* Fixed an issue where the `MembershipListener.memberAdded()`
method after a split-brain merge was showing a different
member order.
https://github.com/hazelcast/hazelcast/issues/15353[#15353]