== 3.12.3

[[enh-3123]]
=== Enhancements 

* Added a new implementation of `SecondsBasedEntryTaskScheduler` for the
`FOR_EACH` mode to improve the performance of `TransactionContext.commit()`.
https://github.com/hazelcast/hazelcast/pull/15586[#15586]
* Improved the client graceful shutdown mechanism so that
its tasks are executed before marking a client as inactive.
https://github.com/hazelcast/hazelcast/pull/15565[#15565]
* Added sent/received bytes logs for each `ProtocolType` into the diagnostics.
https://github.com/hazelcast/hazelcast/pull/15541[#15541]
* Improved the performance of `TransactionLog.add()` by avoiding
the `LinkedList.remove()` call.
https://github.com/hazelcast/hazelcast/pull/15435[#15435]
* To be shown on Management Center, the clients now send both its IP
address and canonical hostname. Before, only the hostname of the
client was shown.
https://github.com/hazelcast/hazelcast/pull/15421[#15421]
* Added the support for nested JSON objects in the arrays.
https://github.com/hazelcast/hazelcast/issues/15368[#15368]

[[fixes-3123]]
=== Fixes

* Fixed an issue where the `node.isMaster()` method could cause
inconsistent behaviors when it is executed during a partition service lock.
https://github.com/hazelcast/hazelcast/pull/15618[#15618]
* Fixed an issue where Management Center was not able to see the 3.12.2 members
(members with CP subsystem enabled) after performing a rolling upgrade from Hazelcast IMDG 3.11.4 to
3.12.2. 'ManagementCenterService' was shutting down and throwing an exception
when a CP-subsystem-enabled member was trying to report to Management Center for the first time. [#15609]
* Made `PagingPredicate` a `VisitablePredicate` so the optimizer is able to
visit its inner predicate to optimize it or to select an index to evaluate the
inner predicate with.
https://github.com/hazelcast/hazelcast/issues/15602[#15602]
* Fixed an issue where CP subsystem restarts were not being canceled
or waited the running/scheduled discovery tasks. Otherwise, two different
discovery tasks could overlap and run concurrently or one of the discovery
tasks could run in a corrupted state.
https://github.com/hazelcast/hazelcast/pull/15568[#15568]
* Fixed an issue where the cleaner task for expired records
was logging the exceptions during migrations: the log level for `PartitionMigratingException`
has been set to `FINEST`.
https://github.com/hazelcast/hazelcast/issues/15543[#15543]
* Fixed an issue where the executor service message task
was blocking the partition thread.
https://github.com/hazelcast/hazelcast/pull/15526[#15526]
* Fixed an issue where `normalFramesRead` and `priorityFramesRead` were
never incremented as seen in the diagnostic logs.
https://github.com/hazelcast/hazelcast/issues/15479[#15479]
* Fixed an issue where the `readBackupData` and `statisticsEnabled`
options were not respected when a new map configuration is dynamically
added from a client to a running Hazelcast cluster.
https://github.com/hazelcast/hazelcast/pull/15392[#15392]
* Fixed an issue where a lock was required when registering metrics
on the happy path.
https://github.com/hazelcast/hazelcast/pull/15378[#15378]
* Fixed an issue where some updates to the entries got lost from
the write behind queue: It was a concurrency issue when there are
updates to `CoalescedWriteBehindQueue` while `StoreWorker` is running.
https://github.com/hazelcast/hazelcast/issues/15060[#15060]

[[contributors-3123]]
=== Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/gdela[Wojciech Gdela]

