== 3.12.1

[[new-features-3121]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* Added support for updating the licenses of all the running
members of a Hazelcast IMDG cluster using the REST API.
See the link:https://docs.hazelcast.org/docs/3.12.1/manual/html-single/#rest-update-license[License Information section^].

[[enh-3121]]
=== Enhancements 

* Introduced complete example configurations (XML and YAML) for
Hazelcast Java client and client failover. See the
link:https://docs.hazelcast.org/docs/3.12.1/manual/html-single/#configuring-declaratively[Configuring Declaratively section^].
* Updated Hazelcast JCache implementation to support
JCache 1.1.1. This version of JCache does not introduce new
functionalities; it resolves the errata and issues in JCache 1.1.0.
See the link:https://docs.hazelcast.org/docs/3.12.1/manual/html-single/#jcache-111[Upgrading to JCache 1.1.1 section^].

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Improved ``Config#getConfigurationUrl()``'s Javadoc to mention
that it returns `null` if the `Config` instance has been built from
a source different than URL or file.
https://github.com/hazelcast/hazelcast/pull/15109[#15109]
* Updated the client failover XSD to include `targetNamespace` that
has been delivered with Hazelcast IMDG 3.12.
https://github.com/hazelcast/hazelcast/pull/15057[#15057]
* Updated the Hazelcast Kubernetes dependency to the latest version.
https://github.com/hazelcast/hazelcast/pull/14899[#14899]
* Added the getter method for the YAML configuration builder properties.
https://github.com/hazelcast/hazelcast/pull/14884[#14884]
* Eliminated the excessive logging when NIO networking is shutdown by
deregistering the IO threads.
https://github.com/hazelcast/hazelcast/pull/14837[#14837] 
* Introduced a warning log for illegal reflective access operation when
using Java 9 and higher, and OpenJ 9.
https://github.com/hazelcast/hazelcast/pull/14835[#14835]
* Updated the Hazelcast web session manager dependency to the latest version.
https://github.com/hazelcast/hazelcast/pull/14822[#14822]

[[fixes-3121]]
=== Fixes

* Fixed an issue which was causing `OutOfMemoryException` in a
split-brain situation, due to the client listeners.
https://github.com/hazelcast/hazelcast/pull/15042[#15042]
* Fixed the authentication mechanism between the clients and members
by adding a check to prevent re-verification while the client is changing
its owner member.
https://github.com/hazelcast/hazelcast/pull/15015[#15015]
* Fixed an issue where the Hazelcast IMDG configuration files, that
have an extension other than `.xml`, `.yaml` or `.yml` or do not have
an extension, were ignored silently. This was happening
when the configuration file is set by using the `hazelcast.config`
system property. https://github.com/hazelcast/hazelcast/pull/14945[#14945]
* Some operations such as heartbeat checks and partition
migrations share common threads with the client login module.
In case of the long running client login module implementations,
some symptoms such as split brain syndrome can be seen. This has
been fixed by introducing a blocking executor which is used only
for the client JAAS authentications.
https://github.com/hazelcast/hazelcast/pull/14957[#14957]
* Fixed an issue where the client was not considering the new
address of a restarted member, which has the same UUID but could
have a different IP address after it is restarted.
https://github.com/hazelcast/hazelcast/pull/14843[#14843]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/14834[#14834]

