== 3.12.5

[[enh-3125]]
=== Enhancements

* Added option to disable retrieving the
`OSMBean.getFreePhysicalMemorySize()` method.
https://github.com/hazelcast/hazelcast/pull/16065[#16065]
* The `recreateCachesOnCluster` invocation is not being checked
for the maximum invocations count anymore during cluster restarts.
https://github.com/hazelcast/hazelcast/pull/16014[#16014]


[[fixes-3125]]
=== Fixes

* Fixed an issue where repetitive calls of `IMap.loadAll()`
may cause memory leaks.
https://github.com/hazelcast/hazelcast/pull/16171[#16171]
* Fixed an issue where an HTTP request via
`hazelcast/rest/cluster` was failing when using the advanced network
configuration and a client endpoint is
not specified. In this case, this request's response
has been improved to report `0` as the client connection count.
https://github.com/hazelcast/hazelcast/pull/16150[#16150]
* Fixed an issue where an enabled `redoOperation()` was not
throwing an exception when an empty list is tried to be retrieved
on the client.
https://github.com/hazelcast/hazelcast/pull/16019[#16019]
* Fixed an issue where gathering MultiMap statistics was breaking
the split-brain healing with `LatestAccessMergePolicy`.
https://github.com/hazelcast/hazelcast/issues/16003[#16003]
* Fixed the `multiplier` element of client's connection
retry configuration to be set as a `double` in the
XML configuration (`hazelcast-client.xml`). 
https://github.com/hazelcast/hazelcast/pull/15990[#15990]
* Fixed the following Hot Restart issues:
** Introduced an additional stage to the Hot Restart
procedure, i.e., `HotRestartIntegrationService.startup()`,
which waits until all members transition from the `PASSIVE` state.
This guarantees all members to have the same state after Hot
Restart operation is finished.
** IMap proxies created during Hot Restart are not initialized
and published to other cluster members. So the operation
has been improved to force initialize any uninitialized proxies
and publish them. This fixed the issue where the
`getDistributedObjects()` method was not reporting the persisted
objects after a Hot Restart.
+
https://github.com/hazelcast/hazelcast/pull/15986[#15986]
* Fixed an issue where, after forming a cluster, certain members
occasionally do not contain `EventService` registrations for
some other members.
https://github.com/hazelcast/hazelcast/issues/15950[#15950]
* Fixed an issue where calling the `IMap.removeAll()` method
without index was updating the last access and expiry time
for all records.
https://github.com/hazelcast/hazelcast/pull/15853[#15853]
* Fixed an issue where the client connection count
was retrieved using an incorrect method.
https://github.com/hazelcast/hazelcast/issues/15681[#15681]
