
== 3.2.3

The following are the fixed issues for 3.2.3 release.

* The method `TransactionalQueue.poll` fails to find an item that is put
into the queue in the same transaction with a non-zero timeout.
https://github.com/hazelcast/hazelcast/issues/2669[[#2669]]
* IExecutorService fails when it is called with MemberSelector instance
that returns 0 Members.
https://github.com/hazelcast/hazelcast/issues/2650[[#2650]]
* If statistics are enabled, map’s `InMemoryFormat.Object` does not
work. https://github.com/hazelcast/hazelcast/issues/2622[[#2622]]
* There is a memory leak in long running Hazelcast instances because of
a bug in `MapEvictionManager.MapEvictTask`.
https://github.com/hazelcast/hazelcast/issues/2596[[#2596]]
* Hazelcast client is missing an extensive XML Config Test and XSD Test.
https://github.com/hazelcast/hazelcast/issues/2587[[#2587]]
* The client may consider the original address list if no cluster member
can be reached.
https://github.com/hazelcast/hazelcast/issues/2585[[#2585]]
* Locks are not cleaned upon the operation `map.destroy`.
https://github.com/hazelcast/hazelcast/issues/2582[[#2582]]
* Classpath: Configuration file discovery is not working.
https://github.com/hazelcast/hazelcast/issues/2565[[#2565]]
* The method `ClientService.getConnectedClients()` does not always
return the correct number of clients.
https://github.com/hazelcast/hazelcast/issues/2541[[#2541]]
* Nodes leaving and joining from/to the cluster can cause multiple
subscription callbacks to be sent.
https://github.com/hazelcast/hazelcast/issues/2539[[#2539]]
* Predicate fails with `NullPointerException` if the value is null.
https://github.com/hazelcast/hazelcast/issues/2522[[#2522]]
* Messages’ order breaks with versions 3.2+.
https://github.com/hazelcast/hazelcast/issues/2513[[#2513]]
* The method `ClientProxy.destroy` should always clean the resources.
https://github.com/hazelcast/hazelcast/issues/2475[[#2475]]
* The method `HazelcastHttpSession.getAttributeNames` returns entries
that were only read but not written.
https://github.com/hazelcast/hazelcast/issues/2434[[#2434]]
