
== 3.2

This section lists the new features, enhancements and fixed issues for
3.2 release.

[[features-32]]
=== New Features

* *NIO Client*: New architecture based on NIO introduced to support more
scalable and concurrent client usage.
* *MapReduce Framework*: MapReduce implemented for your key-value
collections that need to be reduced by grouping the keys. Please see
http://www.infoq.com/news/2014/02/hazelcast-mapreduce-api[the interview]
and
http://docs.hazelcast.org/docs/3.2/manual/html-single/hazelcast-documentation.html#mapreduce[MapReduce]
section.
* *Order/Limit Support*: Now you can order and limit results returned by
queries performed on Hazelcast Distributed Map.
* *C++ Client*: Native C++ client developed for C++ users which can
connect to a Hazelcast cluster and realize almost all operations that a
node can perform. Please see
http://docs.hazelcast.org/docs/3.2/manual/html-single/hazelcast-documentation.html#native-clients[Native
Clients].
* *C# Client*: Also, Native C# client that has a very similar API with
Native Java client developed. Please see
http://docs.hazelcast.org/docs/3.2/manual/html-single/hazelcast-documentation.html#native-clients[Native
Clients].

[[enhancements-32]]
=== Enhancements

* Size of a distributed queue via REST API can be returned.
https://github.com/hazelcast/hazelcast/pull/1809[#1809] +
* InitialLoadMode configuration parameter (having Lazy and Eager as
values) added to MapStoreConfig.
https://github.com/hazelcast/hazelcast/pull/1751[#1751]
* Tagging support for Executor Service introduced such that nodes can be
tagged for IExecutorService.
https://github.com/hazelcast/hazelcast/issues/1457[1457]
* `getForUpdate()` operation for transactional map introduced.
https://github.com/hazelcast/hazelcast/issues/1033[#1033]
* Entry processor can run on a set of keys with the introduction of
`executeOnKeys(keys,entryprocessor)` method for IMap.
https://github.com/hazelcast/hazelcast/pull/1423[1423]
* `getNearCacheStats()` introduced. Statistics for near cache can be
retrieved. https://github.com/hazelcast/hazelcast/issues/30[#30]

[[fixes-32]]
=== Fixes

* `LocalMapStats.getNearCacheStats()` can return null when it is called
before a map get that calls `initNearCache()`.
https://github.com/hazelcast/hazelcast/issues/2009[#2009]
* `testMapWithIndexAfterShutDown` fails in OpenJDK.
https://github.com/hazelcast/hazelcast/issues/2001[#2001]
* Portable Serialization needs objects to be shared between client and
server. https://github.com/hazelcast/hazelcast/issues/1957[#1957]
* Near cache entries should be locally invalidate on
`IMap.executeOnKey()`.
https://github.com/hazelcast/hazelcast/issues/1951[#1951]
* OperationTimeoutException is thrown when executing task that runs
longer than `hazelcast.operation.call.timeout.millis`.
https://github.com/hazelcast/hazelcast/issues/1949[#1949]
* `MapStore#store` was called when executing AbstractEntryProcessor on
backup. https://github.com/hazelcast/hazelcast/issues/1940[#1940]
* After an OperationTimeoutException is thrown from `ILock.tryLock()
(and after the system is back in a normal state), the named lock remains
locked. https://github.com/hazelcast/hazelcast/issues/1937[#1937]
* Hazelcast client needs OutOfMemoryErrorDispatcher.
https://github.com/hazelcast/hazelcast/issues/1933[#1933]
* Near Cache: Caching of local entries may lead to race condition.
https://github.com/hazelcast/hazelcast/issues/1905[#1905]
* After key owner node dies, it takes too much time for threads to
wakeup from `condition.await()`.
https://github.com/hazelcast/hazelcast/issues/1879[#1879]
* Possible improvements/fixes for NearCache.
https://github.com/hazelcast/hazelcast/issues/1863[#1863]
* `MultipleEntryBackupOperation` does not handle deletion of entries.
https://github.com/hazelcast/hazelcast/issues/1854[#1854]
* If topics are created/destroyed, then the statistics for that topic
are not destroyed and this can cause a memory leak.
https://github.com/hazelcast/hazelcast/issues/1847[#1847]
* PartitionService backup/replication fixes.
https://github.com/hazelcast/hazelcast/issues/1840[#1840]
* Cached null values remain in near cache after `evict` is called.
https://github.com/hazelcast/hazelcast/issues/1829[#1829]
* NullPointerException in MultiMap when the service is shutdown before
the migration is processed.
https://github.com/hazelcast/hazelcast/issues/1823[#1823]
* Network interruption causes node to continually warn with
WrongTargetException.
https://github.com/hazelcast/hazelcast/issues/1815[#1815]
* `DefaultRecordStore#removeAll` should be modified so that it keeps
`key objects to delete` as a list, not a set.
https://github.com/hazelcast/hazelcast/issues/1795[#1795]
* Very long `operation.run()` call stack especially when high partition
count is used.
https://github.com/hazelcast/hazelcast/issues/1745[#1745]
* When executing an entry processor with an index aware predicate, the
index is not used, instead the predicate is applied to the entire entry
set. https://github.com/hazelcast/hazelcast/issues/1719[#1719]
* When one node goes down in a cluster with 2 nodes (where near cache is
enabled), `containsKey` call hangs in the second node.
https://github.com/hazelcast/hazelcast/issues/1688[#1688]
* When deleting an entry from an entry processor by setting the value to
null, it is not removed from the backup store.
https://github.com/hazelcast/hazelcast/issues/1687[#1687]
* Client calls executed at server side cause unwanted (de)serialization.
https://github.com/hazelcast/hazelcast/issues/1669[#1669]
* In `TrackableJobFuture.get(long, TimeUnit)`, there is a 100 ms of
sleep-spin while waiting for the result of a MapReduce task to be set.
https://github.com/hazelcast/hazelcast/issues/1648[#1648]
* If `storeAll` takes much time and if instance terminates while map
store is running, data can be lost.
https://github.com/hazelcast/hazelcast/issues/1644[#1644]
* A missing Spring 4 Cache method added to hazelcast-spring package
(namely `public T get(Object key, Class type)`).
https://github.com/hazelcast/hazelcast/issues/1627[#1627]
* When eviction tasks are canceled, `scheduledExecutorService` is not
cleaned. https://github.com/hazelcast/hazelcast/issues/1595[#1595]
* `storeAll()` with new value for the same key should not be executed
until any previous `storeAll()` operations with the same key are not
completed. https://github.com/hazelcast/hazelcast/issues/1592[#1592]
* When using native client to interact with Hazelcast cluster, some JMX
MBean attribute values on cluster nodes are not set/updated.
https://github.com/hazelcast/hazelcast/issues/1576[#1576]
* `IMap.getAll(keys)` method does not read from near cache.
https://github.com/hazelcast/hazelcast/issues/1532[#1532]
* Near Cache _cache-local-entries_ attribute is missing in
`hazelcast-spring-3.2` XSD.
https://github.com/hazelcast/hazelcast/issues/1524[#1524]
* Exception while executing script in OpenJDK 8.
https://github.com/hazelcast/hazelcast/issues/1518[#1518]
* Infinite waiting on merge operations when cluster shuts down.
https://github.com/hazelcast/hazelcast/issues/1504[#1504]
* Client side socket interceptor is not needed to be
MemberSocketInterceptor.
https://github.com/hazelcast/hazelcast/issues/1444[#1444]
* Near cache on the local node should be enabled if its InMemoryFormat
is different from that of the map.
https://github.com/hazelcast/hazelcast/issues/1438[#1438]
* Async EntryProcessor does not deserialize the value before it is
called back. https://github.com/hazelcast/hazelcast/issues/1433[#1433]
* A submitted task cannot be canceled via the native client.
https://github.com/hazelcast/hazelcast/issues/1394[#1394]
* `executeOnKeys(keys,entryprocessor)` introduced on IMap. With this
feature entry processor can be run on a set of keys.
https://github.com/hazelcast/hazelcast/issues/1339[#1339]
* FINEST logging should be guarded where appropriate.
https://github.com/hazelcast/hazelcast/issues/1332[#1332]
* False errors reported in Eclipse due to schema definition.
https://github.com/hazelcast/hazelcast/issues/1330[#1330]
* Index based operations are not synchronized with partition changes.
https://github.com/hazelcast/hazelcast/issues/1297[#1297]
* Management Center: InvocationTargetException in Tomcat console when a
node is started and then stopped.
https://github.com/hazelcast/hazelcast/issues/1267[#1267]
* The system property `hazelcast.map.load.chunk.size` is being ignored
in Hazelcast 3.1.
https://github.com/hazelcast/hazelcast/issues/1110[#1110]
* Master should fire repartitioning after getting confirmation from
nodes. https://github.com/hazelcast/hazelcast/issues/1058[#1058]
* SqlPredicate does not Implement equals/hashCode.
https://github.com/hazelcast/hazelcast/issues/960[#960]
* `DelegatingFuture.isDone` seems to always return false until the
method `DelegatingFuture.get` is called.
https://github.com/hazelcast/hazelcast/issues/850[#850]
* Predicate support for entry processor.
https://github.com/hazelcast/hazelcast/issues/826[#826]

*RC2 Fixes*

The following are the fixed issues for 3.2-RC2 (Release Candidate 2)
release.

* `ClientService.getConnectedClients` returns all end points.
https://github.com/hazelcast/hazelcast/issues/1883[#1883]
* MultiMap is throwing `ConcurrentModificationExceptions`.
https://github.com/hazelcast/hazelcast/issues/1882[#1882]
* `executorPoolSize` field of ClientConfig cannot be configured using
XML. https://github.com/hazelcast/hazelcast/issues/1867[#1867]
* Partition processing cannot be postponed.
https://github.com/hazelcast/hazelcast/pull/1856[#1856]
* Memory leak at client endpoints.
https://github.com/hazelcast/hazelcast/pull/1842[#1842]
* Errors related to management center configuration on startup.
https://github.com/hazelcast/hazelcast/pull/1821[#1821]
* XML parsing error by client.
https://github.com/hazelcast/hazelcast/pull/1818[#1818]
* `ClientReAuthOperation` cannot return response without call ID.
https://github.com/hazelcast/hazelcast/issues/1816[#1816]
* `MemberAttributeOperationType` should be introduced to remove the
dependency to `MapOperationType`.
https://github.com/hazelcast/hazelcast/pull/1811[#1811]
* Entry listener removal from MultiMap.
https://github.com/hazelcast/hazelcast/pull/1810[#1810]

*RC1 Fixes*

The following are the fixed issues for 3.2-RC1 (Release Candidate 1)
release.

* _TransactionalMap_ does not support `put(K,V,long,TimeUnit)`.
https://github.com/hazelcast/hazelcast/issues/1718[#1718]
* Entry is not removed from backup store when it is deleted using entry
processor. https://github.com/hazelcast/hazelcast/issues/1687[#1687]
* Possibility of losing data when MapStore takes a long time.
https://github.com/hazelcast/hazelcast/issues/1644[#1644]
* When eviction tasks are cancelled, `scheduledExecutorService` should
be cleaned. https://github.com/hazelcast/hazelcast/issues/1595[#1595]
* A fix related to _StoreAll_ is needed in a write-behind scenario.
https://github.com/hazelcast/hazelcast/issues/1592[#1592]
* Update problem at map statistics.
https://github.com/hazelcast/hazelcast/issues/1576[#1576]
* Exception while executing script in OpenJDK 8.
https://github.com/hazelcast/hazelcast/issues/1518[#1518]
* StackOverflowError at `AndResultSet`.
https://github.com/hazelcast/hazelcast/issues/1501[#1501]
* Near Cache using `InMemoryFormat.OBJECT` also for local node.
https://github.com/hazelcast/hazelcast/issues/1438[#1438]
* Async entry processor is not deserializing the value before returning.
https://github.com/hazelcast/hazelcast/issues/1433[#1433]
* Distributed Executor; _Future Cancel_ is not working.
https://github.com/hazelcast/hazelcast/issues/1394[#1394]
* `HazelcastInstanceFactory$InstanceFuture.get()` never returns when
`newHazelcastInstance()` method fails/throws exception.
https://github.com/hazelcast/hazelcast/issues/1253[#1253]
* Changes for _Vertx_ on Openshift.
https://github.com/hazelcast/hazelcast/pull/1176[#1176]
* Serialization should be performed after database interaction for
MapStore. https://github.com/hazelcast/hazelcast/issues/1115[#1115]
* System property related to chunk size is passed over in Hazelcast 3.1.
https://github.com/hazelcast/hazelcast/issues/1110[#1110]
* Map backups lack eviction of some specific data.
https://github.com/hazelcast/hazelcast/issues/1085[#1085]
* `DelegatingFuture.isDone` always returns false until get is called.
https://github.com/hazelcast/hazelcast/issues/850[#850]
* Predicate support for entry processor.
https://github.com/hazelcast/hazelcast/issues/826[#826]
* Full replication of Maps should be performed.
https://github.com/hazelcast/hazelcast/issues/360[#360]
