
== 3.2.2

The following are the fixed issues for 3.2.2 release.

* Client security callable fix.
https://github.com/hazelcast/hazelcast/pull/2561[#2561]
* Updating a key in a transaction gives listeners an entryAdded()
callback instead of entryUpdated().
https://github.com/hazelcast/hazelcast/issues/2542[#2542]
* Client ssl engine doesn’t need keyStore and keyStorePassword.
https://github.com/hazelcast/hazelcast/pull/2525[#2525]
* Added support for Mapper, Combiner, Reducer, KeyValueSource to
implement HazelcastInstanceAware.
https://github.com/hazelcast/hazelcast/pull/2502[#2502]
* Fixed alter function.
https://github.com/hazelcast/hazelcast/pull/2496[#2496]
* Return cached value upon IMap.get() if near cache is enabled.
https://github.com/hazelcast/hazelcast/pull/2482[#2482]
* Exception initializing hz:client.
https://github.com/hazelcast/hazelcast/issues/2480[#2480]
* Fixed portable serialization between different services versions.
https://github.com/hazelcast/hazelcast/pull/2478[#2478]
* Resolves a data race in the client proxy that can lead to an NPE.
https://github.com/hazelcast/hazelcast/pull/2474[#2474]
* Fixed partition group hostname matching.
https://github.com/hazelcast/hazelcast/pull/2470[#2470]
* Client shutdown issue: Improve logging.
https://github.com/hazelcast/hazelcast/issues/2442[#2442]
* Unnecessary synchronized lock when invoking
com.hazelcast.instance.LifecycleServiceImpl.isRunning().
https://github.com/hazelcast/hazelcast/issues/2454[#2454]
* If MapStoreFactory throws exception, instance hangs.
https://github.com/hazelcast/hazelcast/issues/2445[#2445]
* Semaphore is given to the thread that is coming late.
https://github.com/hazelcast/hazelcast/issues/2443[#2443]
* Lots of exceptions when shutting down connection.
https://github.com/hazelcast/hazelcast/issues/2441[#2441]
* Migration fails when statistics are disabled.
https://github.com/hazelcast/hazelcast/issues/2436[#2436]
* 3.2.1 regression: nested transactions are not caught and prevented.
https://github.com/hazelcast/hazelcast/issues/2404[#2404]
* Client proxy init synced.
https://github.com/hazelcast/hazelcast/pull/2376[#2376]
* Fixes hostname matching problem when interface has wildcards.
https://github.com/hazelcast/hazelcast/pull/2398[#2398]
* Fix weblogic shutdown backport.
https://github.com/hazelcast/hazelcast/pull/2391[#2391]
* NotWritablePropertyException connectionAttemptLimit with ssl client
config. https://github.com/hazelcast/hazelcast/issues/2335[#2335]
* Map-Reduce Operation fails, when another instance tries to form a
cluster with an instance running a map reduce task.
https://github.com/hazelcast/hazelcast/issues/2354[#2354]
* EntryEvent getMember returning null when a node leaves the cluster.
https://github.com/hazelcast/hazelcast/issues/2358[#2358]
* NullPointerException in Bundle Activator.
https://github.com/hazelcast/hazelcast/issues/2489[#2489]

[[contributors-322]]
===  Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/lukasblu[Lukas Blunschi]
