
== 3.4

This section lists the new features, enhancements and fixed issues for
3.4 release.

[[features-34]]
=== New Features

The following are the new features introduced with 3.4 release.

* *High-Density Memory Store*: Used with the Hazelcast JCache
implementation, High-Density Memory Store is introduced with this
release. High-Density Memory Store is the enterprise grade backend
storage solution. This solution minimizes the garbage collection
pressure and thus enables predictable application scaling and boosts
performance. For more information, please see
http://docs.hazelcast.org/docs/3.4/manual/html-single/index.html#high-density-memory-store[High-Density
Memory Store section].
* *Jetty Based Session Replication*: We have introduced Jetty-based web
session replication with this release. This is a feature of Hazelcast
Enterprise. It enables session replication for Java EE web applications
that are deployed into Jetty servlet containers, without having to
perform any changes in those applications. For more information, please
see
http://docs.hazelcast.org/docs/3.4/manual/html-single/index.html#jetty-based-web-session-replication[Jetty
Based Web Session Replication section].
* *Hazelcast Configuration Import*: This feature, which is an element
named `<import>`, enables you to compose the Hazelcast declarative (XML)
configuration file out of smaller configuration snippets. For more
information, please see
http://docs.hazelcast.org/docs/3.4/manual/html-single/index.html#composing-xml-configuration[Composing
XML Configuration section].
* *Back Pressure*: Starting with this release, Hazelcast provides the
back pressure feature which prevents the overload caused by pending
asynchronous backups. For more information, please see
http://docs.hazelcast.org/docs/3.4/manual/html-single/index.html#back-pressure[Back
Pressure section].

[[enhancements-34]]
=== Enhancements

The following are the enhancements performed for 3.4 release.

* Event packets sent to the client do not have `partitionId`.
https://github.com/hazelcast/hazelcast/issues/4071[#4071]
* Spring Configuration for ReplicatedMap is Missing.
https://github.com/hazelcast/hazelcast/issues/3966[#3966]
* `NodeMulticastListener` floods log file with INFO-level messages when
debug is enabled.
https://github.com/hazelcast/hazelcast/issues/3787[#3787]
* A Hazelcast client should not be a `HazelcastInstance`. It should be a
`factory` and this factory should be able to shut down Hazelcast
clients. https://github.com/hazelcast/hazelcast/issues/3781[#3781]
* `InvalidateSessionAttributesEntryProcessor` could avoid creating
strings at every call to process.
https://github.com/hazelcast/hazelcast/issues/3767[#3767]
* The timeout for `SocketConnector` cannot be configured.
https://github.com/hazelcast/hazelcast/issues/3613[#3613].
* The method `MultiMap.get()` returns `collection`, but this method
should return the correct collection type (`Set` or `List`).
https://github.com/hazelcast/hazelcast/issues/3214[#3214]
* `HazelcastConnection` is not aligned with `HazelcastInstance`.
https://github.com/hazelcast/hazelcast/issues/2997[#2997]
* Support for Log4j 2.x has been implemented.
https://github.com/hazelcast/hazelcast/issues/2345[#2345]
* Management Center console behavior on node shutdown.
https://github.com/hazelcast/hazelcast/issues/2215[#2215]
* When `queue-store` is not enabled, `QueueStoreFactory` should not be
instantiated.
https://github.com/hazelcast/hazelcast/issues/1906[#1906]
* Management Center should be able to say when cluster is safe and all
backups are up to date.
https://github.com/hazelcast/hazelcast/issues/963[#963]

[[fixes-34]]
=== Fixes

The following are the fixed issues for 3.4 release.

* Deadlock happens in MapReduce implementation when there is a high load
on the system. The issue has been solved by offloading Distributed
MapReduce result collection to the async executor.
https://github.com/hazelcast/hazelcast/issues/4238[#4238]
* When the class `ClientExecutorServiceSubmitTest.java` is compiled
using the Eclipse compiler, it gives a compile error: `__The method
submit(Runnable, ExecutionCallback) is ambiguous for the type
IExecutorService__`. The reason is that the `IExecutorService.java`
class does not have some generics. The issue has been solved by adding
these missing generics to the `IExecutorService.java` class.
https://github.com/hazelcast/hazelcast/issues/4234[#4234]
* JCache declarative listener registration does not work.
https://github.com/hazelcast/hazelcast/issues/4215[#4215]
* JCache evicts the records which are not expired yet. To solve this
issue, the `clear` method should be removed that runs when the size is
smaller than the minimum eviction element count
(`MIN_EVICTION_ELEMENT_COUNT`).
https://github.com/hazelcast/hazelcast/issues/4124[#4124]
* Hazelcast Enterprise Native Memory operations should be updated in
relation with the Hazelcast sync listener changes.
https://github.com/hazelcast/hazelcast/issues/4089[#4089]
* The completion listener (JCache) relies on event ordering but if the
completion listener is registered in another node then event ordering is
not guaranteed.
https://github.com/hazelcast/hazelcast/issues/4073[#4073]
* AWS joiner classname should be fixed since EC2 discovery is not
working after the restructure.
https://github.com/hazelcast/hazelcast/issues/4025[#4025]
* If an IMap has a near cache configured, accessing the near cache via
the method `get(key)` does not count as an access to the underlying
IMap. The near cache has its own `max-idle-seconds` element. However, if
an entry is expired/evicted in the IMap, it also causes a near cache
removal operation for the entry regardless of the `max-idle-seconds` of
that entry in the near cache. The entry expires and is evicted even if
the near cache is being hit constantly. When a near cache is hit, the
underlying map should reset the idle time for that key.
https://github.com/hazelcast/hazelcast/issues/4016[#4016]
* Getting a pre-configured Cache instance is not working as expected.
https://github.com/hazelcast/hazelcast/issues/4009[#4009]
* Bounded Queue section in the Reference Manual is unclear and wrong.
https://github.com/hazelcast/hazelcast/issues/3995[#3995]
* The method `checkFullyProcessed` of MapReduce throws null pointer
exception. The reason may be that multiple threads attempt to start the
final processing state in the JobSupervisor.
https://github.com/hazelcast/hazelcast/issues/3952[#3952]
* Merge operation after a split brain syndrome does not guarantee that
the merging is over.
https://github.com/hazelcast/hazelcast/issues/3863[#3863]
* When a client with near cache configuration enabled is shut down,
`RejectedExecutionException` is thrown.
https://github.com/hazelcast/hazelcast/issues/3669[#3669]
* In Hazelcast `IMap` and `TransactionalMap`, read-only operations such
as `get()`, `containsKey()`, `keySet()`, and `containsValue()` break the
transaction atomicity.
https://github.com/hazelcast/hazelcast/issues/3191[#3191]
* Documentation should clearly list features of and differences between
native clients.
https://github.com/hazelcast/hazelcast/issues/2385[#2385]
* Sections of Hazelcast configuration should be able to be imported so
that these sections can be shared between other Hazelcast configurations.
https://github.com/hazelcast/hazelcast/issues/406[#406]
