

== 3.4.3

The following is the the enhancement performed for 3.4.3 release.

* Expose `TcpIpJoiner.MAX_PORT_TRIES` as a configurable property
https://github.com/hazelcast/hazelcast/issues/5062[[#5062]].

The following are the fixed issues for 3.4.3 release.

* Subsequent remove operations may cause reading of stale value from the
map store https://github.com/hazelcast/hazelcast/issues/5368[[#5368]].
* Write-behind may cause reading of stale value upon migration
https://github.com/hazelcast/hazelcast/issues/5339[[#5339]].
* Hazelcast client is unresponsive. `OperationTimeoutException` is seen
in the logs https://github.com/hazelcast/hazelcast/issues/5338[[#5338]].
* Last update time of an entry should not be changed after `getAll()` is
invoked https://github.com/hazelcast/hazelcast/issues/5333[[#5333]].
* `AtomicReference.alterAndGet()` throws
`HazelcastSerializationException`
https://github.com/hazelcast/hazelcast/issues/5265[[#5265]].
* `ICompletableFuture` callback from the method `getAsync` is not always
invoked https://github.com/hazelcast/hazelcast/issues/5133[[#5133]].
* Warnings and exceptions are logged when closing the client connection
https://github.com/hazelcast/hazelcast/issues/4966[[#4966]].
* `CacheConfig` is not created on the cluster if the executer of
`CacheCreateConfigOperation` has already a `CacheConfig`
https://github.com/hazelcast/hazelcast/issues/4960[[#4960]].
* The schema does not allow for an explicit `hz:replicatedMap` element
to be created. One can be created inside `hz:config` but not as a
definition for a concrete Replicated Map. Therefore, at present it is
impossible to define a Replicated Map using Spring.
https://github.com/hazelcast/hazelcast/issues/4958[[#4958]].
* `ResponseThread` and `InvocationRegistry.InspectionThread` reset and
retry operations. Since these threads did not implement `NIOThread`, the
`OperationExecutor` is free to execute tasks on these threads and that
is not desirable
https://github.com/hazelcast/hazelcast/issues/4929[[#4929]].
* The method `CacheManager.getCache()` does not re-open the closed
cache. It should let access to the closed cache and re-open it. Cache
can be accessed by `getCache` but it is still closed
https://github.com/hazelcast/hazelcast/issues/4631[[#4631]].
* The method `close()` of a Closeable `CacheLoader` is called without
explicitly calling the method `Cache.close()`
https://github.com/hazelcast/hazelcast/issues/4617[[#4617]].
* The method `Cache.close()` does not call the method `close()` of
registered Closeable `CacheEntryListener`
https://github.com/hazelcast/hazelcast/issues/4616[[#4616]].
* The method `awaitNanos()` returns the wrong value for both the
`ClientConditionProxy` and `ConditionImpl` classes
https://github.com/hazelcast/hazelcast/issues/4603[[#4603]].
* The method `NotEqualPredicate` should return false if entry is null
(without index) and also if index is present, it should not throw an
exception with null values
https://github.com/hazelcast/hazelcast/issues/4525[[#4525]].
* When running Hazelcast with Spring and Hibernate 4 and when an
application is started, the error related to
`org/hibernate/cache/QueryResultsRegion` is produced
https://github.com/hazelcast/hazelcast/issues/4519[[#4519]].
* `OperationTimeoutException` when calling `get` on task future after
`hazelcast.operation.call.timeout.millis`
https://github.com/hazelcast/hazelcast/issues/4398[[#4398]].
* Predicates with null values throws exception for unordered indexes
https://github.com/hazelcast/hazelcast/issues/4373[[#4373]].
* The method `queue.take()` does not get interrupted on shutdown
https://github.com/hazelcast/hazelcast/issues/4143[[#4143]].
