
== 3.5.1

The following are the fixed issues for Hazelcast 3.5.1 release.

* Hazelcast Management Center uses `UpdateMapConfigOperation` to update
map configurations. This operation simply replaces the map configuration
of the related map container. However, this replacement has no effect
for `maxIdleSeconds` and `timeToLiveSeconds` properties of the map
configuration since they are not used in the map container directly.
They are assigned to the final variables during map container creation
and never touched again
https://github.com/hazelcast/hazelcast/issues/5593[[#5593]].
* Destroying a map just after creating it produces double create/destroy
events for `DistributedObjectListener`
https://github.com/hazelcast/hazelcast/issues/5592[[#5592]].
* Map does not allow changing its maximum size, TTL and maximum idle
properties. However, these fields are editable in the ``Map Config''
popup of Management Center. These fields should be disabled to prevent
misguiding https://github.com/hazelcast/hazelcast/issues/5591[[#5591]].
* Map is destroyed using `IMap.destroy()` but then it is immediately
recreated https://github.com/hazelcast/hazelcast/issues/5554[[#5554]].
* There should be a better calculation when calling the method
`getApproximateMaxSize()` related to casting. Its return type is `int`
and this causes the map entries to be evicted all the time when, for
example, the eviction policy for an IMap is set to heap percentage with
the value 1%
https://github.com/hazelcast/hazelcast/issues/5516[[#5516]].
* All `onResponse()` calls on a `MultiExecutionCallback` should be made
before the method `onComplete()` is called. There exists a race
condition in `ExecutionCallbackAdapterFactory` which permits the method
`onComplete()` to be called before all `onResponse()` calls are made
https://github.com/hazelcast/hazelcast/issues/5490[[#5490]].
* Hazelcast Management Center ``Scripting'' tab is not refreshed when a
new node joins to the cluster
https://github.com/hazelcast/hazelcast/issues/4738[[#4738]].
* When updating a map entry which is replicated over WAN, the TTL (time
to live) is not honored in the remote cluster map. When the timeout
expires, the entry disappears from the cluster in which the key is
owned, however it remains in the remote cluster
https://github.com/hazelcast/hazelcast/issues/254[[#254]].

The following are the enhancements performed for Hazelcast 3.5.1
release.

* Client instances should spawn threads with their instance names added
as prefix https://github.com/hazelcast/hazelcast/issues/5671[[#5671]].
* The method
`com.hazelcast.spi.impl.classicscheduler.ResponseThread::process` may
catch throwables. When this occurs, it logs an unhelpful message, and
ignores the actual exception. This method should be improved to
additionally log the cause, or at least the exception class and message
https://github.com/hazelcast/hazelcast/issues/5619[[#5619]].
* The element `min-eviction-check-millis` in the map configuration does
not exist in documentation
https://github.com/hazelcast/hazelcast/issues/5614[[#5614]].
