
== 3.5.2

The following are the fixed issues for Hazelcast 3.5.2 release.

* There is a performance issue: Even when the Spring boot application is
doing nothing, CPU consumption is very high. A thread named
``.hazelcast-wm.ensureInstance'' consumes CPU around 70% because of the
method `ClusteredSessionService.run()`
https://github.com/hazelcast/hazelcast/issues/6052[[#6052]].
* MapLoader blocks the entire partition when loading a single entry
https://github.com/hazelcast/hazelcast/issues/5818[[#5818]].
* The method `IMap.getAll` by-passes interceptors in the Hazelcast 3.3
and higher versions
https://github.com/hazelcast/hazelcast/issues/5775[[#5775]].
* `AWSJoiner` fails for the regions except us-east-1
https://github.com/hazelcast/hazelcast/issues/5653[[#5653]].
* Getting an instance of `sun.misc.Unsafe` class does not work on HP-UX
operating system
https://github.com/hazelcast/hazelcast/issues/5518[[#5518]].
* `AWSAddressTranslator` always uses the default region and this causes
the HazelcastClient to be unable to join a Hazelcast AWS cluster in a
non-default region
https://github.com/hazelcast/hazelcast/issues/5446[[#5446]].
* The test code `JettyWebFilterTest.java` does not fail properly
https://github.com/hazelcast/hazelcast/issues/5188[[#5188]].
* Management Center behaves unfriendly when map entries increase
https://github.com/hazelcast/hazelcast/issues/4895[[#4895]].
* In `hazelcast-client.xml`, if the region is configured but
`host-header` is not provided, the configuration gives a default
endpoint value of `ec2.amazonaws.com`. It should give, for example,
`ec2.eu-west-1.amazonaws.com` when the region is eu-west-1 and
`host-header` is not provided
https://github.com/hazelcast/hazelcast/issues/4731[[#4731]].
* Too much CPU is used when Hazelcast is idle
https://github.com/hazelcast/hazelcast/issues/81[[#81]].
