
== 3.5

This section lists the new features, enhancements and fixed issues for
3.5 release.

=== New Features

The following are the new features introduced with 3.5 release.

* *Async Back Pressure*: The Back Pressure introduced with Hazelcast 3.4
now supports async operations. For more information, please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#back-pressure[Back
Pressure section].
* *Client Configuration Import*: Hazelcast now supports replacing
variables with system properties in the declarative configuration of
Hazelcast client. Moreover, now you can compose the Hazelcast client
declarative configuration out of smaller configuration snippets. For
more information, please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#composing-declarative-configuration[Composing
Declarative Configuration section].
* *Cluster Quorum*: This feature enables you to define the minimum
number of machines required in a cluster for the cluster to remain in an
operational state. For more information, please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#cluster-quorum[Cluster
Quorum section].
* *Hazelcast Client Protocol*: Starting with 3.5, Hazelcast introduces
the support for different versions of clients in a cluster. Please keep
in mind that this support is not valid for the releases before 3.5.
Please see the important note at the last paragraph of the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#hazelcast-java-client[Hazelcast
Java Client chapter’s] introduction.
* *Listener for Lost Partitions*: This feature notifies you for possible
data loss occurrences. Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#partition-lost-listener[Partition
Lost Listener section] and
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#mappartitionlostlistener[MapPartitionLostListener
section].
* *Increased Visibility of Slow Operations*: With the introduction of
the `SlowOperationDetector` feature, slow operations are logged and can
be seen on the Hazelcast Management Center. Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#slowoperationdetector[SlowOperationDetector
section] and
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#members[Management
Center:Members section].
* *Enterprise WAN Replication*: Hazelcast Enterprise implementation of
the WAN Replication. Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#enterprise-wan-replication[Enterprise
WAN Replication section].
* *Sub-Listener Interfaces for Map Listener*: This feature enables you
to listen to map-wide or entry-based events. With this new feature, the
listener formerly known as `EntryListener` has been changed to
`MapListener` and `MapListener` has sub-interfaces to catch map/entry
related events. Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#map-listener[Map
Listener section] for more information.
* *Scalable Map Loader*: With this feature, you can load your keys
incrementally if the number of your keys is large. Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#incremental-key-loading[Incremental
Key Loading section].
* *Near Cache for JCache*: Now you can use a near cache with Hazelcast’s
JCache implementation. Please see
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#jcache-near-cache[JCache
Near Cache] for details.
* *Fail Fast on Invalid Configuration*: With this feature, Hazelcast
throws a meaningful exception if there is an error in the declarative or
programmatic configuration. Please see the note at the end of the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#configuration-overview[Configuration
Overview section].
* *Continuous Query Caching*: (Enterprise only, since 3.5) Provides an
always up to date view of an IMap according to the given predicate.
Please see the
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#continuous-query-cache[Continuous
Query Cache section]
* Dynamic Selector Rebalancing
* Management of Unbounded Return Values

=== Enhancements

The following are the enhancements introduced with 3.5 release.

* *Eventing System Improvements*: RingBuffer and Reliable Topic
structures are introduced.
* *XA Transactions Improvements*: With this improvement, you can now
obtain a Hazelcast XA Resource instance through `HazelcastInstance`. For
more information, please see
http://docs.hazelcast.org/docs/3.5/manual/html-single/index.html#xa-transactions[XA
Transactions].
* *Query and Indexing Improvements*

The following are the other improvements performed to solve the
enhancement issues opened by the Hazelcast customers/team.

* While configuring JCache, duration of the `ExpiryPolicy` can be set
programmatically but not declaratively
https://github.com/hazelcast/hazelcast/issues/5347[[#5347]].
* Since near cache is not supported as embedded but only at client, at
the moment, there is no need for `NearCacheConfig` in `CacheConfig`
https://github.com/hazelcast/hazelcast/issues/5215[[#5215]].
* Support for parametrized test is needed
https://github.com/hazelcast/hazelcast/issues/5182[[#5182]].
* `SlowOperationDetector` should have an option to not to log the
stacktraces to the log file. There is no need to have the stacktraces
written to the normal log file if the Hazelcast Management Center or the
performance monitor is being used
https://github.com/hazelcast/hazelcast/issues/5043[[#5043]].
* The batch launcher should include the JCache API
https://github.com/hazelcast/hazelcast/issues/4902[[#4902]].
* There are no Spring tags available for Native Memory configuration
https://github.com/hazelcast/hazelcast/issues/4772[[#4772]].
* In the class `BasicInvocationFuture`, there is no need to create an
additional `AtomicInteger` object. It should be replaced with
`AtomicIntegerFieldUpdater`
https://github.com/hazelcast/hazelcast/issues/4408[[#4408]].
* There is no need to use the class `IsStillExecutingOperation` to check
if an operation is running locally. One can directly access to the
scheduler https://github.com/hazelcast/hazelcast/issues/4407[[#4407]].
* Configuring NearCache in a Client/Server system only talks about the
programmatic configuration of NearCache on the clients. The declarative
configuration (XML) of the same is not mentioned
https://github.com/hazelcast/hazelcast/issues/4376[[#4376]].
* XML schema and XML configuration validation is not compliant for AWS
configuration
https://github.com/hazelcast/hazelcast/issues/4310[[#4310]].
* The JavaDoc for the methods `KeyValueSource.hasNext/element/key` and
`Iterator.hasNext/next` should emphasize the differences between each
other, i.e. the state changing behavior should be clarified
https://github.com/hazelcast/hazelcast/issues/4218[[#4218]].
* While migration is in progress, the nodes will have different
partition state versions. If the query is running at that time, it can
get results from the nodes at different stages of the migration. By
adding partition state version to the query results, it can be checked
whether the migration was happening and the query can be re-run
https://github.com/hazelcast/hazelcast/issues/4206[[#4206]].
* XML Config Schema does not allow to set a `SecurityInterceptor`
Implementation
https://github.com/hazelcast/hazelcast/issues/4118[[#4118]].
* Currently, certain types of remote executed calls are stored into the
`executingCalls` map. The key (and value) is a `RemoteCallKey` object.
The functionality provided is the ability to ask on the remote side if
an operation is still executing. For a partition-aware operation, this
is not needed. When an operation is scheduled by a partition specific
operation thread, the operation can be stored in a volatile field in
that thread https://github.com/hazelcast/hazelcast/issues/4079[[#4079]].
* The class `TcpIpJoinerOverAWS` fails at AWS’ recently launched
eu-central-1 region. The reason for the fail is that the region requires
v4 signatures
https://github.com/hazelcast/hazelcast/issues/3963[[#3963]].
* API change in `EntryListener` breaks the compatibility with the Camel
Hazelcast component
https://github.com/hazelcast/hazelcast/issues/3859[[#3859]].
* The `hazelcast-spring-<`__version__`>.xsd` should include the User
Defined Services (SPI) elements and attributes
https://github.com/hazelcast/hazelcast/issues/3565[[#3565]].
* XA Transactions run on multiple threads
https://github.com/hazelcast/hazelcast/issues/3385[[#3385]].
* Hazelcast client fails to connect when you provide variables from the
system properties
https://github.com/hazelcast/hazelcast/issues/3270[[#3270]].
* Entry listeners are not called when the entries are modified by WAN
replication https://github.com/hazelcast/hazelcast/issues/2981[[#2981]].
* Map wildcard matching is confusing. There should be a pluggable
wildcard configuration resolver
https://github.com/hazelcast/hazelcast/issues/2431[[#2431]].
* The method `loadAllKeys()` in map is not scalable
https://github.com/hazelcast/hazelcast/issues/2266[[#2266]].
* Back pressure feature should be added
https://github.com/hazelcast/hazelcast/issues/1781[[#1781]].

=== Fixes

The following are the issues solved for Hazelcast 3.5 release.

* Operation timeout mechanism is not working
https://github.com/hazelcast/hazelcast/issues/5468[[#5468]].
* `MapLoader` exception is not logged: Exception should be logged and
propagated back to the client that triggered the loading of the map
https://github.com/hazelcast/hazelcast/issues/5430[[#5430]].
* Replicated Map documentation page does not mention that it is in the
beta stage https://github.com/hazelcast/hazelcast/issues/5424[[#5424]].
* The method `XAResource.rollback()` should not need the transaction to
be in the prepared state when called from another member/client
https://github.com/hazelcast/hazelcast/issues/5401[[#5401]].
* The method `XAResource.end()` should not need to check `threadId`
https://github.com/hazelcast/hazelcast/issues/5400[[#5400]].
* The method `IList::remove()` should publish the event `REMOVED`
https://github.com/hazelcast/hazelcast/issues/5386[[#5386]].
* `IllegalStateException` with wrong partition is thrown when the method
`IMap::getOperation()` is invoked
https://github.com/hazelcast/hazelcast/issues/5341[[#5341]].
* `WrongTarget` warnings appear in the log since the operations are not
sent to the replicas when a map has no backups
https://github.com/hazelcast/hazelcast/issues/5324[[#5324]].
* When the method `finalizeCombine()` is used, Hazelcast throws
`NullPointerException`
https://github.com/hazelcast/hazelcast/issues/5283[[#5283]].
* `WanBatchReplication` causes `OutOfMemoryException` when the default
value for WAN Replication Batch Size (50) is used
https://github.com/hazelcast/hazelcast/issues/5280[[#5280]].
* When testing Hazelcast, it does not start as an OSGI bundle. After the
OSGI package was refactored, the dynamic class loading of the Script
engine was missed
https://github.com/hazelcast/hazelcast/issues/5274[[#5274]].
* XA Example from Section 11.3.5 in the Reference Manual broken after
the latest XA Improvements are committed
https://github.com/hazelcast/hazelcast/issues/5273[[#5273]].
* XA Transaction throws `TransactionException` instead of an
`XAException` on timeout
https://github.com/hazelcast/hazelcast/issues/5260[[#5260]].
* The test for unbounded return values runs forever with the new client
implementation
https://github.com/hazelcast/hazelcast/issues/5230[[#5230]].
* The new client method `getAsync()` fails with a
`NegativeArraySizeException`
https://github.com/hazelcast/hazelcast/issues/5229[[#5229]].
* The method `putTransient` actuated the MapStore unexpectedly in an
environment with multiple instances
https://github.com/hazelcast/hazelcast/issues/5225[[#5225]].
* Changes made by the interceptor do not appear in the backup
https://github.com/hazelcast/hazelcast/issues/5211[[#5211]].
* The method `removeAttribute` will prevent any updates by the method
`setAttribute` in the deferred write mode
https://github.com/hazelcast/hazelcast/issues/5186[[#5186]].
* Backward compatibility of eviction configuration for cache is broken
since `CacheEvictionConfig` class was renamed to `EvictionConfig` for
general usage
https://github.com/hazelcast/hazelcast/issues/5180[[#5180]].
* Value passed into `ICompletableFuture.onResponse()` is not
deserialized
https://github.com/hazelcast/hazelcast/issues/5158[[#5158]].
* Map Eviction section in the Reference Manual needs more clarification
https://github.com/hazelcast/hazelcast/issues/5120[[#5120]].
* When host names are not registered in DNS or in `/etc/hosts` and the
members are configured manually with IP addresses and while one node is
running, a second node joins to the cluster 5 minutes after it started
https://github.com/hazelcast/hazelcast/issues/5072[[#5072]].
* The method `OperationService.asyncInvokeOnPartition()` sometimes fails
https://github.com/hazelcast/hazelcast/issues/5069[[#5069]].
* The `SlowOperationDTO.operation` shows only the class name, not the
package. This can lead to ambiguity and the actual class cannot be
tracked https://github.com/hazelcast/hazelcast/issues/5041[[#5041]].
* There is no documentation comment for the `MessageListener` interface
of ITopic https://github.com/hazelcast/hazelcast/issues/5019[[#5019]].
* The method `InvocationFuture.isDone` returns `true` as soon as there
is a response including `WAIT_RESPONSE`. However, `WAIT_RESPONSE` is an
intermediate response, not a final one
https://github.com/hazelcast/hazelcast/issues/5002[[#5002]].
* The method `InvocationFuture.andThen` does not deal with the null
response correctly
https://github.com/hazelcast/hazelcast/issues/5001[[#5001]].
* `CacheCreationTest` fails due to the multiple
`TestHazelcastInstanceFactory` creations in the same test
https://github.com/hazelcast/hazelcast/issues/4987[[#4987]].
* When Spring dependency is upgraded to 4.1.x, an exception related to
the `putIfAbsent` method is thrown
https://github.com/hazelcast/hazelcast/issues/4981[[#4981]].
* HazelcastCacheManager should offer a way to access the underlying
cache manager
https://github.com/hazelcast/hazelcast/issues/4978[[#4978]].
* Hazelcast Client code allows to use the value _0_ for the
`connectionAttemptLimit` property which internally results in
`int.maxValue`. However, the XSD of the Hazelcast Spring configuration
requires it to be at least 1
https://github.com/hazelcast/hazelcast/issues/4967[[#4967]].
* Updates from Entry Processor does not take `write-coalescing` into
account https://github.com/hazelcast/hazelcast/issues/4957[[#4967]].
* CachingProvider does not honor custom URI
https://github.com/hazelcast/hazelcast/issues/4943[[#4943]].
* Test for the method `getLocalExecutorStats()` fails spuriously
https://github.com/hazelcast/hazelcast/issues/4911[[#4911]].
* Missing documentation of network configuration for JCache
https://github.com/hazelcast/hazelcast/issues/4905[[#4905]].
* Slow operation detector throws a `NullPointerException`
https://github.com/hazelcast/hazelcast/issues/4855[[#4855]].
* Consider use of `System.nanoTime` in `sleepAtLeast` test code
https://github.com/hazelcast/hazelcast/issues/4835[[#4835]].
* When upgraded to 3.5-SNAPSHOT for testing, Hazelcast project gives a
warning that mentions a missing configuration for
`hazelcastmq.txn-topic`
https://github.com/hazelcast/hazelcast/issues/4790[[#4790]].
* `ClassNotFoundException` when using WAR classes with JCache API
https://github.com/hazelcast/hazelcast/issues/4775[[#4775]].
* When Hazelcast is installed using Maven in Windows environment, the
test `XmlConfigImportVariableReplacementTest` fails
https://github.com/hazelcast/hazelcast/issues/4758[[#4758]].
* When a request cannot be executed due to a problem (connection error,
etc.), if the operation redo is enabled, request is retried. Retried
operations are offloaded to an executor, but after offloading, the user
thread still tries to retry the request. This causes anomalies like
operations being executed twice or operation responses being handled
incorrectly https://github.com/hazelcast/hazelcast/issues/4693[[#4693]].
* Client destroys all connections when a reconnection happens
https://github.com/hazelcast/hazelcast/issues/4692[[#4692]].
* The `size()` method for a replicated map should return `0` when the
entry is removed
https://github.com/hazelcast/hazelcast/issues/4666[[#4666]].
* `NullPointerException` on the `CachePutBackupOperation` class
https://github.com/hazelcast/hazelcast/issues/4660[[#4660]].
* When removing keys from a MultiMap with a listener, the method
`entryRemoved()` is called. In order to get the removed value, one must
call the `event.getValue()` instead of `event.getOldValue()`
https://github.com/hazelcast/hazelcast/issues/4644[[#4644]].
* Unnecessary deserialization at the server side when using
`Cache.get()`
https://github.com/hazelcast/hazelcast/issues/4632[[#4632]].
* Operation timeout exception during `IMap.loadAllKeys()`
https://github.com/hazelcast/hazelcast/issues/4618[[#4618]].
* There have been Hazelcast AWS exceptions after the version of AWS
signer had changed (from v2 to v4)
https://github.com/hazelcast/hazelcast/issues/4571[[#4571]].
* In the declarative configuration; when a variable is used to specify
the value of an element or attribute, Hazelcast ignores the strings that
come before the variable
https://github.com/hazelcast/hazelcast/issues/4533[[#4533]].
* `LocalRegionCache` cleanup is working wrongly
https://github.com/hazelcast/hazelcast/issues/4445[[#4445]].
* Repeatable-read does not work in a transaction
https://github.com/hazelcast/hazelcast/issues/4414[[#4414]].
* Hazelcast instance name with `Hibernate` still creates multiple
instances https://github.com/hazelcast/hazelcast/issues/4374[[#4374]].
* In Hazelcast 3.3.4, `FinalizeJoinOperation` times out if the method
`MapStore.loadAllKeys()` takes more than 5 seconds
https://github.com/hazelcast/hazelcast/issues/4348[[#4348]].
* JCache sync listener completion latch problems: Status of
`ICompletableFuture` while waiting for completion latch in the cache
must be checked
https://github.com/hazelcast/hazelcast/issues/4335[[#4335]].
* Classloader issue with `javax.cache.api` and Hazelcast 3.3.1
https://github.com/hazelcast/hazelcast/issues/3792[[#3792]].
* Failed backup operation on transaction commit causes ``''Nested
transactions are not allowed!" warning
https://github.com/hazelcast/hazelcast/issues/3577[[#3577]].
* Hazelcast Client should not ignore the fact that the XML is for server
and should not use default XML feature to connect to `localhost`
https://github.com/hazelcast/hazelcast/issues/3256[[#3256]].
* Owner connection `read()` forever
https://github.com/hazelcast/hazelcast/issues/3401[[#3401]].
