
== 3.6

This section lists the new features, enhancements and fixed issues for
3.6 release.

[[features-36]]
=== New Features

The following are the new features introduced with 3.6 release.

* *High-Density Memory Store for Hazelcast Map*: With this release,
Hazelcast Map data structure is now equipped with the High-Density
Memory Store, previously implemented for Hazelcast JCache. Please refer
to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#setting-in-memory-format[Setting
In Memory Format section].
* *Discovery Service Provider Interface (Discovery SPI)*: You can use
this SPI to discover Hazelcast instances on cloud environments provided
by jclouds®, Kubernetes and many more. The existing discovery mechanisms
that Hazelcast provides (Multicast, TCP/IP and Amazon EC2) have been
re-implemented on top of this new Discovery SPI. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#discovery-spi[Discovery
SPI section].
* *Client Protocol*: This feature presents the Hazelcast’s new open
binary client protocol. See the http://hazelcast.org/documentation/[Open Binary Client Protocol
Documentation].
* *Client Cross Version Compatibility*: Now you can upgrade your
Hazelcast clients independently from servers and other clients. Please
refer to http://hazelcast.org/documentation/[Open Binary Client Protocol
Documentation].
* *Support for cloud providers through jclouds®*: Hazelcast now supports
deployments on all the well-known cloud providers through the jclouds®
open source library. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#discovering-members-with-jclouds[Discovering
Members with jclouds section].
* *Hot Restart Persistence*: This new feature provides fast restarting
of the Hazelcast clusters. This is achieved by storing the state of the
cluster members to the disk. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#hot-restart-persistence[Hot
Restart Persistence section] for more details.
* *Ringbuffer and Reliable Topic in Hazelcast Clients*: The data
structures Ringbuffer and Reliable Topic recently introduced by
Hazelcast (with the release 3.5) are now implemented for Hazelcast Java
Client. Ringbuffer has also been implemented for .NET Client.
* *Cluster Quorum for Hazelcast JCache*: Cluster Quorum checks are now
provided for Hazelcast JCache implementations, too. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#defining-a-cluster-quorum[Defining
a Cluster Quorum section] to refresh and the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#icache-configuration[ICache
Configuration section] to learn configuring it for JCache.
* *Split Brain Syndrome handler for Hazelcast JCache*: Now Split Brain
Syndrome is handled in JCache as it is taken care in Hazelcast Map.
See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#jcache-split-brain[JCache
Split-Brain section]. 
* *Partition Lost Listener for Hazelcast JCache*: You can listen to
partition lost events fired in your Hazelcast JCache implementation.
See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#icache-configuration[ICache
Configuration section].
* *Hazelcast Docker image*: Now you can run Hazelcast using our image in
the Docker platform. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#deploying-using-docker[Deploying
using Docker section].
* *Lite Members*: With the re-introduction of Hazelcast Lite Members (it
was removed starting with Hazelcast 3.0 release), you are able to
specify certain members in your cluster so that they do not store data.
You can use these lite members mostly for your task executions and
listener registrations. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#enabling-lite-members[Enabling
Lite Members section].
* *Querying in collections and arrays*: Hazelcast is now able to query
and index attributes of objects stored in a collection or array. Please
refer to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#querying-in-collections-and-arrays[Querying
in collections section].
* *Custom attributes extraction*: It is now possible to extract a value
of an object’s attribute using a custom extractor class. See the
the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#custom-attributes[Custom
attributes section].
* *Acquiring locks with a lease time*: Now, you can try to acquire locks
with a lease time. See the the comment for the method
`tryLock()` in
https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/core/ILock.java[ILock
code].
* *Monitoring the WAN replication*: You can now monitor the state of
your WAN replications using the Hazelcast Management Center. Please
refer to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#monitoring-wan-replication[Monitoring
WAN Replication section].

[[enhancements-36]]
=== Enhancements

The following are the enhancements introduced with 3.6 release.

* *Replicated Map improvements*: The implementation of Hazelcast
replicated maps has been revisited. Please especially refer to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#considerations-for-replicated-map[Considerations
for Replicated Map section].
* *Management Center improvements*: Alerting mechanism added. Please
refer to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#management-center[Management
Center section].
* *Paging Predicate improvements*: With the performed improvements, now
random page accessing is supported. See the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#filtering-with-paging-predicates[Filtering
with Paging Predicates section].
* *Rule based query optimizations*: This improvement introduces a query
optimizer based on static rewriting rules. The optimizer treats
predicates as immutable and returns a modified copy when the optimized
one is found. See the `hazelcast.query.optimizer.type`
property definition in the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#system-properties[System
Properties section].
* *WAN replication improvements*: With the improvements performed on
Hazelcast’s WAN replication feature, you can now monitor WAN replication
events for each data structure and WAN replication now supports
different acknowledge types for each target cluster group. Please refer
to the
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#wan-replication-event-filtering-api[WAN
Replication Event Filtering API section] and
http://docs.hazelcast.org/docs/3.6/manual/html-single/index.html#wan-replication-acknowledge-types[WAN
Replication Acknowledge Types section] for more information.
* *Improvements on Hazelcast’s OSGI support*: With this improvement,
Hazelcast bundles provide OSGI services so that the users can manage
(create, access, shutdown) the Hazelcast instances through this service
on OSGI environments. Having the `hazelcast.osgi.start` property
enabled, when an Hazelcast OSGI service is activated, a default
Hazelcast instance is created automatically. These instances can be
served as an OSGI service to be accessed by other bundles. Registering
the created Hazelcast instances behavior is enabled by default and can
be disabled using the `hazelcast.osgi.register.disabled` property. Each
Hazelcast bundle provides a different OSGI service and their instances
can be grouped (clustered) together to prevent possible compatibility
issues between different Hazelcast versions/bundles. This grouping
behavior is enabled by default and can be disabled using the
`hazelcast.osgi.grouping.disabled` property. Hazelcast OSGI service’s
lifecycle (and also the owned/created instances’ lifecycles) are the
same as the owner Hazelcast bundles. When the bundle is stopped
(deactivated), owned service and Hazelcast instances are also
deactivated/shutdown and deregistered automatically. Then, when the
bundle is re-activated, its service is registered again. In addition,
the Hazelcast Enterprise JAR file is also an OSGI bundle like the
Hazelcast OSS JAR file.

The following are the other improvements performed to solve the
enhancement issues opened by the Hazelcast customers/team.

* On WAN Replication Queue overrun, a `WANReplicationQueueFullException`
is expected, but instead, the client receives an
`UndefinedErrorCodeException`. https://github.com/hazelcast/hazelcast/issues/[#7241]
* Approximate `max-size` calculation should be removed for IMap
eviction. https://github.com/hazelcast/hazelcast/issues/6463[#6463]
* `SpringAwareWebFilter` should have a constructor which takes
properties as arguments. https://github.com/hazelcast/hazelcast/issues/6438[#6438]
* Client side and server side cache proxies handle `putAll` operation
one by one. This is not efficient. Records for this operation should be
grouped as per their partitions and should be sent and processed in
batches. https://github.com/hazelcast/hazelcast/issues/6367[#6367]
* Not requested events should not be sent to `MapListener` https://github.com/hazelcast/hazelcast/issues/6349[#6349]
* Inconsistent and potentially buggy design in `BasicCompletableFuture`.
https://github.com/hazelcast/hazelcast/issues/6080[#6080]
* Starting with `hazelcast-wm 3.3`, OSGI Manifest Spring package
imports should be optional. https://github.com/hazelcast/hazelcast/issues/6072[#6072]
* The new client determines the partition ID for every invocation for
data structures like queue and list where the partition ID is static.
There is no need for this behavior. It should calculate the partition ID
for once when the proxy is created and continue to re-use it. https://github.com/hazelcast/hazelcast/issues/5848[#5848]
* `Map.Entry` supplied to Entry Processor is not Serializable any more.
https://github.com/hazelcast/hazelcast/issues/5611[#5611]
* The configuration file `minimal-json` with the provided scope is not
picked up by the _shade_ plugin. https://github.com/hazelcast/hazelcast/issues/5543[#5543]
* In Spring configuration, when a boolean property is injected for
_hazelcast_ bean (`<hz:hazelcast:....</hz:hazelcast`) a `SAXParse`
exception is thrown. https://github.com/hazelcast/hazelcast/issues/5528[#5528]
* Currently, key/value pairs are deserialized prior to the execution of
entry processor by default. This leads to the need of domain object at
the server side, even if entry processor never uses it. https://github.com/hazelcast/hazelcast/issues/5301[#5301]
* In Spring XML configuration, the attributes of `socket-options` should
be of type `xs:string`. https://github.com/hazelcast/hazelcast/issues/4700[#4700]
* `ClientMembershipEvent` does not need to have the `member` field.
https://github.com/hazelcast/hazelcast/issues/4282[#4282]
* Hazelcast has `lock` with lease time feature but does not support
`tryLock` with lease time. https://github.com/hazelcast/hazelcast/issues/1564[#1564]

[[fixes-36]]
=== Fixes

The following are the fixed issues solved for 3.6 release.

*3.6 Fixes*

* Lock requests hang forever after a split-brain recovery: When a member
hangs a few minutes, the cluster assumes that this frozen member as dead
and the master kicks it. When the frozen member comes back, after some
time they figure out it was a split-merge back activity. Problem is,
some of the lock requests hang forever without a timeout after the
merge. That means some of the previously acquired locks cannot be
released and hang in the cluster infinitely; no one can acquire them and
there is no one to release them anymore. https://github.com/hazelcast/hazelcast/issues/8647[#8647]
* In the manifest file, `org.jclouds.*` should be marked as optional
dependencies. https://github.com/hazelcast/hazelcast/issues/7318[#7318]
* Tests are needed for `WanReplicationPublisherDelegate`,
`WanReplicationEvent`, `MapReplicationUpdate` and
`AbstractMultipleEntryBackupOperation` in the Open Source WAN API.
https://github.com/hazelcast/hazelcast/issues/7315[#7315]
* Invocation of quorum listener requires at least an attempt to perform
a map operation. But it should not require this; just the crash of nodes
should be enough to use the quorum mechanism. https://github.com/hazelcast/hazelcast/issues/7300[#7300]
* Owned entry count to be used as the expected near cache hit count
should be calculated by checking the partition ownership in the
`NearCacheTest::testGetAll`. https://github.com/hazelcast/hazelcast/issues/7285[#7285]
* The parameter `minEvictionCheckMillis` controls the maximum frequency
of evictions. It is 100ms by default. It means at most 1 eviction is
executed in a 100ms interval. No other `put()` operation within this
interval triggers an eviction. So, if the put rate is greater than 1 per
100ms, then the number of entries is growing regardless of the
`max-size-policy`. This eventually triggers a forced eviction which will
prevent `OutOfMemoryException`. Forced evictions are only hiding this
issue. Another possible solution is to keep the default interval as it
is and apply batching: When X eviction cycles are skipped due the
`minEvictionCheckMillis` parameter, then during the next cycle X + 1
entries should be evicted instead of just 1. https://github.com/hazelcast/hazelcast/issues/7268[#7268]
* Descriptions of some maximum size policies defined in the
`com.hazelcast.config.EvictionConfig.MaxSizePolicy` and
`com.hazelcast.config.MaxSizeConfig.MaxSizePolicy` are not clear and
confusing. They should be clarified. https://github.com/hazelcast/hazelcast/issues/7267[#7267]
* Tests under `TopicOverloadDistributedTest` are spuriously failing even
on the local machine. They need to be reviewed. https://github.com/hazelcast/hazelcast/issues/7266[#7266]

*3.6-RC1 Fixes*

This section lists the enhancements and fixed issues for 3.6-RC1
(Release Candidate 1) release.

* Javadoc for `IMap.putAll()` does not mention the lack of atomicity in
the invocation. https://github.com/hazelcast/hazelcast/issues/7256[#7256]
* When a WAN Queue overrun occurs (with exception enabled), the source
cluster logs an excessive amount of noise. This should to be logged.
https://github.com/hazelcast/hazelcast/issues/7242[#7242]
* When using Hazelcast as a JCache provider: As JSR-107 Javadoc states,
an update should not reset expiry time for `CreatedExpiryPolicy`.
However, when a cache entry is updated, it does not expire. https://github.com/hazelcast/hazelcast/issues/7236[#7236]
* Default WAN acknowledge type should be `ACK_ON_RECEIPT`. https://github.com/hazelcast/hazelcast/issues/7160[#7160]
* `NullPointerException` is thrown in
`ClientRegressionWithMockNetworkTest`. https://github.com/hazelcast/hazelcast/issues/7148[#7148]
* Changing clusters in the Management Center does not update/refresh the
cluster members in the Scripting tab. https://github.com/hazelcast/hazelcast/issues/7119[#7119]
* A fix is needed for operation retries in
`PartitionCheckIfLoadedOperation`. https://github.com/hazelcast/hazelcast/issues/7114[#7114]
* WAN Queue counts in the Management Center for Hazelcast 3.6-EA3 are
not correct. https://github.com/hazelcast/hazelcast/issues/7100[#7100]
* Hazelcast 3.6 Reference Manual is not correct for its Enterprise WAN
Replication content. https://github.com/hazelcast/hazelcast/issues/7099[#7099]

*3.6-EA3 Fixes*

This section lists the enhancements and fixed issues for 3.6-EA3 (Early
Access 3) release.

* `NullPointerException` is thrown for the thread `cached4` in a test
which uses `MapLoader`. https://github.com/hazelcast/hazelcast/issues/7098[#7098]
* The method `loadInternal` of `MapProxySupport` requires `dataKeys`.
Hence, a serialization step should be added to `MapProxy.loadAll()`.
https://github.com/hazelcast/hazelcast/issues/7090[#7090]
* Near cache heap cost calculation is not proper when the cache gets
concurrent misses. https://github.com/hazelcast/hazelcast/issues/7057[#7057]
* `IQueue` accepts null values from the Hazelcast Java client. https://github.com/hazelcast/hazelcast/issues/7048[#7048]
* `WriteBehindMapStore` for a map that has `OBJECT` as the in-memory
format causes the entry processors to serialize the objects. https://github.com/hazelcast/hazelcast/issues/7040[#7040]
* Latest code does not include the file
`com.hazelcast.client.impl.protocol.codec.CacheContainsKeyCodec` and
build fails. https://github.com/hazelcast/hazelcast/issues/7019[#7019]
* Two members of a cluster become masters and ignore each other. https://github.com/hazelcast/hazelcast/issues/7016[#7016]
* `AbstractCacheRecordStore` should update the field `isOwner` while it
is being cleared after migration. https://github.com/hazelcast/hazelcast/issues/6983[#6983]
* There are memory leaks in the local map statistics and near cache
invalidation queues. The map containers also leak memory caused either
by the near cache invalidation mechanism (when re-creating objects to
check whether the near cache is enabled) or
`MapPartitionDestroyOperation` (when re-creating objects and trying to
the backup count). https://github.com/hazelcast/hazelcast/issues/6972[#6972]
* When the `lite-member` flag is used within the Spring context, its
`enabled` attribute does not work properly. https://github.com/hazelcast/hazelcast/issues/6945[#6945]
* `LoadAllTask` for the client and server side cache proxies should also
handle the `Throwable`, not just the `Exception`. https://github.com/hazelcast/hazelcast/issues/6944[#6944]
* The `enable` attribute of the `partition-group` element in the
`Hazelcast-Spring.xsd` scheme should have the type `string`, not
`boolean`. https://github.com/hazelcast/hazelcast/issues/6927[#6927]
* There is a left-over method in the Discovery SPI configuration, namely
`addDiscoveryProviderConfig`. https://github.com/hazelcast/hazelcast/issues/6911[#6911]
* `InMemoryFormat.OBJECT` does not work with the `max-size` policies
`USED_HEAP_SIZE` and `USED_HEAP_PERCENTAGE`. https://github.com/hazelcast/hazelcast/issues/6875[#6875]
* `PublicAddressTest` has been ignored due to the running time. https://github.com/hazelcast/hazelcast/issues/6858[#6858]
* `NullPointerException` is thrown in `ClientExecutionPoolSizeLowTest`.
https://github.com/hazelcast/hazelcast/issues/6853[#6853]

*3.6-EA2 Fixes*

This section lists the enhancements and fixed issues for 3.6-EA2 (Early
Access 2) release.

* MapLoader may insert null values into IMap causing memory leak. https://github.com/hazelcast/hazelcast/issues/6830[#6830]
* When replicated map entries are migrated to a new destination; TTL
eviction should be scheduled, eviction should be retried when a failure
caused by the migration happens and the sync interval should be
increased. https://github.com/hazelcast/hazelcast/issues/6799[#6799]
* There is a logical error in the method `Ringbuffer.readManyAsync()`
when `minSize = 0`. In this case, the Ringbuffer is not read and nothing
is returned. https://github.com/hazelcast/hazelcast/issues/6787[#6787]
* When a listener’s registration is made from the listener
configuration, an error occurs during the listener initialization.
https://github.com/hazelcast/hazelcast/issues/6784[#6784]
* Remaining cache invalidation messages should be flushed on the
`ICacheService` while the member is in the `SHUTTING_DOWN` state. https://github.com/hazelcast/hazelcast/issues/6678[#6778]
* When a client cannot send a request to one of the connections,
`TargetNotMemberException` is thrown. This name is confusing the
Hazelcast users. https://github.com/hazelcast/hazelcast/issues/6766[#6766]
* `ClassCastException` is thrown when using `Timestamp` within
`DataSerializable`. https://github.com/hazelcast/hazelcast/issues/6759[#6759]
* The method `destroyDistributedObject()` of `ReplicatedMapService`
iterates over partition containers and record stores and destroys them.
While destroying, record store calls `destroyDistributedObject()` which
leads to an infinite loop. https://github.com/hazelcast/hazelcast/issues/6754[#6754]
* Hazelcast does not inject its instance into `HazelcastInstanceAware`
registered via classname. https://github.com/hazelcast/hazelcast/issues/6697[#6697]
* There is a sporadic startup failure in 3.6-EA. https://github.com/hazelcast/hazelcast/issues/6684[#6684]
* There is no need to use `CacheLoader` inside the client/server side
cache proxies. https://github.com/hazelcast/hazelcast/issues/6676[#6676]
* Fixed wrong calculation of eviction removal size when `PER_NODE`
`max-size` policy is used. https://github.com/hazelcast/hazelcast/issues/6671[#6671]
* If the cluster state is not active `RepartitioningTask` should not be
triggered. Otherwise, it causes infinite retries and prevents the member
from shutdown. https://github.com/hazelcast/hazelcast/issues/6663[#6663]
* There are broken XML configuration tests in the Hazelcast client
package. https://github.com/hazelcast/hazelcast/issues/6633[#6633]
* There is a memory leak since the method `publishBathcedEvents` does
not remove the events from `batchEvent`. https://github.com/hazelcast/hazelcast/issues/6618[#6618]
* Custom credentials class is not de-serialized on the server side.
https://github.com/hazelcast/hazelcast/issues/6615[#6615]
* Lite member element should be added to the Hazelcast Spring
configuration. https://github.com/hazelcast/hazelcast/issues/6605[#6605]
* `EntryListener` shows the unprocessed value in combination with
`PostProcessingMapStore`. https://github.com/hazelcast/hazelcast/issues/6588[#6588]
* Clients cannot submit `HazelcastInstanceAware` callables. https://github.com/hazelcast/hazelcast/issues/6570[#6570]

*3.6-EA Fixes*

The following are the issues solved for Hazelcast 3.6-EA (Early Access)
release.

* The method `map.size()` waits indefinitely after the shutdown of a
node. https://github.com/hazelcast/hazelcast/issues/6538[#6538]
* `HazelcastCachingProvider` does not use the specified instance (by the
object) when `instance-name` is not specified. https://github.com/hazelcast/hazelcast/issues/6454[#6454]
* `onExecutionFailure` should be called before returning from `run`, if
backup is not valid. https://github.com/hazelcast/hazelcast/issues/6420[#6420]
* `OperationThread.priorityPendingCount()` should return
`scheduleQueue.prioritySize()` instead of `scheduleQueue.normalSize()`.
https://github.com/hazelcast/hazelcast/issues/6318[#6318]
* There is a growth in heap usage caused by a memory leak in the
following scenario: A node in the cluster regularly creates maps and
puts entries into it, again in regular intervals. Another node removes
the entries minutes after they were put, and if the map is empty, it
destroys the map. https://github.com/hazelcast/hazelcast/issues/6317[#6317]
* Currently, there is an `EntryEvictedListener` that is notified both
for expiration and eviction events. There should be a separate listener
for expired entries: eviction happens due to size constraints, and
expiry is once the entry has expired. https://github.com/hazelcast/hazelcast/issues/6311[#6311]
* `InvocationFuture`s async calls do not detect the lost operations.
https://github.com/hazelcast/hazelcast/issues/6250[#6250]
* When the method `setBooleanAttribute` of the class `Member` is run,
Null Pointer Exception is occurred on `STDOUT`. The problem is in the
method `sendMemberAttributeEvent` of the class `ClusterServiceImpl`.
https://github.com/hazelcast/hazelcast/issues/6223[#6223]
* `IOBalancer` keeps references of all the socket reader/writers but
when destroying the connection, they release the references for only the
ones which has endpoints. This causes a memory leak. https://github.com/hazelcast/hazelcast/issues/6199[#6199]
* `ILIKE` and `Regex` examples should be added to the Reference Manual
under the `Supported SQL Syntax` section. https://github.com/hazelcast/hazelcast/issues/6190[#6190]
* `GroupProperty` defaulting does not work properly when programmatic
configuration is used. https://github.com/hazelcast/hazelcast/issues/6174[#6174]
* When integrating Hazelcast in Spring Boot: if `HazelcastInstance` is
created using the default `newHazelcastInstance` static method, then an
`HazelcastInstance` whose `Config` has a valid `configurationUrl`
property is created. However, `XmlBuilder` does not set this URL in the
configuration it parses. https://github.com/hazelcast/hazelcast/issues/6061[#6061]
* Hazelcast’s latest snapshot run fails due to the introduction of
`ClientExceptionFactory` which has been developed for exception
processing and working well in that sense. https://github.com/hazelcast/hazelcast/issues/6010[#6010]
* The class `HazelcastXATest` has only fast and slow modes (nothing in
between) and possibly due to this, sometimes a transaction is waiting
for a timeout. Either the transaction recovery or the test class itself
is racy. https://github.com/hazelcast/hazelcast/issues/5923[#5923]
* A memory leak occurs when a listener is added and removed from client.
A `remove` runnable in the collection that is stored in
`ClientEndpointImpl` is the leftover. This runnable collection is used
to cleanup the listeners when client is disconnected, it should be
removed too after the listener is removed. https://github.com/hazelcast/hazelcast/issues/5893[#5893]
* The class `CacheRemoveAllOperation` does not send the `completed`
event in some cases, e.g. if `CacheRecordStore` for that partition is
not created yet or if the filtered keys are empty. https://github.com/hazelcast/hazelcast/issues/5865[#5865]
* In the class `MapProxyImpl`, the methods `executeOnKey` and
`submitToKey` create an `EntryOperation` with the thread ID set. This
does not happen with the class `ClientMapProxy`. Therefore, the class
`MapExecuteOnKeyRequest` should take a thread ID and set this on the
generated `EntryOperation`. https://github.com/hazelcast/hazelcast/issues/5857[#5857]
* The method `IndexImpl.getRecords()` fails with Null Pointer Exception
due to the inconsistency between the `not(...equals())` and
`notEquals()`. https://github.com/hazelcast/hazelcast/issues/5807[#5807]
* The method `HazelcastHttpSession.getAttribute()` for WebFilter does
not work when `deferredWrite` is set to `true`. https://github.com/hazelcast/hazelcast/issues/5798[#5798]
* When `hazelcast.nio.faststring` is enabled, `UTFEncoderDecoder` tries
to create a `FastStringCreator`. However, if the reflection is not
available due to the security manager, `buildFastStringCreator` returns
null and consequently `StringCreator` becomes null. https://github.com/hazelcast/hazelcast/issues/5777[#5777]
* `hazelcast-jca-rar/pom.xml` references to `src/main/rar/ra.xml` which
does not exist. https://github.com/hazelcast/hazelcast/issues/5760[#5760]
* The Maven profile `mvn clean compile -Pqa` does not exist but it is
documented in the README of Hazelcast. https://github.com/hazelcast/hazelcast/issues/5746[#5746]
* `PerformanceLogFile` only compiles if JDK 1.7 or above is used. https://github.com/hazelcast/hazelcast/issues/5729[#5729]
* Currently, for every deserialization a `BufferObjectDataInput` is
created. This generates waste since it is created with an array of data
for every deserialization. The `BufferObjectDataOutput` is already
cached; the input should use a similar approach. https://github.com/hazelcast/hazelcast/issues/5562[#5562]
* When any entities are defined as read only in the Hibernate L2 cache,
an invalidation of the cache (such as caused by executing a native
SQLQuery) leads to the error `UnsupportedOperationException`. https://github.com/hazelcast/hazelcast/issues/5561[#5561]
* The performance impacts of TWO_PHASE and LOCAL transaction types
should be documented. https://github.com/hazelcast/hazelcast/issues/5075[#5075]
* Client requests are very inefficient when determining the partition
ID. https://github.com/hazelcast/hazelcast/issues/4940[#4940]
* The method `keySet()` relies on `QueryOperation`. The `QueryOperation`
does not accept `IterationType` - it always returns both keys and
values. This can lead to unnecessary load and potentially even an OOM
exception. https://github.com/hazelcast/hazelcast/issues/4642[#4642]
* Hazelcast is stuck in TIMED_WAITING when used as 2nd level cache for
Hibernate. https://github.com/hazelcast/hazelcast/issues/4406[#4406]
* Management Center license loading problem when REST API is used. https://github.com/hazelcast/hazelcast/issues/189[#189]
* Executor monitoring in Management Center does not show the
`cancelled` operations" https://github.com/hazelcast/hazelcast/issues/177[#177]
* When an alert for a data structure (map, queue, etc.) with its
specific name is created, a `NullPointerException` is thrown after the
cluster is reset. https://github.com/hazelcast/hazelcast/issues/175[#175]
* Default directory name is hardcoded as `mancenter3.5` and it needs
to be maintained for every major release. This process should be
dynamic. https://github.com/hazelcast/hazelcast/issues/174[#174]
* Throughput statistics for Map shows nothing when the `putAll()` method
is used. https://github.com/hazelcast/hazelcast/issues/159[#159]

[[contributors-36]]
===  Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/cszmajda[cszmajda]
* https://github.com/matjohns[Mat Johns]
* https://github.com/adessaigne[adessaigne]
* https://github.com/Fabryprog[Fabrizio Spataro]
* https://github.com/LoneRifle[LoneRifle]
* https://github.com/fwassmer[fwassmer]
* https://github.com/cetin[Çetin]
* https://github.com/henri-tremblay[Henri Tremblay]
