
== 3.6.4

The following are the fixed issues for 3.6.4 release.

* `OperationFactoryWrapper` should use `callersUUID` instead of
overriding on the member side. [8437]
* `HazelcastInstanceLoader` ignores ``instance-name'' for clients.
[8413]
* Usage of `GroupProperties` in Hibernate modules should be removed.
[8398]
* Thread interrupt flag check must be added to `StoreWorker`. [8345]
* Partition proxies are created eventually on all members. However, this
is an async process driven by the eventing system. If a member does not
have a proxy in its registry, then it will not fire
`MapPartitionLostListener`. Before firing a partition lost event,
proxies should be waited to be created. [8293]
* Ensure skipping previously removed `CacheEntryListenerConfiguration`
entries while iterating over added `CacheEntryListenerConfiguration` s in
the `CacheConfig` to register listeners. [8283]
* Hazelcast instance is started without problems but Management Center
does not launch and throws an exception when bundled Jetty is used with
Java versions 1.8.0_91 and higher. [8248]
