
== 3.7.1

The following are the fixed issues for 3.7.1 release.

* Behavior of JCache near cache invalidation events changed: (i) the
method `Cache.close` now delivers near cache invalidation events, (ii)
the method `Cache.destroy` no longer delivers invalidation events, (iii)
the method `CacheManager.destroyCache` when invoked from a client-side
cache manager no longer delivers invalidation events. https://github.com/hazelcast/hazelcast/issues/8801[#8801]
* Aggressive SQL predicate flattening may result in wrong parsing of
SQL. https://github.com/hazelcast/hazelcast/issues/8799[#8799]
* To properly configure within Spring context, incorrect client defaults
should be fixed. https://github.com/hazelcast/hazelcast/issues/8761[#8761]
* `NullPointerException` is thrown when the class `DefaultNodeExtension`
has been loaded by two different class loaders. https://github.com/hazelcast/hazelcast/issues/8755[#8755]
* `HazelcastInstanceNotActive` exception is thrown which is misleading.
When a remote member is shutdown while destroying a proxy, no warnings
should be logged. https://github.com/hazelcast/hazelcast/issues/8736[#8736]
* Missing dependency for JSPC plugin should be added. https://github.com/hazelcast/hazelcast/issues/297[#297]
