
== 3.8.3

The following are the fixed issues for Hazelcast 3.8.3 release.

* Hazelcast 3.8.1: calling `replace(K, old, new)` keeps the expiry time
as creation time + duration. But Hazelcast doesn’t seem to honor this
expiration even after calling `get()`.
https://github.com/hazelcast/hazelcast/issues/10817[#10817]
* When using a client side Near Cache, the cache statistics seem
incorrect when asking for a key that doesn’t exist.
https://github.com/hazelcast/hazelcast/issues/10806[#10806]
* Ringbuffer is not adjusting `headSeq` while setting `tailSeq` due to
capacity. https://github.com/hazelcast/hazelcast/issues/10774[#10774]
* Older versions of Mulesoft clash with Hazelcast Client classpath.
https://github.com/hazelcast/hazelcast/issues/10706[#10706]
* In the case when the master node is terminated in the middle of a
2-phase transaction, the rollback for that transaction is not performed.
This causes loss of data.
https://github.com/hazelcast/hazelcast/issues/10637[#10637]
* Adding/removing listeners fails if a member is removed in the
progress. https://github.com/hazelcast/hazelcast/issues/10595[#10595]
* When two callbacks are registered as callback to
`ClientDelegatingFuture`, if one of them wants to deserialize the
response while the other is does not, Hazelcast falsely gives null
response to the one waiting a deserialized value.
https://github.com/hazelcast/hazelcast/issues/10581[#10581]
* Eviction and `max-size` for less then 271 cause map to never populate.
https://github.com/hazelcast/hazelcast/issues/10179[#10179]
* `IOException` at the client side must be produced only if
`hazelcast.client.invocation.timeout.seconds` is passed.
https://github.com/hazelcast/hazelcast/issues/9696[#9696]
