
== 3.8.4

The following are fixed issues and enhancements for Hazelcast 3.8.4
release.

* Added timeout option for the `get` operation when Hazelcast is used
within the Spring context.
https://github.com/hazelcast/hazelcast/pull/11001/[#11001]
* HTTP HEAD support added to the REST interface.
https://github.com/hazelcast/hazelcast/pull/11000/[#11000]
* `ClientProxy` gets `NullPointerException` from the method `getClient`.
https://github.com/hazelcast/hazelcast/issues/10961[#10961]
* Added support for collecting and tracking statistics for all reliable
topic proxies on a local member. The statistics are destroyed when the
proxy is destroyed.
https://github.com/hazelcast/hazelcast/pull/10932/[#10932]
* The method `containsKey` returns `true` even the key does not exist
in the map.
https://github.com/hazelcast/hazelcast/issues/10923[#10923]
* Assuming a scenario in which invalidations are generated previously
for some other near caches and then later a new near cached map is
created, all entries that are near cached before the first
reconciliation period will be removed.
https://github.com/hazelcast/hazelcast/issues/10913[#10913]
* HTTP upload to Hazelcast fails. The code fails with the exception
`BufferOverflowException`.
https://github.com/hazelcast/hazelcast/issues/10878[#10878]
* The method `MapProxyImpl.executeOnKeys()` does not work when
`ConcurrentSkipListSet` is passed and throws `NullPointerException`.
https://github.com/hazelcast/hazelcast/issues/10877[#10877]

=== Known Issues

* *Upgrading from 3.6.x to 3.8.x (Hazelcast IMDG Enterprise) when using
`JCache`:* Due to a compatibility problem, `CacheConfig` serialization
may not work if your member is 3.8.x where x < 5. Hence, you will need
to use Hazelcast 3.8.5 or higher version where the problem is being
fixed. This issue affects Hazelcast IMDG Enterprise only.
