
== 3.8

This section lists the new features, enhancements, fixed issues and,
removed or deprecated features for 3.8 release.

[[features-38]]
=== New Features

The following are the new features introduced with 3.8 release.

*_Hazelcast IMDG Enterprise Features:_*

* *Rolling Member Upgrades for Minor Releases*: You can upgrade your
Hazelcast members to the next minor release without service
interruption. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#rolling-member-upgrades[Rolling Member Upgrades chapter].
* *Restore Hot Restart Data in a Different Cluster*: You will be able to
restore Hot Restart data on a completely new cluster with different IP
addresses or on a cluster of machines formed by existing and new IP
addresses. Since this is a removal of a restriction or limitation,
nothing will change for current Hot Restart Store users. See
the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#moving-copying-hot-restart-data[Moving/Copying Hot Restart Data section].

*_Hazelcast IMDG Open Source Features:_*

* *Continuous Query Cache*: With this release, the previously Enterprise
feature Continuous Query Cache becomes open source. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#continuous-query-cache[Continuous Query Cache section].
* *Cardinality Estimator*: Cardinality Estimator data structure is
implemented on top of Hazelcast to estimate cardinality. See
the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#cardinality-estimator-service[Cardinality Estimator Service section].
* *Scheduled Executor Service*: Distributed implementation of Java’s
`ScheduledExecutorService` API. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#scheduled-executor-service[Scheduled Executor
Service section].
* *User Code Deployment*: Load your new classes to Hazelcast IMDG
members dynamically without restarting all of them.

[[enhancements-38]]
=== Enhancements

The following are the enhancements introduced with 3.8 release.

* *Fast Aggregations for Queries*: See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#fast-aggregations[Fast Aggregations
section].
* *Projections for Queries*: See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#projections[Projections section].
* *Eventually Consistent Near Cache*: With this improvement, possible
losses of invalidation events are detected and stale reads are
prevented. See the http://docs.hazelcast.org/docs/latest/manual/html-single/index.html#eventual-consistency[Near Cache Eventual Consistency section].
* *Cluster Split-Brain Protection for Queue and Lock*: Split-brain
protection is now available for the queue and lock data structures.
See the sections http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#split-brain-protection-for-lock[Lock Split-Brain Protection] and http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#split-brain-protection-for-queue[Queue
Split-Brain Protection.]
* *Unified Near Cache Implementation*: Different near cache
implementations for JCache, map, client side and member side are
unified. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#near-cache[Near Cache section].
* *High Performance Near Cache*: A near cache preloader is introduced to
preserve the information about which keys are used in a populated near
cache. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#near-cache-preloader[Near Cache Preloader section].
* *`removeAll(predicate)` for Map*: You can remove all map entries that
match your predicate. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#removing-bulk-map-entries-with-predicates[Removing Bulk Map Entries
with Predicates section].
* *Ringbuffer with Persistent Datastore*: Implemented for the Ringbuffer
which is similar to the existing queue store mechanism. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#ringbuffer-with-persistent-datastore[Ringbuffer with Persistent Datastore section].
* *Hazelcast Striim Hot Cache Adapter*: Hot Cache functionality based on
Striim’s Change Data Capture (CDC) for the underlying database updates.
Note that this enhancement is available for Hazelcast Enterprise.
See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#hazelcast-striim-hot-cache[Hazelcast Striim Hot Cache section].
* *One-off WAN Synchronization with Dynamically Added Endpoint*:
Improvement to allow copying the maps’ all content to a target cluster
dynamically in runtime. Note that this enhancement is available
for Hazelcast Enterprise.
* *Hot Restart Usability Improvements*: When a cluster with Hot Restart
enabled is restarted, it starts in the ACTIVE state. Note that
this enhancement is available for Hazelcast Enterprise. See
the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#hot-restart-types[Hot Restart Types section].
* *Hot Restart with Incomplete Members*: The restart procedure for a
cluster having Hot Restart enabled is now more flexible by allowing you
to do a partial start, which basically means that once the cluster is
shutdown, it can be restarted with some missing members. Note
that this enhancement is available for Hazelcast Enterprise. See the
http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#partial-start[Partial Start section].
* *Copy Hot Restart Store data from Source to Target*: You can copy Hot
Restart Store data from a running cluster to a target without shutting
down the source cluster. Note that this enhancement is available
for Hazelcast Enterprise. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#movingcopying-hot-restart-data[Moving/Copying Hot Restart Data section].
* *Improvement in WAN Queue Full Behavior*: Now, Hazelcast throws an
exception when the queue is full and replication is active, unless it is
stopped on the Management Center. Note that this enhancement is
available for Hazelcast Enterprise. See the http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#queue-full-behavior[Queue Full
Behavior section].

The following are the other improvements performed to solve the
enhancement issues opened by the Hazelcast customers/team.

* Currently there are only MERGING and MERGED states for lifecycle, but
no event is fired for a failed merge. This would be informative and
further give an idea to user to understand a reason of a SHUTTING_DOWN
event since a failed merge is followed by a shutdown. https://github.com/hazelcast/hazelcast/issues/9856[#9856]
* Tests are needed to prove that `removeAll` does not deserialize
portables. https://github.com/hazelcast/hazelcast/issues/9474[#9474]
* Client support for distributed scheduled executor service. https://github.com/hazelcast/hazelcast/issues/9385[#9385]
* When a member without JCache service joins a cluster where JCache
service is enabled but not used, the member should not fail. https://github.com/hazelcast/hazelcast/issues/9301[#9301]
* It would be nice to have names assigned to all threads created by
Hazelcast (and not the default ones, e.g., `pool-2-thread-1`,
`pool-2-thread-2`). https://github.com/hazelcast/hazelcast/issues/9210[#9210]
* There should be a more detailed and clarifying information in the
diagnostics of `PartitionIteratingOperation`. https://github.com/hazelcast/hazelcast/issues/8855[#8855]
* When there is no access to `NodeEngine`, the logger should be able to
be used from a static context without any side effects to the logging
configuration. https://github.com/hazelcast/hazelcast/issues/8760[#8760]
* Client tasks should be bounced back when a member has not completely
start yet. https://github.com/hazelcast/hazelcast/issues/8715[#8715]
* A method `size(Predicate)` should be added to determine the size of
predicate results. https://github.com/hazelcast/hazelcast/issues/8555[#8555]
* Currently the property
`com.hazelcast.map.impl.eviction.ExpirationManager.PERIOD` is hard-coded
to 5 seconds. Making it a configurable property will help in tuning the
eviction. https://github.com/hazelcast/hazelcast/issues/8277[#8277]
* The method `com.hazelcast.topic.impl.TopicProxy#publish` serializes
the message even if the message is never sent due to having no
subscribers. In the case of non-global-ordering and non-client use, the
implementation should defer serialization until it has established that
there are subscribers. https://github.com/hazelcast/hazelcast/issues/8262[#8262]
* Hazelcast should provide an abstract Mapper implementation which
invokes the Supplier given to `Aggregation#getMapper()`. https://github.com/hazelcast/hazelcast/issues/7477[#7477]
* Configuration setting for WAN replication queue should be only for
primary entries. https://github.com/hazelcast/hazelcast/issues/7124[#7124]
* Currently if you want to use Container-Managed Transactions with
Hazelcast within a JEE Application Server, you need to use the provided
JCA Adapter. This JCA Adapter creates a Hazelcast instance. This should
be allowed: configuration of the JCA Adapter to be either Server or
Client-based. https://github.com/hazelcast/hazelcast/issues/5667[#5667]
* Currently `PartitionIteratingOperation` consumes a generic operation
thread, while the operations for the partitions are running. This means
that the generic thread pool can dry out and this can cause a lot of
problems for important tasks that cannot be executed since the thread
pool is empty. A `PartitionIteratingService` should be introduced where
the system can lookup TraceableOperations. https://github.com/hazelcast/hazelcast/issues/4889[#4889]
* Hazelcast Shutdown Hook calls the method `terminate()` instead of
`shutdown()`. https://github.com/hazelcast/hazelcast/issues/46468[#4648]
* Hazelcast should support `ScheduledExecutorService`. https://github.com/hazelcast/hazelcast/issues/115[#115]

[[fixes-38]]
=== Fixes

The following are the issues solved for Hazelcast 3.8 release.

* `TaskDefinition` should be removed from the client protocol. https://github.com/hazelcast/hazelcast/issues/9846[#9846]
* `AggregationResult` should be serialized via Codec instead of IDS.
https://github.com/hazelcast/hazelcast/issues/9845[#9845]
* `MetaDataResponse` should be serialized via Codec instead of IDS.
https://github.com/hazelcast/hazelcast/issues/9844[#9844]
* The script `stop.bat` does not stop the running Hazelcast instances.
https://github.com/hazelcast/hazelcast/issues/9822[#9822]
* The script `start.bat` allows multiple instances to be started in the
same folder; it should not. https://github.com/hazelcast/hazelcast/issues/9820[#9820]
* Ordering consistency for the the method `writePortable` should be
explained in the Reference Manual. https://github.com/hazelcast/hazelcast/issues/9813[#9813]
* A client cannot add index to map using Portable values without
registering Portable classes on member. https://github.com/hazelcast/hazelcast/issues/9808[#9808]
* Index is not updated after entry processors change values. https://github.com/hazelcast/hazelcast/issues/9801[#9801]
* When using Entry Processor and index on a field the Entry Processor
uses, wrong data is returned when executing a Predicate. https://github.com/hazelcast/hazelcast/issues/9798[#9798]
* `NullPointerException` in `LockServiceImpl`: an NPE is thrown in
`LockServiceImpl` when creating one map with a quorum configuration
(which activates the `QuorumServiceImpl` for all `QuorumAware`
operations) and then calling a `QuorumAware` operation on another data
structure without a quorum configuration. https://github.com/hazelcast/hazelcast/issues/9792[#9792]
* `ClusterVersion` is missing convenience methods for comparing easily.
https://github.com/hazelcast/hazelcast/issues/9789[#9789]
* When scheduling tasks with multiple executors, calling
`getAllScheduled` on one of them returns tasks scheduled per member but
for all executors, rather than for the one we called the
`getAllScheduled` from. https://github.com/hazelcast/hazelcast/issues/9784[#9784]
* There are too many log entries when quorum is not present. https://github.com/hazelcast/hazelcast/issues/9781[#9781]
* Hazelcast terminates listener incorrectly. https://github.com/hazelcast/hazelcast/issues/9766[#9766]
* When `storeAll`/`deleteAll` methods are used in the MapStore
interface, it is possible that the underlying implementation has
stored/deleted some entries from the supplied batch and then gets an
exception on some particular entry in the middle of the batch. In order
to handle this scenario properly the MapStore could remove from the
supplied batch entries which were properly stored in the underlying
persistent store. The only thing to improve in the
`DefaultWiteBehindProcessor` is to properly synchronize the map passed
to `processBatch` method with the initial `batchMap`. https://github.com/hazelcast/hazelcast/issues/9733[#9733]
* If `hazelcast.discovery.enabled` on the client side: If neither
`DiscoveryServiceProvider` nor `DiscoveryStrategyConfig` is specified,
an NPE is thrown. A more helpful exception should be provided. https://github.com/hazelcast/hazelcast/issues/9722[#9722]
* The `hazelcast-all.jar`, which is the one included in Hazelcast
Docker, downloaded from Maven repo, contains an outdated version of
`hazelcast-aws` library. https://github.com/hazelcast/hazelcast/issues/9698[#9698]
* When scheduling on random partitions and trying to get all the
scheduled tasks from the service, the number of tasks is wrong. The
returned figure seems to match `num_of_tasks * backup_count`. https://github.com/hazelcast/hazelcast/issues/9694[#9694]
* When a scheduled Callable/Runnable throws an exception, invoking
`future.get()` on the client side does not throw the expected
`ExecutionException`. https://github.com/hazelcast/hazelcast/issues/9685[#9685]
* The client is not updating listener registrations when the member
restarts with a new version. https://github.com/hazelcast/hazelcast/issues/9677[#9677]
* `IScheduledExecutorService` does not use `HazelcastInstanceAware` on
local operations. https://github.com/hazelcast/hazelcast/issues/9675[#9675]
* Near cache compatibility with 3.7 clients is broken for TTL
expirations. https://github.com/hazelcast/hazelcast/issues/9674[#9674]
* Fix inconsistent Ringbuffer TTL defaults: when starting a
`HazelcastInstance` without an explicit configuration
(`HazelcastInstance hz = Hazelcast.newHazelcastInstance();`), the
default Ringbuffer TTL was 30 seconds, instead of correct value 0. This
change may break existing applications relying on the default
configuration. https://github.com/hazelcast/hazelcast/issues/9610[#9610]
* Replicated Map configured with `async-fillup` as `false` prevents
further members from joining the cluster. Members are stuck in an
endless loop. https://github.com/hazelcast/hazelcast/issues/9592[#9592]
* When an exception is thrown from an `InitializingObject`’s initialize
method, it is logged in WARNING level but then swallowed and the proxy
object is added to the `ProxyRegistry`. Instead, the exception should
result in removing the object from the `ProxyRegistry`, as it is already
done for exceptions thrown from `service.createDistributedObject`.
https://github.com/hazelcast/hazelcast/issues/9578[#9578]
* Near cache pre-loader fails when invalidations are enabled. https://github.com/hazelcast/hazelcast/issues/9536[#9536]
* There is a memory leak in `MetaDataGenerator` when (1) near cache
invalidations are enabled, (2) map/cache is created and destroyed, and
(3) the map name is stays referenced from `MetaDataGenerator`. https://github.com/hazelcast/hazelcast/issues/9495[#9495]
* JCache client needs access to `CacheLoader` implementation to work.
https://github.com/hazelcast/hazelcast/issues/9453[#9453]
* The matching wildcard is strict, but no declaration can be found for
element `hz:hazelcast`. https://github.com/hazelcast/hazelcast/issues/9406[#9406]
* `Connection Reset` warning shows up in the class `CloudyUtility`.
https://github.com/hazelcast/hazelcast/issues/9404[#9404]
* Key state marking in near cached `getAll` should be improved. Instead
of key based marking, partition based approach can be used. https://github.com/hazelcast/hazelcast/issues/9403[#9403]
* Scheduled executor service tests are too slow. https://github.com/hazelcast/hazelcast/issues/9386[#9386]
* The method `getAll` is not updating the `localMapStats`. https://github.com/hazelcast/hazelcast/issues/9373[#9373]
* Hazelcast 3.7.3 and Spring Boot 1.4.2 get the error
`PortableFactory[-22] is already registered`. https://github.com/hazelcast/hazelcast/issues/9353[#9353]
* There is an issue when integrating with WebLogic 12c. Classloading
logging should be added when `DefaultNodeExtension` is loaded by
multiple classloaders. https://github.com/hazelcast/hazelcast/issues/9291[#9291]
* The method `MapLoader.loadAll(true)` does not reload after reloading
with new keys. https://github.com/hazelcast/hazelcast/issues/9255[#9255]
* Problems with timeout in blocking calls. https://github.com/hazelcast/hazelcast/issues/9250[#9250]
* Stale reads from Map inside a transaction should be guaranteed, when
Near Cache and delayed MapStore are enabled. https://github.com/hazelcast/hazelcast/issues/9248[#9248]
* Client protocol cannot handle ``null``s in the collection. https://github.com/hazelcast/hazelcast/issues/9240[#9240]
* `LifecycleState` events are not received when Hazelcast docker image
is used. https://github.com/hazelcast/hazelcast/issues/9189[#9189]
* If there is no network, multicast socket exception is thrown. https://github.com/hazelcast/hazelcast/issues/9081[#9081]
* Hazelcast is not handling XML configuration attribute for
`DurableExecutorService`. https://github.com/hazelcast/hazelcast/issues/9078[#9078]
* If `DurableExecutorService.retrieveResult(long)` is run from a client
for a task that does not exist, two exceptions appear at the client
side. At the member side, it logs `StaleTaskIdException`. This should
not be logged to the member if re-thrown to the client. https://github.com/hazelcast/hazelcast/issues/9051[#9051]
* When retrieving data from Java Hazelcast instance,
`HazelcastSerializationException` is thrown from the .NET client. https://github.com/hazelcast/hazelcast/issues/8985[#8985]
* Callback for time to live (for map eviction) is invoked with a
significant delay. https://github.com/hazelcast/hazelcast/issues/8894[#8894]
* `Warning 2` in `IMap::tryRemove` method’s code comments is not
correct. This method returns only a boolean. https://github.com/hazelcast/hazelcast/issues/8884[#8884]
* There are too many log messages when members of a cluster are not
joined to another cluster (multicast) having a different group name in
Hazelcast 3.6 and 3.7, which is already expected. https://github.com/hazelcast/hazelcast/issues/8867[#8867]
* When clients lose connection to the members in the cluster, even after
the clients are reconnected to the cluster, the Entry/Message Listeners
are never fired again. https://github.com/hazelcast/hazelcast/issues/8847[#8847]
* Nested queries on `VersionedPortables` with different versions cannot
be performed. Hazelcast throws IllegalArgumentException. https://github.com/hazelcast/hazelcast/issues/8846[#8846]
* Fixed `max-size` value behavior for Near Cache configuration. If you
set 0 for the `max-size`, now, it is valued as `Integer.MAX_VALUE` as
expected and documented. https://github.com/hazelcast/hazelcast/issues/8826[#8826]
* While generating the XML string from a configuration object in
`ConfigXmlGenerator.generate()` method, `native-memory` configuration is
not appended to the result string. This causes the `native-memory`
configuration for members not to be shown on the Management Center.
https://github.com/hazelcast/hazelcast/issues/8825[#8825]
* `Client heartbeat is timed out, closing connection` warning shows
up indefinitely on AWS. https://github.com/hazelcast/hazelcast/issues/8777[#8777]
* Spring XML configuration: The smart routing attribute defaults to
false while the documentation says it defaults to true. https://github.com/hazelcast/hazelcast/issues/8746[#8746]
* Distributed objects present in the cluster do not show the same
values. https://github.com/hazelcast/hazelcast/issues/8743[#8743]
* In Hazelcast 3.6.3, the error
`Current thread is not owner of the lock` shows up when using Hazelcast
client to perform the actions. https://github.com/hazelcast/hazelcast/issues/8730[#8730]
* There is an unchecked `CancelledKeyException` when client disconnects
from the cluster. https://github.com/hazelcast/hazelcast/issues/8681[#8681]
* Bulk `get` operation with 100 keys fails. https://github.com/hazelcast/hazelcast/issues/8535[#8535]
* An `IllegalThreadStateException` may be thrown sometimes on a member
of a cluster with two or more members when a Hazelcast client creates a
new map with configured indexes. This exception is not thrown when
indexes are created programmatically. https://github.com/hazelcast/hazelcast/issues/8492[#8492]
* Group and password attributes in Hibernate integration module should
be validated. https://github.com/hazelcast/hazelcast/issues/7978[#7978]
* There appears to be an inconsistency where JCache uses the
`EvictionConfig` object, but IMap directly uses properties of the
`NearCacheConfig`. https://github.com/hazelcast/hazelcast/issues/7788[#7788]
* Topic listeners are lost after merging from a split-brain scenario.
https://github.com/hazelcast/hazelcast/issues/7742[#7742]
* Member attributes go missing after merging from a split-brain
scenario. https://github.com/hazelcast/hazelcast/issues/7697[#7697]
* There should be a distributed class loading feature to perform
distributed loading of classes so that jobs like MapReduce and Aggregate
can be done more effectively. https://github.com/hazelcast/hazelcast/issues/7394[#7394]
* MapLoader misses state updates on second load on the receiver members.
https://github.com/hazelcast/hazelcast/issues/7364[#7364]
* If the system retries an operation because a member is leaving the
cluster, the invocation can be retried due to the response but also due
to the `member-left` event. In most cases this should not lead to a
problem, but the invocation may be executed twice. This can be a problem
and can lead to a permanent inconsistent system. https://github.com/hazelcast/hazelcast/issues/7270[#7270]
* Using Lock and Map, the heap memory on Hazelcast server keeps
increasing. All the created Locks and Maps are destroyed by the method
`destroy()`, but the memory cannot be destroyed by the garbage collector
even via FGC. When an application runs for some time, Hazelcast server
goes down. https://github.com/hazelcast/hazelcast/issues/7246[#7246]
* Hazelcast 3.5 throws `InvalidConfigurationException`. https://github.com/hazelcast/hazelcast/issues/6523[#6523]
* More granular mutexes should be used when creating and removing a set
of closeable cache resources. https://github.com/hazelcast/hazelcast/issues/6273[#6273]
* Running `PredicateBuilder` queries when nodes join causes timeouts and
cluster crash. https://github.com/hazelcast/hazelcast/issues/6242[#6242]
* The method `setEvictionPolicy` for near cache configuration wants a
string argument whereas the same for map configuration wants an enum
value. https://github.com/hazelcast/hazelcast/issues/2010[#2010]
* The configuration schemas Hazelcast Spring XSD and Hazelcast default
configuration XSD are out of sync. They must have the same elements.
https://github.com/hazelcast/hazelcast/issues/5034[#5034]

[[bc-38]]
=== Behavioral Changes

* A separate thread pool for query requests coming from the clients has
been introduced. The goal for this is to avoid `OutOfMemoryException` s
under heavy query load. This separate thread pool’s size is configurable
via the system property `hazelcast.clientengine.query.thread.count`.

[[rd-38]]
=== Removed/Deprecated Features

* Aggregators feature is deprecated. Instead, Fast-Aggregations feature
should be used.
* MapReduce feature is deprecated. See the
http://docs.hazelcast.org/docs/3.8/manual/html-single/index.html#mapreduce-deprecation[MapReduce
Deprecation section].
