
== 3.9

[[features-39]]
=== New Features

*_Hazelcast IMDG Enterprise Features:_*

* *WAN Replication Using Discovery API*: With this new feature, you can
run multiple clusters within environments, that have Hazelcast’s
Discovery SPI implemented, without manually configuring IP addresses and
use Hazelcast’s WAN replication to keep them in sync. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#defining-wan-replication-using-discovery-spi[Defining
WAN Replication Using Discovery SPI section].

*_Hazelcast IMDG Open Source Features:_*

* *Dynamic Creation of Distributed Objects Configuration*: You can
perform on the fly configuration of your distributed objects. See
the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#dynamically-adding-configuration-on-a-cluster[Dynamically
Adding Configuration on a Cluster section].

[[enhancements-39]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* *OpenSSL Integration*: OpenSSL is integrated into Hazelcast. Please
see the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#integrating-openssl[Integrating
OpenSSL section].

*_Hazelcast IMDG Open Source Enhancements:_*

* *Client Support for User Code Deployment*: You can now perform dynamic
class loading from Hazelcast clients too. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#client-user-code-deployment-beta[Client
User Code Deployment section].
* *Event Journal*: This new distributed data structure stores the
history of mutation actions on data structures such as map or cache.
See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#event-journal[Event
Journal section].
* *Fine-Grained Anti-Entropy Mechanism*: Allows to detect
inconsistencies for each data structure in a single partition and
replicate only the specific fragment of it instead of the whole
partition. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#consistency-and-replication-model[Consistency
and Replication Model chapter].
* *Gigantic Cache Migration Enhancements*: It enables manual control on
the partition migrations. Partitions can be migrated/replicated in small
fragments. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#system-properties[hazelcast.partition.migration.fragments.enabled]
system property and
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#managing-cluster-and-member-states[NO_MIGRATION]
cluster state.
* *Storing Near Cache Keys by Reference*: This enhancement provides a
functionality to skip the serialization of keys for Near Caches to
improve the performance of the Near Caches. See the
`serialize-keys` option in the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#configuring-near-cache[Near
Cache section].
* *Client Connection Strategy Enhancements*: Allows lazy initiation for
Hazelcast Clients. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#client-connection-strategy[Configuring
Client Connection Strategy section].
* *Default Group Password and Symmetric Encryption Default Credentials
Policy*: Hazelcast requires the default group password and default
symmetric encryption password/salt to be changed. See the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#validating-secrets-using-strength-policy[Validating
Secrets Using Strength Policy section].
* *Hazelcast Consistency Model Documentation*: We added a new chapter
explaining the full picture of Hazelcast’s consistency model. See
the
http://docs.hazelcast.org/docs/3.9/manual/html-single/index.html#consistency-and-replication-model[Consistency
and Replication Model chapter].
* *Keeping JCache Implementation Updated*: Hazelcast JCache
implementation is updated for JSR 1.1 compliance when it is released.

The following are the other improvements performed to solve the
enhancement issues opened by the Hazelcast customers/team.

* Support for `properties` in `RingbufferStoreConfig` must be added.
https://github.com/hazelcast/hazelcast/issues/11077[#11077]
* There should be the ability to add a timeout to get operations for
Spring `HazelcastCache`.
https://github.com/hazelcast/hazelcast/issues/10756[#10756]
* Exception causes get lost when using `IExecutorService` with the
Hazelcast client.
https://github.com/hazelcast/hazelcast/issues/10591[#10591]
* The attribute `override-java-serialization` should be added to the
element `global-serializer` in `hazelcast-client-config.xsd`. https://github.com/hazelcast/hazelcast/issues/10449[#10449]
* Hazelcast should have a method like `gerOrCreateHazelcastInstance()`
to detect a default configuration file and either create an instance or
get an existing one. https://github.com/hazelcast/hazelcast/issues/10007[#10007]
* Allow binding any port without using the method
`setPortAutoIncrement()` and specifying the port count. https://github.com/hazelcast/hazelcast/issues/9775[#9775]
* Consistent interface for IMap and TransactionalMap is needed. https://github.com/hazelcast/hazelcast/issues/8729[#8729]
* Hazelcast instance’s name should be added as a prefix to the name of
the threads managed by Hazelcast. https://github.com/hazelcast/hazelcast/issues/8542[#8542]
* When back pressure is enabled members always use back-off and clients
always throws `HazelcastOverloadedException`. This is not consistent and
the behavior should be configurable on both members and clients. https://github.com/hazelcast/hazelcast/issues/8533[#8533]
* There should be a Spring property placeholder for
`cache-deserialized-values` in the map configuration.
https://github.com/hazelcast/hazelcast/issues/8487[#8487]
* For `OperationService`, the contention on the counters should be
reduced. https://github.com/hazelcast/hazelcast/issues/4925[#4925]
* Some of the properties mentioned in `GroupProperties` are not used
anymore, it should be cleaned up. https://github.com/hazelcast/hazelcast/issues/4505[#4505]
* When a grid member is configured to use port 0, it should be handled
properly. https://github.com/hazelcast/hazelcast/issues/2506[#2506]
* There should be the ability to configure the distributed objects on
the fly. https://github.com/hazelcast/hazelcast/issues/592[#592]

[[fixes-39]]
=== Fixes

* Members cannot join to 3.9 cluster when using cache with a key/value
type that is only resolvable from the user code deployment repository.
https://github.com/hazelcast/hazelcast/issues/11505[#11505]
* Hazelcast listeners may fail to be registered to a new joined member.
This is caused by a race condition between `PostJoinOperations` and the
member doing the listener registration.
https://github.com/hazelcast/hazelcast/issues/11490[#11490]
* Regression occurs after returning `ResultSet` instead of
`SortedQueryResultSet`.
https://github.com/hazelcast/hazelcast/issues/11489[#11489]
* Performance issue in `MapProxyImpl.readFromEventJournal` with
projection. Projection cloning on the method `readFromEventJournal` must
be skipped.
https://github.com/hazelcast/hazelcast/issues/11410[#11410]
* There is an issue with `MapStore`: the method
`hcInstance.getMap(mapName)` gets blocked when a new member joins and
data is being loaded.
https://github.com/hazelcast/hazelcast/issues/11407[#11407]
* Migration operation during the member startup raises `ERROR` level
exception. https://github.com/hazelcast/hazelcast/issues/11406[#11406]
* `SpringAware` and `NodeAware` are not taken into account when
injecting dependencies to various cache resources.
https://github.com/hazelcast/hazelcast/issues/11406[#11406]
* When the method `execute()` from `OperationServiceImpl` is used and if
it times out, the operation cannot send a response since
`responseHandler` is null (assuming the caller did not set it
initially). This leads to `NullPointerException`.
https://github.com/hazelcast/hazelcast/issues/11375[#11375]
* In the method `DataRecordComparator.isEqual()`, the objects are always
serialized so that the binary form is used to determine if something
equals another object. This can lead to a lot of unwanted
serializations.
https://github.com/hazelcast/hazelcast/issues/11290[#11290]
* There is an inconsistent behavior for the method `exists()` of
`CacheEntryProcessorEntry`.
https://github.com/hazelcast/hazelcast/issues/11266[#11266]
* Hazelcast 3.8.4 source code does not match the JAR classes.
https://github.com/hazelcast/hazelcast/issues/11261[#11261]
* `OperationTimeoutException` should include the cause of exception.
https://github.com/hazelcast/hazelcast/issues/11233[#11233]
* There is no way to configure the `port-count` element within Spring
context. https://github.com/hazelcast/hazelcast/issues/11224[#11224]
* Registration objects cause a memory leak while using
`ScheduledExecutor`.
https://github.com/hazelcast/hazelcast/issues/11221[#11221]
* Incorrect `UnsupportedOperationException` message: `Event journal
actions are not available when cluster version is 3.9 or higher`. It
should be `.. are available ..`.
https://github.com/hazelcast/hazelcast/issues/11220[#11220]
* `loadClasses` of client user code deployment throws
`ClassNotFoundException`.
https://github.com/hazelcast/hazelcast/issues/11217[#11217]
* Dead cluster member causes a high reconnect count.
https://github.com/hazelcast/hazelcast/issues/11176[#11176]
* `MapGetInvalidationMetaDataOperation` throws `NullPointerException` in
a Near Cache scenario.
https://github.com/hazelcast/hazelcast/issues/11147[#11147]
* REST endpoints for cluster version management should be documented.
https://github.com/hazelcast/hazelcast/issues/11139[#11139]
* `CacheDestroyOperation` must be invoked on the generic operation
thread. https://github.com/hazelcast/hazelcast/issues/11137[#11137]
* Hazelcast members keep leaving and rejoining from/to the cluster in
Docker (via the plugin Hazelcast AWS).
https://github.com/hazelcast/hazelcast/issues/11118[#11118]
* The method `ICache.getAndRemove()` doesn’t invalidate the Near Cache.
https://github.com/hazelcast/hazelcast/issues/11110[#11110]
* `IScheduledExecutorService` with `@SpringAware` does not inject
ApplicationContext or Beans.
https://github.com/hazelcast/hazelcast/issues/11108[#11108]
* IMap allows passing null collection in `putAll` and `getAll`, and null
keys in `loadAll`.
https://github.com/hazelcast/hazelcast/issues/11099[#11099]
* MapLoader `NullPointerException` occurs on `loadAll(Collection)` when
the value is null and MapLoader implements `PostProcessingMapStore` or
has an Interceptor.
https://github.com/hazelcast/hazelcast/issues/11081[#11081]
* `CacheNotExistsException` is thrown when a new member joins a
cluster where the primary member is creating and destroying JCaches.
https://github.com/hazelcast/hazelcast/issues/11047[#11047]
* `NullPointerException` on `ScheduledExecutor` when handling multiple
migration requests on the same source should be fixed.
https://github.com/hazelcast/hazelcast/issues/11046[#11046]
* The exception
`NoClassDefFoundError: com/hazelcast/com/eclipsesource/json/JsonObject`
is thrown when using Payara Server and Hazelcast-AWS.
https://github.com/hazelcast/hazelcast/issues/10994[#10994]
* There should be a warning or an information message when
`DiscoveryStrategy` SPI is not on the classpath.
https://github.com/hazelcast/hazelcast/issues/10993[#10993]
* There is a rolling upgrade compatibility issue for native queries in
Hazelcast 3.9. It will fail when a 3.8 member send a `QueryOperation` to
3.9. https://github.com/hazelcast/hazelcast/issues/10973[#10973]
* SSL Incorrect Error Message: Memcached not enabled. Connecting to a
Hazelcast Cluster that has SSL/Security disabled with a Hazelcast Client
that has SSL enabled gives this error.
https://github.com/hazelcast/hazelcast/issues/10971[#10971]
* Statistics `getTotalGetLatency`, `getTotalRemoveLatency`, and
`getTotalPutLatency` works incorrectly.
https://github.com/hazelcast/hazelcast/issues/10938[#10938]
* Map destroy doesn’t remove invalidation sequences and this causes
`OutOfMemoryException`.
https://github.com/hazelcast/hazelcast/issues/10936[#10936]
* Ensure dynamic configuration is available before `HazelcastInstance`
is returned to user.
https://github.com/hazelcast/hazelcast/issues/10926[#10926]
* Illegal character exception is thrown at index for the character
''^''. https://github.com/hazelcast/hazelcast/issues/10921[#10921]
* The method `ScheduledTaskHandler.of(urn)` fails when IPv6 address is
used. https://github.com/hazelcast/hazelcast/issues/10898[#10898]
* There is a thread leak after calling the method
`HazelcastInstance.shutdown()` in 3.8.2; so, JVM won’t exit.
https://github.com/hazelcast/hazelcast/issues/10886[#10886]
* Transactional Queue: Backup reserve is failed, itemId: is not found.
https://github.com/hazelcast/hazelcast/issues/10867[#10867]
* Map configurations inconsistency between members.
https://github.com/hazelcast/hazelcast/issues/10860[#10860]
* `PostJoinMapOperation` is running on a generic thread; it means it
cannot create high-density memory store indexes. It should probably
spawn partition specific operations.
https://github.com/hazelcast/hazelcast/issues/10841[#10841]
* The element `config-permission` cannot be configured in Hazelcast
Spring XML.
https://github.com/hazelcast/hazelcast/issues/10835[#10835]
* `DynamicSecurityConfig` and `SecurityService` lifecycle should be
clarified. https://github.com/hazelcast/hazelcast/issues/10834[#10834]
* Eliminate synchronization when checking task permissions.
https://github.com/hazelcast/hazelcast/issues/10833[#10833]
* Dynamic configuration tasks should be non-blocking.
https://github.com/hazelcast/hazelcast/issues/10813[#10813]
* Hazelcast declares `commons-logging` (OSGi) as a required dependency,
but it is not required.
https://github.com/hazelcast/hazelcast/issues/10770[#10770]
* Comparing `Version.UNKNOWN` with other versions results in strange
results. https://github.com/hazelcast/hazelcast/issues/10755[#10755]
* Multiple threads from Spring boot application are able to acquire lock
on the same document id ( String ).
https://github.com/hazelcast/hazelcast/issues/10754[#10754]
* The system property
`hazelcast.cache.invalidation.batchfrequency.seconds` does not work for
IMap. https://github.com/hazelcast/hazelcast/issues/10743[#10743]
* The method `isEnterprise()` for `BuildInfoProvider` does not work in
Hazelcast 3.7.x.
https://github.com/hazelcast/hazelcast/issues/10740[#10740]
* Infinite loop trying to initialize Cache configuration when
deserialization fails.
https://github.com/hazelcast/hazelcast/issues/10728[#10728]
* There is a race between `CacheConfig` addition and Proxy creation when
a new member joins cluster.
https://github.com/hazelcast/hazelcast/issues/10727[#10727]
* There is an infinite loop trying to initialize cache configuration
when deserialization fails.
https://github.com/hazelcast/hazelcast/issues/10723[#10723]
* Fail fast should occur when the cache’s in-memory format is
incompatible with its eviction configuration.
https://github.com/hazelcast/hazelcast/issues/10716[#10716]
* When a Java application is run with Hazelcast 3.8.2 within Docker, and
after switching from `openjdk:8u121-jre-alpine` to
`openjdk:8u131-jre-alpine`, `IllegalArgumentException` is thrown during
cluster bootstrap. https://github.com/hazelcast/hazelcast/issues/10704[#10704]
* Performance Issue in Hazelcast 3.8.1: `QueueStore.loadAll()` is called
way too often when draining items from Queue. https://github.com/hazelcast/hazelcast/issues/10621[#10621]
* Hazelcast instance is not injected into predicate. It occurs when the
predicate is not serialized and deserialized because it was invoked on
the partition owner.
https://github.com/hazelcast/hazelcast/issues/10620[#10620].
* Hazelcast client always tries to connect to localhost when using
`DiscoveryStrategy`.
https://github.com/hazelcast/hazelcast/issues/10606[#10606]
* Scheduled task remains cancelled after migration. https://github.com/hazelcast/hazelcast/issues/10603[#10603]
* `SplitBrainMergeValidationOperation` ignores the join check from
[NODEB]:5701, because that node is not master.
https://github.com/hazelcast/hazelcast/issues/10587[#10587]
* Problem setting up a cluster into Docker Swarm (overlay network).
[#10477]
* New cache eviction is populated among nodes very slowly. https://github.com/hazelcast/hazelcast/issues/10470[#10470]
* WAN backup events are published twice. The
`publishWanReplicationEventBackups` method is called in the `run` and
`afterRun` method in the `PartitionWideEntryBackupOperation`. Elsewhere
it is only called in `afterRun`. This needs to be checked but possibly
the fix is just to remove the call in `run`. https://github.com/hazelcast/hazelcast/issues/10457[#10457]
* `PortableFactory[-22] is already registered` error when using Spring
Boot 1.4.2 and Hazelcast 3.7.x.
https://github.com/hazelcast/hazelcast/issues/10438[#10438]
* Source parameter is null on `JCache.loadAll()` call. https://github.com/hazelcast/hazelcast/issues/10328[#10328]
* `TransactionalMapProxy` depends on `MapContainer`. Also, creating a
`TransactionalMapProxy` should not trigger creation of the backing
`MapContainer`.
https://github.com/hazelcast/hazelcast/issues/10254[#10254]
* It is impossible to stop a Hazelcast Client service if it has never
connected to the server.
https://github.com/hazelcast/hazelcast/issues/10237[#10237]
* `TcpIpJoiner` throws the
exception`ConcurrentModificationException: null`. https://github.com/hazelcast/hazelcast/issues/10207[#10207]
* `Cache.cacheManager` may be overwritten with a different
`CacheManager`.
https://github.com/hazelcast/hazelcast/issues/10200[#10200]
* It seems like the Near Cache statistics seem to be off-by-one for at
least the `ownedEntryCount`. Sometimes the `ownedEntryMemoryCost` seems
to be affected as well. https://github.com/hazelcast/hazelcast/issues/10193[#10193]
* `PagingPredicate` does not work for the method `executeOnEntries()`.
https://github.com/hazelcast/hazelcast/issues/10174[#10174]
* Setting up a Hazelcast listener in a Spring configuration format does
not seem to work when using the class property of `hz:listener`.
https://github.com/hazelcast/hazelcast/issues/10154[#10154]
* Test coverage for `NearCacheClientCacheProxy` should be increased.
https://github.com/hazelcast/hazelcast/issues/10127[#10127]
* Fast Aggregations for `any` operator on empty arrays do not work.
https://github.com/hazelcast/hazelcast/issues/10126[#10126]
* `CachingProvider` should attempt to get or create `HazelcastInstance`
with the default configuration when only instance name is provided.
https://github.com/hazelcast/hazelcast/issues/10094[#10094]
* `MulticastDiscoveryStrategy` does not work correctly with client
discovery. https://github.com/hazelcast/hazelcast/issues/10089[#10089]
* Updates with `IMap#putTransient` should trigger
`EntryUpdatedListener`.
https://github.com/hazelcast/hazelcast/issues/10077[#10077]
* The method `loadAll(boolean replaceExistingValues)` does not reload
the map store after the method `cache.evictAll` is called.
https://github.com/hazelcast/hazelcast/issues/10057[#10057]
* Hazelcast XML configuration does not allow `RANDOM` eviction as an
eviction policy. https://github.com/hazelcast/hazelcast/issues/10053[#10053]
* There is a race condition in `TestClientRegistry` where the tests are
calling `blockFrom` and `blockTo` before any connection was made (via
`createSocketConnection`). This causes `NullPointerException` in those
block methods. https://github.com/hazelcast/hazelcast/issues/10021[#10021]
* Client side query cache declarative configuration does not support
wildcard usage `mapName` configuration.
https://github.com/hazelcast/hazelcast/issues/9990[#9990]
* When health check is enabled, the user can send a garbage request like
`\http://<your member's host IP>:5701/hazelcast/healthqqq` and it returns
a correct response. https://github.com/hazelcast/hazelcast/issues/9967[#9967]
* Durable Executor Service re-executes the completed tasks in case of a
member failure. https://github.com/hazelcast/hazelcast/issues/9965[#9965]
* There is a problem with virtual IP assignments when Hazelcast is used
into a Docker Swarm cluster.
https://github.com/hazelcast/hazelcast/issues/9963[#9963]
* Currently there is no Spring support for Near Cache preloader.
https://github.com/hazelcast/hazelcast/issues/9771[#9771]
* MapStore: write delay is not precisely respected as it has been in the
previous Hazelcast releases (before 3.7.4).
https://github.com/hazelcast/hazelcast/issues/9745[#9745]
* The option `cache-local-entries` is not supported at the client side
Near Cache configuration. https://github.com/hazelcast/hazelcast/issues/9712[#9712]
* Latest member-list may not be received when `FinalizeJoinOperation`
invocation timeouts. https://github.com/hazelcast/hazelcast/issues/9501[#9501]
* Cluster member-list update operations are not ordered, new member
addition and removal operations can get reordered on
receiving/processing side. Also periodic member-list publish operation
has no order with other member adding/removing operations. That can
cause having different member lists on different members. [#9486]
* Hazelcast Client API (3.7.3) is not able to execute get/put/delete
operations on the maps when used in AWS with smart-routing enabled
(values and clear operation work).
https://github.com/hazelcast/hazelcast/issues/9419[#9419]
* Single map with ten items and three members, Split-Brain case: After
isolating one member, the merge occurs only with some of the keys, not
all of them. https://github.com/hazelcast/hazelcast/issues/9358[#9358]
* When attempting to start a cluster member (3.6.5) with JMX enabled,
`IllegalArgumentException` is thrown and the member is self-terminated
immediately. https://github.com/hazelcast/hazelcast/issues/9293[#9293]
* Backup is lost if `maxIdle` property is used. https://github.com/hazelcast/hazelcast/issues/9153[#9153]
* MultiMap lock: Thread is getting stuck when calling `lock(key)`.
https://github.com/hazelcast/hazelcast/issues/9055[#9055]
* Near Cache on the Hazelcast Client side returns old values.
https://github.com/hazelcast/hazelcast/issues/8838[#8838]
* Behavior of TTL when it is a negative value should be clarified.
https://github.com/hazelcast/hazelcast/issues/7729[#7729]
* Heartbeat only removes a member if it is related to the master member.
https://github.com/hazelcast/hazelcast/issues/5253[#5253]
* Multicast discovery does not work after loading some data.
https://github.com/hazelcast/hazelcast/issues/4721[#4721]

[[bc-39]]
=== Behavioral Changes

* Maximum timeout of heartbeat for a member to assume it is dead was 300
seconds. Starting with Hazelcast 3.9, it is reduced to 60 seconds.
Related property is `hazelcast.max.no.heartbeat.seconds`. Also, starting
with Hazelcast 3.9, maximum timeout of master confirmation from other
members is reduced to 150 seconds from 450 seconds. Related property is
`hazelcast.max.no.master.confirmation.seconds`.
* Starting with Hazelcast 3.9, the default `Cache` merge policy is *Put
if Absent*. It was *Pass Through* before Hazelcast 3.9.
* Starting with Hazelcast 3.9, the format of member list shown in the
logs is changed. Before Hazelcast 3.9, it was like the following:
+
....
Members [3] {
    Member [127.0.0.1]:5701 - c1ccc8d4-a549-4bff-bf46-9213e14a9fd2 this
    Member [127.0.0.1]:5702 - 33a82dbf-85d6-4780-b9cf-e47d42fb89d4
    Member [127.0.0.1]:5703 - 813ec82f-9d9e-4712-bae1-6c95b32d6d7d
}
....
+
Starting with Hazelcast 3.9, it is shown as follows:
+
....
Members {size:3, ver:3} [
  Member [127.0.0.1]:5701 - e40081de-056a-4ae5-8ffe-632caf8a6cf1 this
  Member [127.0.0.1]:5702 - 93e82109-16bf-4b16-9c87-f4a6d0873080
  Member [127.0.0.1]:5703 - 06fb4e61-9757-443b-a19f-7af1f3966f30
]
....
+
Here, you can see the size of your cluster (`size`) and member list
version (`ver`). The member list version will be incremented when
changes happen to the cluster, e.g., a member leaving from or joining to
the cluster.
+
You can set the system property
`hazelcast.legacy.memberlist.format.enabled` to `true` if you want to
see the member list in its old format.

[[contributors-39]]
===  Contributors

We would like to thank the contributors from our open source
community who worked on this release:

* https://github.com/gaganis[Giorgos Gaganis]
* https://github.com/dpwegener[dpwegener]

