

== 4.0

[[nf-40]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

*_Hazelcast IMDG Open Source New Features:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

[[enh-40]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

*_Hazelcast IMDG Open Source Enhancements:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Enhanced the queries (read-only operations) in the CP Subsystem so that
they are executed with linearizability but they are not appended to the Raft log.
By this way, the grow of Raft logs and snapshots of read-only operations are
prevented, leading to throughput improvement
https://github.com/hazelcast/hazelcast/pull/14986[#14986]
* Introduced `PartitionIdSet`. This is a mutable set of partition IDs
which can be efficiently represented by a fixed size leading to a
better performance.
https://github.com/hazelcast/hazelcast/pull/14925[#14925]
* Made `AssertTask` an interface to enable lambdas to be used in
assert-eventually methods.
https://github.com/hazelcast/hazelcast/pull/14923[#14923]
* Updated the Hazelcast Kubernetes dependency to version 1.5.
https://github.com/hazelcast/hazelcast/pull/14898[#14898]
* Updated the map package so that it uses the Java 8 features.
https://github.com/hazelcast/hazelcast/pull/14891[#14891]
* Cleaned up the Maven repositories in Hazelcast's `pom.xml`
to simplify the usage of Maven proxies.
https://github.com/hazelcast/hazelcast/pull/14850[#14850]
* Eliminated the excessive logging when NIO networking is shutdown by
deregistering the IO threads.
https://github.com/hazelcast/hazelcast/pull/14823[#14823]
* Updated the web session manager dependency to its latest
version.
https://github.com/hazelcast/hazelcast/pull/14822[#14822]
* Introduced a warning log for illegal reflective access operation when
using Java 9 and higher, and OpenJ 9.
https://github.com/hazelcast/hazelcast/pull/14798[#14798]
* Separated the statistic gathering for `IMap.set(K, V)` and
`IMap.put(K, V) operations`.
https://github.com/hazelcast/hazelcast/issues/14663[#14663]
* Improved the fluent interface of configuration classes by adding
the `return this` statements to the setter methods.
https://github.com/hazelcast/hazelcast/pull/11107[#11107]

[[bc-40]]
=== Breaking Changes

* Removed the `hazelcast.executionservice.taskscheduler.remove.oncancel`
system property and related methods.
https://github.com/hazelcast/hazelcast/pull/14998[#14998]
* Removed the `LegacyAsyncMap` interface.
https://github.com/hazelcast/hazelcast/pull/14994[#14994]
* Removed the support for primitives for `setAttribute` and `getAttribute` operations.
All member attributes support only string attributes now.
https://github.com/hazelcast/hazelcast/pull/14974[#14974]
* Changed the `application/javascript` "Content-Type" header used
by REST API to respond to the JSON documents. Now, it uses
`application/json`.
https://github.com/hazelcast/hazelcast/pull/14972[#14972]
* Changed the `non-space-string` XSD type to collapse all
whitespaces, so they are handled correctly in the declarative
Hazelcast IMDG configuration files.
https://github.com/hazelcast/hazelcast/issues/14919[#14919]
* Removed the `java.util.function` back ports.
https://github.com/hazelcast/hazelcast/pull/14912[#14912]


[[fixes-40]]
=== Fixes

* Fixed an issue where the client was not considering the new
address of a restarted member, which has the same UUID but could
have a different IP address after it is restarted.
https://github.com/hazelcast/hazelcast/pull/14842[#14842]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/14832[#14832]
* Fixed an issue where the outbound pipeline was not waking up
properly after various optimizations for write-through
persistence is made.
https://github.com/hazelcast/hazelcast/pull/14831[#14831]
* Fixed an issue caused by the cache being not ready to be used
immediately after the cache proxy was created.
https://github.com/hazelcast/hazelcast/pull/14821[#14821]
* Fixed a performance issue where there were unneeded iterations and
object creations while converting the client messages to user objects.
https://github.com/hazelcast/hazelcast/pull/13784[#13784]
* Fixed an issue where the locked entries with a time-to-live were not evicted.
With this fix, the lock operation checks if an entry has already expired.
https://github.com/hazelcast/hazelcast/issues/13272[#13272]
* Fixed a leak in the query cache due to `ListenerRegistrationHelper`, which
has been removed with this fix.
https://github.com/hazelcast/hazelcast/pull/11914[#11914]
* Fixed an issue where the `IMap.replace()` method was not loading entries
from the MapLoader when the keys could not be found in the memory.
https://github.com/hazelcast/hazelcast/issues/11300[#11300]

[[deprecated-40]]
=== Deprecated Features

* ???.
* The following system properties are deprecated:
** `???`
* The following Hazelcast IMDG interfaces are deprecated and replaced
with the ones provided by the Hazelcast IMDG CP Subsystem:
** `???`

[[removed-40]]
=== Removed Features

