

== 4.0

NOTE: See the https://docs.hazelcast.org/docs/4.0/manual/html-single/#upgrading-to-hazelcast-imdg-4-0[Hazelcast IMDG 4.0 Migration Guide]
for the detailed guidelines to be followed when upgrading Hazelcast IMDG to 4.0.

[[nf-40]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **X.509 Certificate Authentication:** Added support for credential retrieval by the members
from the X.509 certificates configured on the clients.
See the link:https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section^].
* **Intel(R) Optane(TM) DC Persistent Memory Integration:** Added support for
Intel Optane DC to the High-Density Memory Store.
See the link:https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section^]


*_Hazelcast IMDG Open Source New Features:_*

* **CP Subsystem Development Mode:** Introduced `UNSAFE` mode for the CP data
structures. This way, you do not need to have at least three IMDG members
to use CP subsystem: you can benefit from its functionalities using only one
or two members. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

[[enh-40]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **Separating WAN Publisher Configuration:** The previously known `wan-publisher` (or `WanPublisherConfig`) has been separated into two configuration elements to be used for built-in and custom WAN publishers:
** `batch-publisher`
** `custom-publisher`
+
See the link:https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#defining-wan-replication[Defining WAN Replication section^]
* **Improvements in the JAAS Authentication Mechanism:**
** Added support for the standard JAAS callbacks, i.e., `NameCallback` and `PasswordCallback`
** Secrets, if not necessary, are not stored now
** Cleaned up the `Credentials` and `ClusterPrincipal` object.
+
See the link:https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section^].


*_Hazelcast IMDG Open Source Enhancements:_*

* **HTTPS for scripts:**Enabled the REST endpoints for the `cluster.sh` and
`healthcheck.sh` scripts to use HTTPS. Before, they were
using HTTP. See the
link:https://docs.hazelcast.org/docs/4.0/manual/html-single/#using-the-script-cluster-sh[cluster.sh^] and
link:https://docs.hazelcast.org/docs/4.0/manual/html-single/#health-check-script[healtcheck.sh^] sections.
* **MapLoader with custom time-to-live:** Introduced the `EntryStore` and `EntryLoader`
interfaces (adding expiration support for MapStore). See the
https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#loading-and-storing-persistent-data[Loading and Storing Persistent Data section].
* **JCache 1.1.1:**Updated Hazelcast JCache implementation to support JCache 1.1.1.
This version of JCache does not introduce new functionalities;
it resolves the errata and issues in JCache 1.1.0.
See the https://docs.hazelcast.org/docs/4.0/manual/html-single/#jcache-111[Upgrading to JCache 1.1.1 section].
* **Moby naming:** Introduced friendly names for the Hazelcast instances to be shown
in the Hazelcast Management Center. See the link:https://docs.hazelcast.org/docs/4.0/manual/html-single/#checking-the-name-of-the-instance-for-rest-client[Checking the Instances' Name section^]. Also, a new system property, `hazelcast.member.naming.moby.enabled`, is introduced for this purpose.

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Improved the client protocol code generator so that it now
automatically generates the custom codecs.
https://github.com/hazelcast/hazelcast/pull/15630[#15630]
* Added the ``cachePartitionLostListenerConfig``s to `CacheConfig` serialization
and the client protocol encoding.
https://github.com/hazelcast/hazelcast/pull/15608[#15608]
* Set the log level to `FINEST` for `PartitionMigratingException`.
https://github.com/hazelcast/hazelcast/pull/15577[#15577]
* Added serialization compatibility tests for built-in objects
such as predicates, aggregators and projections.
https://github.com/hazelcast/hazelcast/pull/15511[#15511]
* Improved `DistinctValuesAggregator` and `MultiAttributeProjection` so that
they return objects compatible with non-Java clients.
https://github.com/hazelcast/hazelcast/pull/15506[#15506]
* Added the async version of the `IMap.putAll()` method, i.e., `IMap.putAllAsync()`.
In a member-to-member case, the put operations for members now are executed in parallel.
https://github.com/hazelcast/hazelcast/pull/15463[#15463]
* Updated the auto-generated codes according to the new Hazelcast
Open Binary Client Protocol (v2.0): message types are no longer of the type
`short`. Instead, `integer` is now being used to represent them.
https://github.com/hazelcast/hazelcast/pull/15450[#15450]
* Added the support for nested JSON objects in arrays.
https://github.com/hazelcast/hazelcast/pull/15425[#15425]
* To be shown on Management Center, the clients now send both its IP
address and canonical hostname. Before, only the hostname of the
client was shown.
https://github.com/hazelcast/hazelcast/pull/15421[#15421]
* Added a new implementation of `SecondsBasedEntryTaskScheduler` for the
`FOR_EACH` mode to improve the performance of `TransactionContext.commit()`.
https://github.com/hazelcast/hazelcast/pull/15414[#15414]
* Made the Hazelcast specific root nodes in the YAML
configurations optional.
https://github.com/hazelcast/hazelcast/pull/15389[#15389]
* Updated the `JavaVersion` class to support JDK 13 and 14 builds.
https://github.com/hazelcast/hazelcast/pull/15372[#15372]
* Added support for updating the licenses of all the running
members of a Hazelcast IMDG cluster using the REST API.
https://github.com/hazelcast/hazelcast/pull/15370[#15370]
* Added transaction specific backup operations: `TxnSetBackupOperation`
and `TxnDeleteBackupOperation`.
https://github.com/hazelcast/hazelcast/pull/15236[#15236]
* Fixed ``MemberAttributeEvent``s `getMembers()` method to return
the correct members list for the client.
https://github.com/hazelcast/hazelcast/pull/15231[#15231]
* Improved the WAN replication mechanism so that the WAN synchronization
now reports the progress based on target acknowledgments instead of
reporting based on enqueueing the WAN synchronization events in the local cluster.
https://github.com/hazelcast/hazelcast/pull/15221[#15221]
* Added `Nullable` and `Nonnull` annotations to IQueue.
https://github.com/hazelcast/hazelcast/pull/15156[#15156]
* Added support for null keys for the client side implementations of
`IMap.addEntryListener()`.
https://github.com/hazelcast/hazelcast/issues/15155[#15155]
* Improved the generics for the API with Projection, Predicate and EntryListener
by adding lower bounded wildcards to accept a wider range of parameters.
https://github.com/hazelcast/hazelcast/pull/15153[#15153]
* Implemented the Transaction propagation feature:
** Added the `suspend()` and `resume()` methods for `TransactionContext` interface.
** Added `Propagation.REQUIRES_NEW` support for `HazelcastTransactionManager`.
+
https://github.com/hazelcast/hazelcast/pull/15141[#15141]
+
* Unified `InvalidConfigurationException` and `ConfigurationException`.
https://github.com/hazelcast/hazelcast/pull/15132[#15132]
* Improved the performance of `TransactionLog.add()` by avoiding
the `LinkedList.remove()` call.
https://github.com/hazelcast/hazelcast/pull/15111[#15111]
* Improved the Raft snapshotting so that the old log entries are not
kept when there is no follower with an unknown match index.
https://github.com/hazelcast/hazelcast/pull/15062[#15062]
* Made `ClientConfig` to override `toString` as it is the situation
with `Config` to make it easier to troubleshoot.
https://github.com/hazelcast/hazelcast/issues/15061[#15061]
* Added the full example configuration files (XML and YAML) for the
Hazelcast Java client.
https://github.com/hazelcast/hazelcast/pull/15056[#15056]
* Hazelcast IMDG now sends error messages and stack trace separately
(for WAN consistency check) to the Management Center.
https://github.com/hazelcast/hazelcast/pull/15052[#15052]
* Added support for `HazelcastJsonValue` over REST API: When a
`HazelcastJsonValue` is requested, now a UTF8 encoded JSON value is returned. The
response  has the JSON string in the payload and "Content-Type"
header is set to `application/json`.
https://github.com/hazelcast/hazelcast/pull/15017[#15017]
* Introduced functional and serializable interfaces having a single
abstract method which declares a checked exception. The interfaces
are also serializable and can be readily used in the IMDG API when
providing a lambda which is then serialized.
https://github.com/hazelcast/hazelcast/pull/14993[#14993]
* Enhanced the queries (read-only operations) in the CP Subsystem so that
they are executed with linearizability but they are not appended to the Raft log.
By this way, the grow of Raft logs and snapshots of read-only operations are
prevented, leading to throughput improvement
https://github.com/hazelcast/hazelcast/pull/14986[#14986]
* Improved the WAN feature so that now lazy deserialization is used
when merging entries received via WAN. Otherwise, the unconditional
deserialization was causing overhead.
https://github.com/hazelcast/hazelcast/pull/14982[#14982]
* Added the support for Java 8 `Optionals` in the queries.
https://github.com/hazelcast/hazelcast/pull/14827[#14827]
* Fixed the Javadoc markup issues.
https://github.com/hazelcast/hazelcast/pull/14971[#14971]
* Introduced `PartitionIdSet`. This is a mutable set of partition IDs
which can be efficiently represented by a fixed size leading to a
better performance.
https://github.com/hazelcast/hazelcast/pull/14925[#14925]
* Made `AssertTask` an interface to enable lambdas to be used in
assert-eventually methods.
https://github.com/hazelcast/hazelcast/pull/14923[#14923]
* Updated the Hazelcast Kubernetes dependency to version 1.5.
https://github.com/hazelcast/hazelcast/pull/14898[#14898]
* Updated the map package so that it uses the Java 8 features.
https://github.com/hazelcast/hazelcast/pull/14891[#14891]
* Renamed the `Networking.start()` method as `Networking.restart()`
to make it obvious that it can be used for restarting an
already shutdown `Networking` instance.
https://github.com/hazelcast/hazelcast/pull/14872[#14872]
* Cleaned up the Maven repositories in Hazelcast's `pom.xml`
to simplify the usage of Maven proxies.
https://github.com/hazelcast/hazelcast/pull/14850[#14850]
* Eliminated the excessive logging when NIO networking is shutdown by
deregistering the IO threads.
https://github.com/hazelcast/hazelcast/pull/14823[#14823]
* Updated the web session manager dependency to its latest
version.
https://github.com/hazelcast/hazelcast/pull/14822[#14822]
* Separated the statistics for `IMap.set()` and `IMap.put()` methods.
https://github.com/hazelcast/hazelcast/pull/14811[#14811]
* Introduced a warning log for illegal reflective access operation when
using Java 9 and higher, and OpenJ 9.
https://github.com/hazelcast/hazelcast/pull/14798[#14798]
* Separated the statistic gathering for `IMap.set(K, V)` and
`IMap.put(K, V) operations`.
https://github.com/hazelcast/hazelcast/issues/14663[#14663]
* Improved the fluent interface of configuration classes by adding
the `return this` statements to the setter methods.
https://github.com/hazelcast/hazelcast/pull/11107[#11107]

[[bc-40]]
=== Breaking Changes

* Removed the support for primitives for `setAttribute` and
`getAttribute` operations.
All member attributes support only string attributes now.
https://github.com/hazelcast/hazelcast/pull/14974[#14974]
* Removed the backward compatible `ADDED` event from the
`loadAll` method.
https://github.com/hazelcast/hazelcast/pull/14964[#14964]
* Changed the `non-space-string` XSD type to collapse all
whitespaces, so they are handled correctly in the declarative
Hazelcast IMDG configuration files.
https://github.com/hazelcast/hazelcast/issues/14919[#14919]
* Removed the `java.util.function` back ports.
https://github.com/hazelcast/hazelcast/pull/14912[#14912]

==== Distributed Data Structures

* Removed the legacy `AtomicLong` and deprecated `IdGenerator`
implementations.
https://github.com/hazelcast/hazelcast/pull/15601[#15601]
* Removed the legacy `AtomicReference` implementation and
the `HazelcastInstance.getAtomicReference()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15593[#15593]
* Removed the legacy `Semaphore` implementation and
the `HazelcastInstance.getSemaphore()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15539[#15539]
* Removed the legacy `CountdownLatch` implementation and
the `HazelcastInstance.getCountdownLatch()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15538[#15538]
* Added null checks to `Cluster`, `Ringbuffer` and `ReplicatedMap`.
https://github.com/hazelcast/hazelcast/pull/15351[#15351]
* Added null checks and annotations to the IList, ISet, ITopic and
MultiMap interfaces.
https://github.com/hazelcast/hazelcast/pull/15220[#15220]
* Made the collection clones of IMap immutable so that
`UnsupportedOperationException` is thrown consistently
upon the attempts to update a collection returned by the `keySet`,
`entrySet`, `localKeySet`, `values` and `getAll` methods.
https://github.com/hazelcast/hazelcast/pull/15013[#15013]
* Added `Nullable` and `Nonnull` annotations to IMap.
https://github.com/hazelcast/hazelcast/pull/15003[#15003]


==== Configuration

* Moved all the read-only configuration classes to internal package.
https://github.com/hazelcast/hazelcast/pull/15569[#15569]
* Renamed `MapAttributeConfig` as `AttributeConfig`. Also, its
`extractor` field is renamed as `extractorClassName`.
https://github.com/hazelcast/hazelcast/pull/15548[#15548]
* Renamed the `group` configuration element as `cluster` and
removed the `GroupConfig` class.
https://github.com/hazelcast/hazelcast/pull/15540[#15540]
* Removed the deprecated the configuration parameters from
Replicated Map, i.e., `concurrency-level` and `replication-delay-millis`.
https://github.com/hazelcast/hazelcast/pull/15404[#15404]
* Removed the deprecated configuration parameters from the Near
Cache configuration.
https://github.com/hazelcast/hazelcast/pull/15313[#15313]
* Moved the Event Journal configuration inside the map/cache
configuration. Before, it was configured as a parent-level
element.
https://github.com/hazelcast/hazelcast/pull/15185[#15185]
* Moved the Merkle tree configuration under map configuration.
https://github.com/hazelcast/hazelcast/pull/15180[#15180] 
* Removed the XSDs for Hazelcast IMDG 3.x versions.
https://github.com/hazelcast/hazelcast/pull/15177[#15177]
* Removed deprecated client configuration methods such as
`isInsideAws()` and `newAliasedDiscoveryConfig()`.
https://github.com/hazelcast/hazelcast/pull/15012[#15012]
* Removed the `hazelcast.executionservice.taskscheduler.remove.oncancel`
system property and related methods.
https://github.com/hazelcast/hazelcast/pull/14998[#14998]

==== WAN Replication

* Replaced the `WAN` prefix of classes with `Wan` for the
sake of naming consistencies.
https://github.com/hazelcast/hazelcast/pull/15571[#15571]
* `WanReplicationPublisher` cleanups:
** Removed `WanReplicationEndpoint` and moved all of its methods
to `WanReplicationPublisher`.
** Replaced the `publishSyncEvent()` method with
`publishAntiEntropyEvent()`.
** Removed the `putBackup()` method.
** Moved the `removeWanEvents(int, String, String, int)` method to
the newly introduced  `InternalWanReplicationPublisher`.
** Removed the `Node` parameter from the `init()` method as it is private API.
+
https://github.com/hazelcast/hazelcast/pull/15527[#15527]
* Removed `ReplicationEventObject` so that the WAN are not wrapped
anymore, saving up on the heap space. By means of this, wrapper will also
not be serialized, which was using up bytes for the factory ID, class ID
and the full string with the service name.
https://github.com/hazelcast/hazelcast/pull/15432[#15432]
* The previously known `WanPublisherConfig` has been separated into
two configuration elements/classes to be used for built-in and
custom WAN publishers: `batch-publisher` and `custom-publisher`.
https://github.com/hazelcast/hazelcast/pull/15309[#15309]
* Separated WAN private and public classes into different packages.
https://github.com/hazelcast/hazelcast/pull/15195[#15195]

==== Split-Brain Protection

* Renamed the `isMinimumClusterSizeSatisfied()` method as
`hasMinimumSize().`
https://github.com/hazelcast/hazelcast/pull/15554[#15554]
* Removed the legacy merge policies:
** PASS_THROUGH
** PUT_IF_ABSENT
** HIGHER_HITS
** LATEST_ACCESS
+
https://github.com/hazelcast/hazelcast/pull/15292[#15292]


==== Serialization

* Added support for the following default Java serializers for collections:
** `ArrayDeque`
** `HashSet`
** `TreeSet`
** `TreeMap`
** `LinkedHashSet`
** `LinkedHashMap`
** `LinkedBlockingQueue`
** `ArrayBlockingQueue`
** `PriorityBlockingQueue`
** `DelayQueue`
** `SynchronousQueue`
** `LinkedBlockingDeque`
** `LinkedTransferQueue`
** `CopyOnWriteArrayList`
** `CopyOnWriteArraySet`
** `ConcurrentSkipListSet`
** `ConcurrentHashMap`
** `ConcurrentSkipListMap`
+
https://github.com/hazelcast/hazelcast/pull/15371[#15371]

==== REST

* Changed the `application/javascript` "Content-Type" header used
by REST API to respond to the JSON documents. Now, it uses
`application/json`.
https://github.com/hazelcast/hazelcast/pull/14972[#14972]

==== Distribution Package Changes

* Merged the client module into the core module: All the classes
in the `hazelcast-client` module have been moved to `hazelcast`.
`hazelcast-client.jar` will not be created anymore.
https://github.com/hazelcast/hazelcast/pull/15366[#15366]

==== API Package/Interface Changes

* The APIs that returned `UUID` string now returns `UUID`. These include `Endpoint.getUUID`,
listener registrations/deregistrations, keys of replica timestamps of `VectorClock`,
``UUID``s in the executor service, `UUID` in the `MigrationInfo`, cluster ID and transaction ID.
https://github.com/hazelcast/hazelcast/pull/15473[#15473]
* Moved the capability interfaces from `com.hazelcast.spi` to
`com.hz.internal.services`.
https://github.com/hazelcast/hazelcast/pull/15403[#15403]
Classes like AbstractDistributedObject have been moved to com.hz.spi.impl
* Made all the classes/interfaces in the `com.hazelcast.spi` package
`PrivateAPI`.
https://github.com/hazelcast/hazelcast/pull/15401[#15401]
* Converted the following custom query attribute abstract classes to
functional interfaces so that they have become
lambda friendly.
** `ArgumentParser`
** `ValueCallback`
** `ValueCollector`
** `ValueReader`
** `ValueExtractor`
* Converted `Projection` to a functional interface so that it has become
lambda friendly.
https://github.com/hazelcast/hazelcast/pull/15204[#15204]
* Removed the usage of `com.hazelcast.core.IBifunction`, replaced
it with `java.util.function.Bifunction`.
https://github.com/hazelcast/hazelcast/pull/15201[#15201]
* Separated the interfaces and implementations in `com.hazelcast.instance`:
Moved various classes (`Node`, `NodeContext`, etc.)
from the `com.hazelcast.instance` package to
`com.hazelcast.instance.impl`.
https://github.com/hazelcast/hazelcast/pull/15151[#15151]
* Renamed the `getId` method of `IdentifiedDataSerializable`
to `getClassId`.
https://github.com/hazelcast/hazelcast/pull/15127[#15127]
* Refactored and cleaned up the internal partition/migration listeners:
** Renamed `PartitionListener` to `PartitionReplicaInterceptor` and
removed registering child listeners, which is not used.
** Renamed `InternalMigrationListener` to `MigrationInterceptor` and
converted to interface with default methods.
+
https://github.com/hazelcast/hazelcast/pull/15051[#15051]
+
* Made the `EntryProcessor` interface lambda friendly.
https://github.com/hazelcast/hazelcast/pull/14995[#14995]
* Removed the `LegacyAsyncMap` interface.
https://github.com/hazelcast/hazelcast/pull/14994[#14994]
* Added `EntryExpiredListener` to the `EntryListener` interface.
https://github.com/hazelcast/hazelcast/pull/14959[#14959]
* The packages of the following classes have been changed:
+
[cols="3a,2a,3a,1a"]
|===

|Classes|Package Before IMDG 4.0|Package After IMDG 4.0|Details

| All private classes
| `com.hazelcast.spi.hotrestart`
| `com.hazelcast.internal.hotrestart`
| https://github.com/hazelcast/hazelcast/pull/15603[#15603]

| All private NIO and serialization classes
| `com.hazelcast.nio`
| `com.hazelcast.internal.nio`
| https://github.com/hazelcast/hazelcast/pull/15599[#15599]

| All private YAML, CRDT and memory classes
|

* `com.hazelcast.config.yaml`
* `com.hazelcast.crdt`
* `com.hazelcast.memory`
* `com.hazelcast.elastic`
|

* `com.hazelcast.internal.config.yaml`
* `com.hazelcast.internal.crdt`
* `com.hazelcast.internal.memory`
* `com.hazelcast.internal.elastic`
| https://github.com/hazelcast/hazelcast/pull/15588[#15588]

| All
| `com.hazelcast.util`
| `com.hazelcast.internal.util`
| https://github.com/hazelcast/hazelcast/pull/15570[#15570]

| `SerializationService`
| `com.hazelcast.spi.serialization`
| `com.hazelcast.internal.serialization`
| https://github.com/hazelcast/hazelcast/pull/15418[#15418]

| Private client classes
| 

* `client.connection`
* `client.proxy`
* `client.spi.properties`
* `client.spi`
* `client.util.ClientDelegatingFuture`
* `client.api`
|
* `client.impl.connection`
* `client.impl.proxy`
* `client.properties`
* `client.impl.spi`
* `client.impl.ClientDelegatingFuture`
* `client`
| https://github.com/hazelcast/hazelcast/pull/15377[#15377]

| `Joiner` and `TcpIpJoiner`
| `com.hazelcast.cluster` and `com.hazelcast.cluster.impl`
| `com.hazelcast.internal.cluster` and `com.hazelcast.internal.cluster.impl`
| https://github.com/hazelcast/hazelcast/pull/15335[#15335]

| All IExecutor classes
| `com.hazelcast.core`
| `com.hazelcast.executor`
| https://github.com/hazelcast/hazelcast/pull/15187[#15187]

|`ClassNameFilter`, `SerializationClassNameFilter` 
|`com.hazelcast.nio`
|`com.hazelcast.nio.serialization`
|https://github.com/hazelcast/hazelcast/pull/15171[#15171]

| All IMap classes
| `com.hazelcast.core`
| `com.hazelcast.map`
| https://github.com/hazelcast/hazelcast/pull/15149[#15149]

|`ReplicatedMap`
|`com.hazelcast.core`
|`com.hazelcast.replicatedmap`
|https://github.com/hazelcast/hazelcast/pull/15146[#15146]

|`IAtomicLong`, `IAtomicReference`, `ILock`, `ICondition`, `ISemaphore`, `ICountDownLatch`
|`com.hazelcast.core`
|`com.hazelcast.cp`
|https://github.com/hazelcast/hazelcast/pull/15143[#15143]

|`IndexAwarePredicate`, `VisitablePredicate`, `SqlPredicate/Parser`, `TruePredicate`
|`com.hazelcast.query`
|`com.hazelcast.query.impl.predicates`
|https://github.com/hazelcast/hazelcast/pull/15142[#15142]

|Transaction collection classes (`TransactionalMap`, `TransactionalList`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.transaction`
|https://github.com/hazelcast/hazelcast/pull/15129[#15129]

|`IQueue`, `QueueStore`, `IList`, `ISet`, `ItemEvent`, `ItemListener`
|`com.hazelcast.core`
|`com.hazelcast.collection`
|https://github.com/hazelcast/hazelcast/pull/15127[#15127]

|`MultiMap`
|`com.hazelcast.core`
|`com.hazelcast.multimap`
|https://github.com/hazelcast/hazelcast/pull/15123[#15123]

|`ITopic`, `Message`, `MessageListener`
|`com.hazelcast.core`
|`com.hazelcast.topic`
|https://github.com/hazelcast/hazelcast/pull/15122[#15122]

|`RingbufferStoreFactory`, `RingbufferStore`
|`com.hazelcast.core`
|`com.hazelcast.ringbuffer`
|https://github.com/hazelcast/hazelcast/pull/15121[#15121]

|Operation classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.impl.operationservice`
|https://github.com/hazelcast/hazelcast/pull/15115[#15115]

|Partition SPI classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.partition`
|https://github.com/hazelcast/hazelcast/pull/15088[#15088]

|Member and membership classes (`Cluster`, `Member`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.cluster`
.2+^.^|https://github.com/hazelcast/hazelcast/pull/15046[#15046]

|Client classes (`Client`, `ClientService`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.client.api`

|Partition classes
|`com.hazelcast.core`
|`com.hazelcast.partition`
|https://github.com/hazelcast/hazelcast/pull/15039[#15039]

|===



[[fixes-40]]
=== Fixes

* Fixed an issue where the `node.isMaster()` method could cause
inconsistent behaviors when it is executed during a partition service lock.
https://github.com/hazelcast/hazelcast/pull/15617[#15617]
* Fixed an issue where the CP subsystems' restart operations were
not being canceled and waiting the running/scheduled discovery tasks.
https://github.com/hazelcast/hazelcast/pull/15567[#15567]
* Fixed an issue where the executor service message task
was blocking the partition thread.
https://github.com/hazelcast/hazelcast/pull/15522[#15522]
* Fixed an issue where the used memory in metrics was becoming
a negative value.
https://github.com/hazelcast/hazelcast/issues/15485[#15485]
* Fixed an issue where `ClientMessageWriter` was throwing an
exception while writing to buffer.
https://github.com/hazelcast/hazelcast/issues/15471[#15471]
* Fixed an issue where the maps on the client side were encoded
as list of key value items, not list of keys and list of values.
https://github.com/hazelcast/hazelcast/pull/15467[#15467]
* Moved the `checkWanReplicationQueues` operation from the caller side
to the callee. https://github.com/hazelcast/hazelcast/pull/15412[#15412]
* Fixed an issue where `WanConsistencyCheckIgnoredEvent`, when it is
sent to Management Center, was throwing a `NullPointerException`.
https://github.com/hazelcast/hazelcast/pull/15400[#15400]
* Fixed an issue where the map configuration options `readBackupData`
and `statisticsEnabled` were not being respected when a new
`MapConfig` is dynamically added from a client to a running Hazelcast cluster.
https://github.com/hazelcast/hazelcast/issues/15382[#15382]
* Fixed an issue where the comparators were not able to act on
both keys and values. A custom paging predicate comparator may act on
keys and values at the same time even if only the keys are requested, e.g., using
the `IMap.keySet()` method. Before this fix only the keys were fetched for
this method, making comparators unable to act on values.
https://github.com/hazelcast/hazelcast/pull/15380[#15380]
* Optimized the shutdown for on-heap indexes: These indexes are cleaned on shutdown and
the index entries are removed one by one. For large indexes, e.g.,
for array/collection attribute indexes, this was taking a considerable amount of time.
https://github.com/hazelcast/hazelcast/issues/15340[#15340]
* Fixed the deserialization filtering for Externalizables and Deadlock in the
map index. The deserialization filter was not properly protecting against the
vulnerable Externalizable classes. The filtering has been extended.
https://github.com/hazelcast/hazelcast/pull/15358[#15358]
* Fixed an issue where the named scheduled tasks was not respecting
the `HazelcastInstanceAware` marker.
https://github.com/hazelcast/hazelcast/pull/15352[#15352]
* Fixed a possible `NullPointerException` for the `remove` variable in
`DeafultRecordStore`.
https://github.com/hazelcast/hazelcast/pull/15344[#15344]
* Fixed an issue where storing `MapStore` instances in `MapStoreConfig`
could cause member failures when the configuration is added
dynamically.
https://github.com/hazelcast/hazelcast/pull/15224[#15224]
* Fixed a `NullPointerException` in the query caches by setting
the `publisher-listener-id` if a query cache has already one.
https://github.com/hazelcast/hazelcast/pull/15215[#15215]
* Fixed an issue where `SimpleTokenCredentials` could not be
deserialized due to the missing handling in `SpiPortableHook`.
https://github.com/hazelcast/hazelcast/issues/15196[#15196]
* Fixed an issue where the queries like `labels[any] = 0` and `labels[any] = 1`
were optimized only to `false` since `labels[any]` was interpreted as a
regular attribute name having a single value.
https://github.com/hazelcast/hazelcast/pull/15163[#15163]
* For on-heap indexes, fixed an issue where a record's `lastAccessTime`
was not updated when it is being accessed through an index. 
Now, this way, the expiration `maxIdle` mechanism takes this into account.
https://github.com/hazelcast/hazelcast/pull/15136[#15136]
* Fixed an issue where `ExecutorServiceProxy` was unnecessarily
serializing the same task multiple times before submitting it
to multiple members.
https://github.com/hazelcast/hazelcast/pull/15069[#15069]
* Added the missing user code deployment section to the configuration
which is sent to Management Center.
https://github.com/hazelcast/hazelcast/pull/15044[#15044]
* Fixed an issue where two client listeners are not registered since
they listen on a single connection (not cluster wide listeners) by
adding cleanups for them.
https://github.com/hazelcast/hazelcast/pull/15041[#15041]
* Fixed the authentication mechanism between the clients and members
by adding a check to prevent re-verification while the client is changing
its owner member.
https://github.com/hazelcast/hazelcast/pull/15030[#15030]
* Added support for the missing aliased discovery strategies,
e.g., `gcp` and `kubernetes`, to `ClientConfigXmlGenerator`.
https://github.com/hazelcast/hazelcast/issues/15010[#15010]
* Fixed an issue where the client user code deployment was
becoming non-operational when assertions are enabled.
https://github.com/hazelcast/hazelcast/pull/15006[#15006]
* Some operations such as heartbeat checks and partition
migrations share common threads with the client login module.
In case of the long running client login module implementations,
some symptoms such as split brain syndrome can be seen. This has
been fixed by introducing a blocking executor which is used only
for the client authentications.
https://github.com/hazelcast/hazelcast/pull/14956[#14956]
* Fixed an issue where the `IMap.removeInterceptor()` method
was returning `void`.
https://github.com/hazelcast/hazelcast/pull/14955[#14955]
* Removed the `entryEvicted` event from the event firing mechanism
in the case of eviction. Before, both `entryEvicted` and `entryExpired`
events were being fired.
https://github.com/hazelcast/hazelcast/pull/14954[#14954]
* Fixed an issue where the Hazelcast IMDG configuration files, that
have an extension other than `.xml`, `.yaml` or `.yml` or do not have
an extension, were ignored silently. This was happening
when the configuration file is set by using the `hazelcast.config`
system property.
https://github.com/hazelcast/hazelcast/pull/14953[#14953]
* Fixed an issue where the client was not considering the new
address of a restarted member, which has the same UUID but could
have a different IP address after it is restarted.
https://github.com/hazelcast/hazelcast/pull/14842[#14842]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/14832[#14832]
* Fixed an issue where the outbound pipeline was not waking up
properly after various optimizations for write-through
persistence is made.
https://github.com/hazelcast/hazelcast/pull/14831[#14831]
* Fixed an issue caused by the cache being not ready to be used
immediately after the cache proxy was created.
https://github.com/hazelcast/hazelcast/pull/14821[#14821]
* Fixed an issue where the performance of `IMap.values()` was low when
using `PartitionPredicate`. Also, `PartitionPredicate` was not
respecting indexes. So, now global indexes are used for partition
queries.
https://github.com/hazelcast/hazelcast/pull/14814[#14814]
* Fixed a performance issue where there were unneeded iterations and
object creations while converting the client messages to user objects.
https://github.com/hazelcast/hazelcast/pull/13784[#13784]
* Fixed an issue where the locked entries with a time-to-live were not evicted.
With this fix, the lock operation checks if an entry has already expired.
https://github.com/hazelcast/hazelcast/issues/13272[#13272]
* Fixed an issue where there were excessive amount of logs on the target cluster
when `cache` config is missing for the WAN replication.
https://github.com/hazelcast/hazelcast/issues/12826[#12826]
* Fixed an issue where there was an inconsistent `removeIf` behavior among the
collection views of IMap.
https://github.com/hazelcast/hazelcast/issues/12198[#12198]
* Fixed a leak in the query cache due to `ListenerRegistrationHelper`, which
has been removed with this fix.
https://github.com/hazelcast/hazelcast/pull/11914[#11914]
* Fixed an issue where `NetworkConfig.setPortCount(int)` was not returning
the `this` instance compared to other setter methods in the class.
https://github.com/hazelcast/hazelcast/issues/11669[#11669]
* Fixed an issue where the `IMap.replace()` method was not loading entries
from the MapLoader when the keys could not be found in the memory.
https://github.com/hazelcast/hazelcast/issues/11300[#11300]

[[deprecated-40]]
=== Deprecated Features

* ???.
* The following system properties are deprecated:
** `???`
* The following Hazelcast IMDG interfaces/classes are deprecated and replaced
with the ones provided by the Hazelcast IMDG CP Subsystem:
** `???`
* The following classes are deprecated:

[[removed-40]]
=== Removed Features

* Removed the methods in the `Member` and `AddressPicker` classes.
* Removed the deprecated diagnostics property names.
* Removed the `ILock` interface. The `ILock implementation is still being kept
as the development/unsafe mode of CP Subsystem's `FencedLock`.
* Removed the legacy `IdGenerator` interface. Instead, `FlakeIdGenerator` has been used.
* Removed the deprecated `AsyncAtomicLong` and `AsyncAtomicReference` classes.
* Removed the deprecated cache eviction configurations.
* Removed the MapReduce feature.
* Removed the deprecated `LOCAL` transaction type (`TransactionType.LOCAL`)
* Removed the unused `newTransaction()` method.
* Removed the deprecated `optimizeQueries` map configuration parameter.
* Removed the deprecated `ClearNearCacheOperation`.
* Removed the following deprecated group properties:
** `hazelcast.version.check.enabled`
** `hazelcast.icmp.enabled`
** `hazelcast.icmp.parallel.mode`
** `hazelcast.icmp.echo.fail.fast.on.startup`
** `hazelcast.icmp.timeout`
** `hazelcast.icmp.interval`
** `hazelcast.icmp.max.attempts`
** `hazelcast.icmp.ttl`
** `hazelcast.mc.url.change.enabled`
** `hazelcast.slow.invocation.detector.threshold.millis`





