

== 4.0-BETA-1

NOTE: See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#upgrading-to-hazelcast-imdg-4-0[Hazelcast IMDG 4.0 Migration Guide^]
for the detailed guidelines to be followed when upgrading Hazelcast IMDG to 4.0.

[[nf-40]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **Persistent Memory Integration:** Added support for persistent memory,
such as Intel(R) Optane(TM) DC, to be used by Hazelcast's
High-Density Memory Store feature.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/index.html#using-persistent-memory[Using Persistent Memory section^].
* **Encrypting Data in Hot Restart Store:** Provided a framework and implementation to encrypt
data in Hot Restart stores ("at rest") for data held in distributed structures.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#encryption-at-rest[Encryption at Rest section^].
* **X.509 Certificate Authentication:** Added support for credential retrieval by the members
from the X.509 certificates configured on the clients.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#tls-authentication-type[Security chapter^].
* **Out of the Box LDAP Configuration:** Introduced a new LDAP login module
where you do not need to provide your own JAAS login module for this purpose.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#ldap-authentication-type[Security chapter^].
* **CP Subsystem Persistence:** Implemented persistency for Hazelcast's
CP (Consistency & Partition Tolerance) subsystem. 
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#cp-subsystem-persistence[CP Subsystem Persistence section^].

*_Hazelcast IMDG Open Source New Features:_*

* **CP Subsystem Development Mode:** Introduced `UNSAFE` mode for the CP data
structures. This way, you do not need to have at least three IMDG members
to use CP subsystem: you can benefit from its functionalities using only one
or two members. See the https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#cp-subsystem-unsafe-mode[CP Subsystem Unsafe Mode section].

[[enh-40]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **Separating WAN Publisher Configuration:** The previously known `wan-publisher`
(or `WanPublisherConfig`) has been separated into two configuration elements
to be used for built-in and custom WAN publishers:
** `batch-publisher` (or `WanBatchReplicationPublisherConfig`)
** `custom-publisher`  (or `CustomWanPublisherConfig`)
+
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/index.html#defining-wan-replication[Defining WAN Replication section^]
* **Tracking WAN Synchronization Events:** Management Center, logs and diagnostics now report
the progress of a WAN synchronization. https://github.com/hazelcast/hazelcast/pull/15221[#15221]
* **Improvements in the JAAS Authentication Mechanism:**
** Aligned with JAAS best practices.
** Added support for the standard JAAS callbacks, i.e., `NameCallback` and `PasswordCallback`
** Avoided automatic deserialization of custom credentials in the client protocol.
** Introduce the concept of security roles to distinguish between (a single) connecting side identity and its privileges.
** Used `Credentials` object only for authentication to prevent secrets leaks.
** Cleaned up the `Credentials` interface.
+
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#jaas-authentication[JAAS Authentication section^]
* **Improvements in the Security Configuration:**
** Replaced the `<group>` configuration by simple `<cluster-name>`.
** Removed the `group-password` configuration.
** Introduced the concept of security realms on the members. https://github.com/hazelcast/hazelcast/pull/15651[#15651]
** Added typed authentication and identity configuration (e.g. `<ldap>` authentication, `<token>` identity)
** Used similar identity configuration in client config
+
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#changes-in-the-security-configuration[Hazelcast IMDG 4.0 Migration Guide^]
and link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#security[Security chapter^].
* **Javadoc for the Hazelcast IMDG Enterprise Edition:** Added Javadoc JAR file
for the Hazelcast IMDG Enterprise Edition.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#getting-started[Getting Started section^]

*_Hazelcast IMDG Open Source Enhancements:_*

* **HTTPS for Scripts:** Enabled the REST endpoints for the `cluster.sh` and
`healthcheck.sh` scripts to use HTTPS. Before, they were
using HTTP. See the
link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#using-the-script-cluster-sh[cluster.sh^] and
link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#health-check-script[healtcheck.sh^] sections.
* **MapLoader with Custom time-to-live:** Introduced the `EntryStore` and `EntryLoader`
interfaces (adding expiration support for MapStore). See the
https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/index.html#loading-and-storing-persistent-data[Loading and Storing Persistent Data section].
* **Moby Naming:** Introduced friendly names for the Hazelcast instances to be shown
in the Hazelcast Management Center. See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#checking-the-name-of-the-instance-for-rest-client[Checking the Instances' Name section^]. Also, a new system property, `hazelcast.member.naming.moby.enabled`, is introduced for this purpose.
* **Improved Client Performance:** Introduced a way to eliminate the sync backup
wait from the client and send the backup ACK to the client:
the smart clients have been made backup aware and the backups
now are redirected to the client directly from the backup members.
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#configuring-backup-acknowledgment[Configuring Backup Acknowledgment section^].
* **Ownerless Client:** Previously, the clients had an owner member
responsible for cleaning up their resources after they leave the cluster. Also, the
ownership information was needed to be replicated to the whole cluster when a client joins the cluster.
This mechanism have been made simpler by introducing the following system properties
to control the lifecycle of the clients on the member side:
** `hazelcast.client.cleanup.period.millis`
** `hazelcast.client.cleanup.timeout.millis`
+
See the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#client-system-properties[Client System Properties section^].
* **Single Thread Hazelcast Clients Performance:** Hazelcast clients have been designed to be
used by multiple threads; the more threads you throw at it, the better the performance
(until it is saturated). Now, it has also been optimized for a single thread doing requests:
The default values for the `hazelcast.client.io.write.through` and `hazelcast.client.response.thread.dynamic`
have been changed from `false` to `true`.
* **JSON Support for REST:** Added support for `HazelcastJsonValue` over REST API: When a
`HazelcastJsonValue` is requested, now a UTF8 encoded JSON value is returned. The
response  has the JSON string in the payload and "Content-Type"
header is set to `application/json`.
https://github.com/hazelcast/hazelcast/pull/15017[#15017]

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Added option to disable retrieving the
`OSMBean.getFreePhysicalMemorySize()` method.
https://github.com/hazelcast/hazelcast/pull/16039[#16039]
* The `recreateCachesOnCluster` invocation is not being checked
for the maximum invocations count anymore during cluster restarts.
https://github.com/hazelcast/hazelcast/pull/16026[#16026]
* Removed the PID management from the IMDG start and stop
scripts. You can now start multiple Hazelcast instances, when
using the start script, without the need to create another
copy of the `/bin` directory, i.e., it now allows running
multiple processes.
https://github.com/hazelcast/hazelcast/pull/15934[#15934]
* Added the cache statistics to the dynamically collected metrics
https://github.com/hazelcast/hazelcast/pull/15926[#15926]
* The following operations have been added to the client side
Management Center service:
** `getMemberConfig`
** `runGc`
** `getThreadDump`
** `shutdownMember`
** `promoteMember`
** `getSystemProperties`
* Introduced cluster fail-fast when there are missing security
realms.
https://github.com/hazelcast/hazelcast/pull/15872[#15872]
* Enhanced the counters by adding the `set()` method so that they
can be used in Hazelcast Jet.
https://github.com/hazelcast/hazelcast/pull/15867[#15867]
* Added support for persisting and restoring the active CP members
list.
https://github.com/hazelcast/hazelcast/pull/15828[#15828]
* Added binary compatibility tests for the client protocol.
https://github.com/hazelcast/hazelcast/pull/15822[#15822]
* Added `ConnectionRetryConfig` to `ClientConfigXmlGenerator`.
https://github.com/hazelcast/hazelcast/pull/15821[#15821]
* Removed the legacy `BindMessage` class and renamed `ExtendedBindMessage`
as `BindMessage`.
https://github.com/hazelcast/hazelcast/pull/15820[#15820]
* Unified the IMap and ICache eviction configurations to decrease
the configuration complexity.
https://github.com/hazelcast/hazelcast/pull/15592[#15592]
* Introduced dynamic metric collection. Previously, Hazelcast metrics were 
reported programmatically to the Hazelcast Management Center, one by one. 
Introducing new metrics required changes both in IMDG and in MC, which limited the
number of metrics sent to MC. In 4.0 this has been changed to collecting and reporting 
all available metrics dynamically just by declaring them in IMDG. Besides reporting
the metrics dynamically to MC exposing them on JMX is done dynamically as well. 
Both reporting to MC and exposing on JMX are toggleable by using the `metric` 
configuration element introduced in 4.0.
+
https://github.com/hazelcast/hazelcast/pull/15560[#15560],
https://github.com/hazelcast/hazelcast/pull/15650[#15650],
https://github.com/hazelcast/hazelcast/pull/15667[#15667],
https://github.com/hazelcast/hazelcast/pull/15779[#15779],
https://github.com/hazelcast/hazelcast/pull/15782[#15782],
https://github.com/hazelcast/hazelcast/pull/15818[#15818]
* Set the log level to `FINEST` for `PartitionMigratingException`.
https://github.com/hazelcast/hazelcast/pull/15577[#15577]
* Added the support for nested JSON objects in arrays.
https://github.com/hazelcast/hazelcast/pull/15425[#15425]
* To be shown on Management Center, the clients now send both its IP
address and canonical hostname. Before, only the hostname of the
client was shown.
https://github.com/hazelcast/hazelcast/pull/15421[#15421]
* Added a new implementation of `SecondsBasedEntryTaskScheduler` for the
`FOR_EACH` mode to improve the performance of `TransactionContext.commit()`.
https://github.com/hazelcast/hazelcast/pull/15414[#15414]
* Added a level of memory protection to the Hazelcast client protocol:
untrusted connections (the ones which haven't finished
authentication yet) do not accept fragmented messages; they check the
frame size against a configurable limit.
https://github.com/hazelcast/hazelcast/pull/15396[#15396]
* Made the Hazelcast specific root nodes in the YAML
configurations optional.
https://github.com/hazelcast/hazelcast/pull/15389[#15389]
* Updated the `JavaVersion` class to support JDK 13 and 14 builds.
https://github.com/hazelcast/hazelcast/pull/15372[#15372]
* Added support for updating the licenses of all the running
members of a Hazelcast IMDG cluster using the REST API.
https://github.com/hazelcast/hazelcast/pull/15370[#15370]
* Introduced configuration of initial permits for CP subsystem
semaphore.
https://github.com/hazelcast/hazelcast/issues/15208[#15208]
* Added support for null keys for the client side implementations of
`IMap.addEntryListener()`.
https://github.com/hazelcast/hazelcast/issues/15155[#15155]
* Improved the generics for the API with Projection, Predicate and EntryListener
by adding lower bounded wildcards to accept a wider range of parameters.
https://github.com/hazelcast/hazelcast/pull/15153[#15153]
* Implemented the Transaction propagation feature:
** Added the `suspend()` and `resume()` methods for `TransactionContext` interface.
** Added `Propagation.REQUIRES_NEW` support for `HazelcastTransactionManager`.
+
https://github.com/hazelcast/hazelcast/pull/15141[#15141]
+
* Improved the performance of `TransactionLog.add()` by avoiding
the `LinkedList.remove()` call.
https://github.com/hazelcast/hazelcast/pull/15111[#15111]
* Improved the Raft snapshotting so that the old log entries are not
kept when there is no follower with an unknown match index.
https://github.com/hazelcast/hazelcast/pull/15062[#15062]
* Made `ClientConfig` to override `toString` as it is the situation
with `Config` to make it easier to troubleshoot.
https://github.com/hazelcast/hazelcast/issues/15061[#15061]
* Added the full example configuration files (XML and YAML) for the
Hazelcast Java client.
https://github.com/hazelcast/hazelcast/pull/15056[#15056]
* Introduced functional and serializable interfaces having a single
abstract method which declares a checked exception. The interfaces
are also serializable and can be readily used in the IMDG API when
providing a lambda which is then serialized.
https://github.com/hazelcast/hazelcast/pull/14993[#14993]
* Enhanced the queries (read-only operations) in the CP Subsystem so that
they are executed with linearizability but they are not appended to the Raft log.
By this way, the grow of Raft logs and snapshots of read-only operations are
prevented, leading to throughput improvement
https://github.com/hazelcast/hazelcast/pull/14986[#14986]
* Improved the WAN feature so that now lazy deserialization is used
when merging entries received via WAN. Otherwise, the unconditional
deserialization was causing overhead.
https://github.com/hazelcast/hazelcast/pull/14982[#14982]
* Updated the following packages to Java 8 and removed the
3.x rolling upgrade compatibility paths: cache, MultiMap, cluster,
partition, WAN replication, CP subsystem, Hot Restart.
https://github.com/hazelcast/hazelcast/issues/14896[#14896]
* Added the support for Java 8 `Optionals` in the queries.
https://github.com/hazelcast/hazelcast/pull/14827[#14827]
* Fixed the Javadoc markup issues.
https://github.com/hazelcast/hazelcast/pull/14971[#14971]
* Updated the Hazelcast Kubernetes dependency to version 1.5.
https://github.com/hazelcast/hazelcast/pull/14898[#14898]
* Cleaned up the Maven repositories in Hazelcast's `pom.xml`
to simplify the usage of Maven proxies.
https://github.com/hazelcast/hazelcast/pull/14850[#14850]
* Updated the web session manager dependency to its latest
version.
https://github.com/hazelcast/hazelcast/pull/14822[#14822]
* Separated the statistics for `IMap.set()` and `IMap.put()` methods.
https://github.com/hazelcast/hazelcast/pull/14811[#14811]
* Introduced a warning log for illegal reflective access operation when
using Java 9 and higher, and OpenJ9.
https://github.com/hazelcast/hazelcast/pull/14798[#14798]
* Improved the fluent interface of configuration classes by adding
the `return this` statements to the setter methods.
https://github.com/hazelcast/hazelcast/pull/11107[#11107]
* Aligned the put mechanism for IMap and ICache: As in ICache,
now the put operations without time-to-live (TTL) in IMap makes an
entry either to live forever or use the TTL in the map's
configuration (if configured).
https://github.com/hazelcast/hazelcast/issues/10965[#10965]
* Added support for falling back to a "default" configuration for
the cache data structure.
https://github.com/hazelcast/hazelcast/issues/10695[#10695]

[[bc-40]]
=== Breaking Changes

NOTE: Please see the link:https://docs.hazelcast.org/docs/4.0-BETA-1/manual/html-single/#upgrading-to-hazelcast-imdg-4-0[Upgrading to Hazelcast IMDG 4.0^] for the details of following breaking changes to be considered while upgrading to IMDG 4.0. 

==== Distributed Data Structures

* Removed the `MapEvictionPolicy` class and its related
configurations. This has brought the following changes:
** `EvictionConfig` is used instead of `MapEvictionPolicy` for
custom eviction policies.
** `MapEvictionPolicy` has been removed and `MapEvictionPolicyComparator`
has been addd for the same tasks.
** `EvictionPolicyComparator`, `MapEvictionPolicyComparator` and
`CacheEvictionPolicyComparator` have become interfaces.
** Moved `EvictionPolicyComparator`  and `EvictableEntryView` to
the `com.hazelcast.spi.eviction` package.
** Renamed the `accessHits()` method as `hits()`.
+
https://github.com/hazelcast/hazelcast/pull/15939[#15939]
* Removed deprecated `IMap` methods accepting `EntryListener`.
https://github.com/hazelcast/hazelcast/pull/15781[#15781]
* Removed deprecated `DistributedObjectEvent.getObjectId`. 
The replacement is `DistributedObjectEvent.getObjectName`.
https://github.com/hazelcast/hazelcast/pull/15773[#15773]
* Removed the deprecated `getReplicationEventCount()` method of
local replicated map statistics.
https://github.com/hazelcast/hazelcast/pull/15676[#15676]
* Removed the legacy `AtomicLong` and deprecated `IdGenerator`
implementations.
https://github.com/hazelcast/hazelcast/pull/15601[#15601]
* Removed the legacy `ILock` implementation and
the `HazelcastInstance.getLock()` method. Instead
we provide the unsafe mode of CP Subsystem's `FencedLock`.
The `ICondition` is not supported anymore.
https://github.com/hazelcast/hazelcast/pull/15625[#15625]
* Removed the legacy `AtomicReference` implementation and
the `HazelcastInstance.getAtomicReference()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15593[#15593]
* Removed the legacy `Semaphore` implementation and
the `HazelcastInstance.getSemaphore()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15539[#15539]
* Removed the legacy `CountdownLatch` implementation and
the `HazelcastInstance.getCountdownLatch()` method. Instead
we provide the unsafe mode for all CP data structures.
https://github.com/hazelcast/hazelcast/pull/15538[#15538]
* Added `Nullable` and `Nonnull` annotations to IQueue, IMap,
`HazelcastInstance`, Cardinality Estimator, IExecutor, Durable Executor,
`QuorumService`, CP subsystem, logging service,
lifecycle service, partition service and client service.
https://github.com/hazelcast/hazelcast/pull/15156[#15156],
https://github.com/hazelcast/hazelcast/pull/15003[#15003],
https://github.com/hazelcast/hazelcast/pull/15442[#15442],
https://github.com/hazelcast/hazelcast/pull/15842[#15842]
* Added null checks and annotations to `Cluster`, Ringbuffer, Replicated Map,
IList, ISet, ITopic and MultiMap interfaces.
https://github.com/hazelcast/hazelcast/pull/15351[#15351],
https://github.com/hazelcast/hazelcast/pull/15220[#15220]
* Made the collection clones of IMap immutable so that
`UnsupportedOperationException` is thrown consistently
upon the attempts to update a collection returned by the `keySet`,
`entrySet`, `localKeySet`, `values` and `getAll` methods.
https://github.com/hazelcast/hazelcast/pull/15013[#15013]

==== Distributed Events

* Removed the unused entry listener configuration code since
the return type of `getImplementation()` has been changed from
`EntryListener` to `MapListener`.
https://github.com/hazelcast/hazelcast/pull/16051[#16051]
* Fixed ``MemberAttributeEvent``s `getMembers()` method to return
the correct members list for the client.
https://github.com/hazelcast/hazelcast/pull/15231[#15231]
* Refactored the `MigrationListener` API. With this change,
an event is published when a new migration process starts
and another one when migration is completed. Additionally,
on each replica migration, both for primary and backup
replica migrations, a migration event is published.
https://github.com/hazelcast/hazelcast/pull/15071[#15071]
* Removed the backward compatible `ADDED` event from the
`loadAll` method.
https://github.com/hazelcast/hazelcast/pull/14964[#14964]
* Refactored and cleaned up the internal partition/migration listeners:
** Renamed `PartitionListener` to `PartitionReplicaInterceptor` and
removed registering child listeners, which is not used.
** Renamed `InternalMigrationListener` to `MigrationInterceptor` and
converted to interface with default methods.
+
https://github.com/hazelcast/hazelcast/pull/15051[#15051]
* Added `EntryExpiredListener` to the `EntryListener` interface.
https://github.com/hazelcast/hazelcast/pull/14959[#14959]

==== Configuration

* `CachingProvider` no longer resolves an URI as the instance name
since it was used both as the namespace for the cache manager and as a
means to locate a running Hazelcast instance.
https://github.com/hazelcast/hazelcast/pull/15995[#15995]
* The group name in the client configuration renamed to cluster name.
https://github.com/hazelcast/hazelcast/pull/15772[#15772]
* Unified `InvalidConfigurationException` and `ConfigurationException`.
https://github.com/hazelcast/hazelcast/pull/15132[#15132]
* Removed the deprecated `AwsConfig` getter/setter methods, e.g., 
`getAccessKey()`. They have been replaced with the `getProperty()`
methods, e.g., `getProperty("access-key")`.
https://github.com/hazelcast/hazelcast/pull/15758[#15758]
* Moved the following client statistics properties to the public `ClientProperty`
class.
** `hazelcast.client.statistics.enabled`
** `hazelcast.client.statistics.period.seconds`
+
https://github.com/hazelcast/hazelcast/pull/15752[#15752]
* Undeprecated the following group properties:
** `hazelcast.memcache.enabled`
** `hazelcast.rest.enabled`
** `hazelcast.http.healthcheck.enabled`
+
https://github.com/hazelcast/hazelcast/pull/15743[#15743]
* Removed the deprecated `get/setImplementation()` methods of
login module configuration. They have been replaced with
`get/setClassName()`.
https://github.com/hazelcast/hazelcast/pull/15729[#15729]
* Removed the deprecated `get/setPartitionStrategy()` methods of
`PartitioningStrategyConfig` configuration. They have been replaced with
`get/setPartitioningStrategy()`.
https://github.com/hazelcast/hazelcast/pull/15730[#15730]
* Removed the deprecated `get/setSyncBackupCount()` methods of
`MultiMap` configuration. They have been replaced with
`get/setBackupCount()`.
https://github.com/hazelcast/hazelcast/pull/15720[#15720]
* Removed the deprecated `get/setServiceImpl()` methods of
service configuration. They have been replaced with
`get/setImplementation()`.
https://github.com/hazelcast/hazelcast/pull/15680[#15680]
* Removed the `connection-attempt-period` and `connection-attempt-limit`
configuration elements. Instead, the elements of `connection-retry`
are now used.
https://github.com/hazelcast/hazelcast/pull/15675[#15675]
* Renamed `MapAttributeConfig` as `AttributeConfig`. Also, its
`extractor` field is renamed as `extractorClassName`.
https://github.com/hazelcast/hazelcast/pull/15548[#15548]
* Improved the index configuration API so that now you
can specify the name of the index. Also, instead of boolean type,
you can use index type enumeration.
https://github.com/hazelcast/hazelcast/pull/15537[#15537]
* Renamed the `group-name` configuration element as `cluster-name` and
removed the `GroupConfig` class.
https://github.com/hazelcast/hazelcast/pull/15540[#15540]
* Removed the deprecated configuration parameters from
Replicated Map, i.e., `concurrency-level` and `replication-delay-millis`.
https://github.com/hazelcast/hazelcast/pull/15404[#15404]
* Removed the deprecated configuration parameters from the Near
Cache configuration.
https://github.com/hazelcast/hazelcast/pull/15313[#15313]
* Moved the Event Journal configuration inside the map/cache
configuration. Before, it was configured as a parent-level
element.
https://github.com/hazelcast/hazelcast/pull/15185[#15185]
* Moved the Merkle tree configuration under map configuration.
https://github.com/hazelcast/hazelcast/pull/15180[#15180] 
* Removed the XSDs for Hazelcast IMDG 3.x versions.
https://github.com/hazelcast/hazelcast/pull/15177[#15177]
* Removed deprecated client configuration methods such as
`isInsideAws()` and `newAliasedDiscoveryConfig()`.
https://github.com/hazelcast/hazelcast/pull/15012[#15012]
* Removed the `hazelcast.executionservice.taskscheduler.remove.oncancel`
system property and related methods.
https://github.com/hazelcast/hazelcast/pull/14998[#14998]
* Changed the `non-space-string` XSD type to collapse all
whitespaces, so they are handled correctly in the declarative
Hazelcast IMDG configuration files.
https://github.com/hazelcast/hazelcast/issues/14919[#14919]

==== WAN Replication

* Cleaned up the WAN publisher SPI to make it easier to implement integration between map/cache entry mutation and an external system.
+
https://github.com/hazelcast/hazelcast/pull/15195[#15195],
https://github.com/hazelcast/hazelcast/pull/15432[#15432],
https://github.com/hazelcast/hazelcast/pull/15527[#15527]
* Replaced the `WAN` prefix of classes with `Wan` for the
sake of naming consistencies.
https://github.com/hazelcast/hazelcast/pull/15571[#15571]
* Separated WAN private and public classes into different packages.
https://github.com/hazelcast/hazelcast/pull/15195[#15195]

==== Split-Brain Protection and Split-Brain Merge

* Introduced "split brain protection" concept to replace "quorum"
to make it more explicit and unambiguous. Classes and configuration
elements including the term "quorum" has been replaced by "splitbrainprotection".
https://github.com/hazelcast/hazelcast/pull/15444[#15444]
* Renamed the `isMinimumClusterSizeSatisfied()` method as
`hasMinimumSize().`
https://github.com/hazelcast/hazelcast/pull/15554[#15554]
* Removed the legacy merge policies specific to a data structure
in favour of generic merge policies.
** PASS_THROUGH
** PUT_IF_ABSENT
** HIGHER_HITS
** LATEST_ACCESS
+
https://github.com/hazelcast/hazelcast/pull/15292[#15292]

==== Serialization

* Since `SerializationService` is now an internal API,
the implementations of `ObjectDataOutput` make use of
`SerializationServiceSupport` where serialization service
is needed in the user customizations.
https://github.com/hazelcast/hazelcast/pull/16046[#16046]
* Added support for the following default Java serializers for collections:
** `ArrayDeque`
** `HashSet`
** `TreeSet`
** `TreeMap`
** `LinkedHashSet`
** `LinkedHashMap`
** `LinkedBlockingQueue`
** `ArrayBlockingQueue`
** `PriorityBlockingQueue`
** `DelayQueue`
** `SynchronousQueue`
** `LinkedBlockingDeque`
** `LinkedTransferQueue`
** `CopyOnWriteArrayList`
** `CopyOnWriteArraySet`
** `ConcurrentSkipListSet`
** `ConcurrentHashMap`
** `ConcurrentSkipListMap`
+
https://github.com/hazelcast/hazelcast/pull/15371[#15371]

==== REST

* Changed the `application/javascript` "Content-Type" header used
by REST API to respond to the JSON documents. Now, it uses
`application/json`.
https://github.com/hazelcast/hazelcast/pull/14972[#14972]

==== Distribution Package Changes

* Merged the client module into the core module: All the classes
in the `hazelcast-client` module have been moved to `hazelcast`.
`hazelcast-client.jar` will not be created anymore.
https://github.com/hazelcast/hazelcast/pull/15366[#15366]

==== Query Engine API

* The Predicate API has been cleaned up to eliminate exposing internal 
interfaces and classes. The end result is that the public Predicate API 
provides only interfaces (Predicate, PagingPredicate, and 
PartitionPredicate) with no dependencies on internal APIs.
https://github.com/hazelcast/hazelcast/pull/15142[#15142]
* Converted `Projection` to a functional interface so that it has become
lambda friendly.
https://github.com/hazelcast/hazelcast/pull/15204[#15204]
* Converted the `Aggregator` abstract class to an interface.
https://github.com/hazelcast/hazelcast/pull/15764[#15764]
* Converted the following custom query attribute abstract classes to
functional interfaces so that they have become
lambda friendly.
** `ArgumentParser`
** `ValueCallback`
** `ValueCollector`
** `ValueReader`
** `ValueExtractor`


==== API Package/Interface Changes

* Moved the following classes from `com.hazelcast.monitor`
to `com.hazelcast.internal.monitor`:
** `HotRestartState`
** `LocalCacheStats`
** `LocalFlakeIdGeneratorStats`
** `LocalGCStats`
** `LocalMemoryStats`
** `LocalOperationStats`
** `LocalPNCounterStats`
** `LocalRecordStoreStats`
** `LocalWanPublisherStats`
** `LocalWanStats`
** `MemberPartitionState`
** `MemberState`
** `NodeState`
** `WanSyncState`
** All classes in `com.hazelcast.monitor.impl`
+
https://github.com/hazelcast/hazelcast/pull/15888[#15888]
* Relocated the following classes:
** `com.hazelcast.monitor.LocalQueueStats` -> `com.hazelcast.collection.LocalQueueStats`
** `com.hazelcast.monitor.LocalExecutorStats` -> `com.hazelcast.executor.LocalExecutorStats`
** `com.hazelcast.monitor.LocalInstanceStats` -> `com.hazelcast.instance.LocalInstanceStats`
** `com.hazelcast.internal.management.JsonSerializable` -> `com.hazelcast.json.internal.JsonSerializable`
** `com.hazelcast.monitor.LocalMapStats` -> `com.hazelcast.map.LocalMapStats`
** `com.hazelcast.monitor.LocalMultiMapStats` -> `com.hazelcast.multimap.LocalMultiMapStats`
** `com.hazelcast.monitor.NearCacheStats` -> `com.hazelcast.nearcache.NearCacheStats`
** `com.hazelcast.monitor.LocalReplicatedMapStats` -> `com.hazelcast.replicatedmap.LocalReplicatedMapStats`
** `com.hazelcast.monitor.LocalTopicStats` -> `com.hazelcast.topic.LocalTopicStats`
+
https://github.com/hazelcast/hazelcast/pull/15888[#15888]
* Moved the `getXaResource()` method from the `TransactionContext` class
to `HazelcastInstance`.
https://github.com/hazelcast/hazelcast/pull/15728[#15728]
* Moved various private classes to internal packages.
https://github.com/hazelcast/hazelcast/pull/15569[#15569],
https://github.com/hazelcast/hazelcast/pull/15570[#15570],
https://github.com/hazelcast/hazelcast/pull/15588[#15588],
https://github.com/hazelcast/hazelcast/pull/15599[#15599],
https://github.com/hazelcast/hazelcast/pull/15603[#15603],
https://github.com/hazelcast/hazelcast/pull/15616[#15616],
https://github.com/hazelcast/hazelcast/pull/15171[#15171],
https://github.com/hazelcast/hazelcast/pull/15151[#15151],
https://github.com/hazelcast/hazelcast/pull/15146[#15146],
https://github.com/hazelcast/hazelcast/pull/15145[#15145],
https://github.com/hazelcast/hazelcast/pull/15129[#15129],
https://github.com/hazelcast/hazelcast/pull/15124[#15124],
https://github.com/hazelcast/hazelcast/pull/15123[#15123],
https://github.com/hazelcast/hazelcast/pull/15122[#15122],
https://github.com/hazelcast/hazelcast/pull/15121[#15121],
https://github.com/hazelcast/hazelcast/pull/15888[#15888],
https://github.com/hazelcast/hazelcast/pull/15887[#15887]
* The APIs that returned `UUID` string now returns `UUID`. These include `Endpoint.getUUID`,
listener registrations/deregistrations, keys of replica timestamps of `VectorClock`,
``UUID``s in the executor service, `UUID` in the `MigrationInfo`, cluster ID and transaction ID.
https://github.com/hazelcast/hazelcast/pull/15473[#15473]
* Removed `ICompletableFuture` which was a replacement for the missing JDK
8's `CompletableFuture`. Now, it has been replaced by `CompletionStage`.
See https://github.com/hazelcast/hazelcast/pull/15441[#15441] for more details.
* Removed the usage of `com.hazelcast.core.IBifunction`, replaced
it with `java.util.function.Bifunction`.
https://github.com/hazelcast/hazelcast/pull/15201[#15201]
* Renamed the `getId` method of `IdentifiedDataSerializable`
to `getClassId`.
https://github.com/hazelcast/hazelcast/pull/15127[#15127]
+
* Made the `EntryProcessor` interface lambda friendly.
https://github.com/hazelcast/hazelcast/pull/14995[#14995]
* Removed the `LegacyAsyncMap` interface.
https://github.com/hazelcast/hazelcast/pull/14994[#14994]
* Removed the support for primitives for `setAttribute` and
`getAttribute` member attributes.
All member attributes support only `String` attributes now.
https://github.com/hazelcast/hazelcast/pull/14974[#14974]
* Removed the `java.util.function` back ports.
https://github.com/hazelcast/hazelcast/pull/14912[#14912]
* `CacheService` now implements `StatisticsAwareService`
https://github.com/hazelcast/hazelcast/issues/14904[#14904]
* Renamed the class to start a Hazelcast member from
`com.hazelcast.core.server.StartServer` to
`com.hazelcast.core.server.HazelcastMemberStarter`.
https://github.com/hazelcast/hazelcast/issues/12791[#12791]
* The packages of the following classes have been changed:
+
[cols="3a,2a,3a,1a"]
|===

|Classes|Package Before IMDG 4.0|Package After IMDG 4.0|Details

| `LdapLoginModule`, `BasicLdapLoginModule`
| `com.hazelcast.security.impl`
| `com.hazelcast.security.loginimpl`
| https://github.com/hazelcast/hazelcast/pull/15929[#15929]

| `EventJournalMapEvent`, `EventJournalCacheEvent`
| 

* `com.hazelcast.map.impl.journal`
* `com.hazelcast.cache.impl.journal`
|

* `com.hazelcast.map`
* `com.hazelcast.cache`
| https://github.com/hazelcast/hazelcast/pull/15900[#15900]

| All private classes
|

* `com.hazelcast.client.config`
* `com.hazelcast.config`
* `com.hazelcast.spi.partition`
* `com.hazelcast.map.journal`
* `com.hazelcast.query.extractor`
|

* `com.hazelcast.client.config.impl`
* `com.hazelcast.internal.config`
* `com.hazelcast.internal.partition`
* `com.hazelcast.map.impl.journal`
* `com.hazelcast.query.impl`

| https://github.com/hazelcast/hazelcast/pull/15887[#15887]

| All classes
| `com.hazelcast.internal.util.function`
| `com.hazelcast.function`
| https://github.com/hazelcast/hazelcast/pull/15802[#15802]

| `WanPublisherState`
| `com.hazelcast.config`
| `com.hazelcast.wan`
| https://github.com/hazelcast/hazelcast/pull/15791[#15791]

| All private classes
| `com.hazelcast.spi.hotrestart`
| `com.hazelcast.internal.hotrestart`
| https://github.com/hazelcast/hazelcast/pull/15603[#15603]

| All private NIO and serialization classes
| `com.hazelcast.nio`
| `com.hazelcast.internal.nio`
| https://github.com/hazelcast/hazelcast/pull/15599[#15599]

| All private YAML, CRDT and memory classes
|

* `com.hazelcast.config.yaml`
* `com.hazelcast.crdt`
* `com.hazelcast.memory`
* `com.hazelcast.elastic`
|

* `com.hazelcast.internal.config.yaml`
* `com.hazelcast.internal.crdt`
* `com.hazelcast.internal.memory`
* `com.hazelcast.internal.elastic`
| https://github.com/hazelcast/hazelcast/pull/15588[#15588]

| All
| `com.hazelcast.util`
| `com.hazelcast.internal.util`
| https://github.com/hazelcast/hazelcast/pull/15570[#15570]

| `SerializationService`
| `com.hazelcast.spi.serialization`
| `com.hazelcast.internal.serialization`
| https://github.com/hazelcast/hazelcast/pull/15418[#15418]

| Private client classes
| 

* `client.connection`
* `client.proxy`
* `client.spi.properties`
* `client.spi`
* `client.util.ClientDelegatingFuture`
* `client.api`
|
* `client.impl.connection`
* `client.impl.proxy`
* `client.properties`
* `client.impl.spi`
* `client.impl.ClientDelegatingFuture`
* `client`
| https://github.com/hazelcast/hazelcast/pull/15377[#15377]

| `Joiner` and `TcpIpJoiner`
| `com.hazelcast.cluster` and `com.hazelcast.cluster.impl`
| `com.hazelcast.internal.cluster` and `com.hazelcast.internal.cluster.impl`
| https://github.com/hazelcast/hazelcast/pull/15335[#15335]

| All IExecutor classes
| `com.hazelcast.core`
| `com.hazelcast.executor`
| https://github.com/hazelcast/hazelcast/pull/15187[#15187]

| `Address`
| `com.hazelcast.nio`
| `com.hazelcast.cluster`
| https://github.com/hazelcast/hazelcast/pull/15172[#15172]

|`ClassNameFilter`, `SerializationClassNameFilter` 
|`com.hazelcast.nio`
|`com.hazelcast.nio.serialization`
|https://github.com/hazelcast/hazelcast/pull/15171[#15171]

| All IMap classes
| `com.hazelcast.core`
| `com.hazelcast.map`
| https://github.com/hazelcast/hazelcast/pull/15149[#15149]

|`ReplicatedMap`
|`com.hazelcast.core`
|`com.hazelcast.replicatedmap`
|https://github.com/hazelcast/hazelcast/pull/15146[#15146]

|`IAtomicLong`, `IAtomicReference`, `ILock`, `ICondition`, `ISemaphore`, `ICountDownLatch`
|`com.hazelcast.core`
|`com.hazelcast.cp`
|https://github.com/hazelcast/hazelcast/pull/15143[#15143]

|`IndexAwarePredicate`, `VisitablePredicate`, `SqlPredicate/Parser`, `TruePredicate`
|`com.hazelcast.query`
|`com.hazelcast.query.impl.predicates`
|https://github.com/hazelcast/hazelcast/pull/15142[#15142]

|Transaction collection classes (`TransactionalMap`, `TransactionalList`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.transaction`
|https://github.com/hazelcast/hazelcast/pull/15129[#15129]

|`IQueue`, `QueueStore`, `IList`, `ISet`, `ItemEvent`, `ItemListener`
|`com.hazelcast.core`
|`com.hazelcast.collection`
|https://github.com/hazelcast/hazelcast/pull/15127[#15127]

|`MultiMap`
|`com.hazelcast.core`
|`com.hazelcast.multimap`
|https://github.com/hazelcast/hazelcast/pull/15123[#15123]

|`ITopic`, `Message`, `MessageListener`
|`com.hazelcast.core`
|`com.hazelcast.topic`
|https://github.com/hazelcast/hazelcast/pull/15122[#15122]

|`RingbufferStoreFactory`, `RingbufferStore`
|`com.hazelcast.core`
|`com.hazelcast.ringbuffer`
|https://github.com/hazelcast/hazelcast/pull/15121[#15121]

|Operation classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.impl.operationservice`
|https://github.com/hazelcast/hazelcast/pull/15115[#15115]

|Partition SPI classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.partition`
|https://github.com/hazelcast/hazelcast/pull/15088[#15088]

|Member and membership classes (`Cluster`, `Member`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.cluster`
.2+^.^|https://github.com/hazelcast/hazelcast/pull/15046[#15046]

|Client classes (`Client`, `ClientService`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.client.api`

|Partition classes
|`com.hazelcast.core`
|`com.hazelcast.partition`
|https://github.com/hazelcast/hazelcast/pull/15039[#15039]

|===

[[fixes-40]]
=== Fixes

[[fixes-40beta2]]
==== 4.0-Beta-2

* Fixed possible statistics miscalculations by checking an
entry's expiration in a Near Cache only if its state is
`READ_PERMITTED`
https://github.com/hazelcast/hazelcast/pull/16067[#16067]
* Fixed an issue where `TestHazelcastInstanceFactory.registry()`
was throwing `NullPointerException` when it is null (being null could happen
when using in production networks).
https://github.com/hazelcast/hazelcast/pull/16033[#16033]
* Fixed an issue where some functions may not be working when
a client provides a new client type: removed `ClientType` and
`ConnectionType` enums and introduced free strings for them
instead.
https://github.com/hazelcast/hazelcast/pull/16030[#16030]
* Fixed an issue where an enabled `redoOperation()` was not
throwing an exception when an empty list is tried to be retrieved
on the client.
https://github.com/hazelcast/hazelcast/pull/16015[#16015]
* Aligned the exception mechanism of `CacheManager.createCache()`
with the `getCache()` and `getCacheManager().getCache()` methods of the
same class.
https://github.com/hazelcast/hazelcast/pull/16007[#16007]
* Fixed an issue where a Raft node may leak and stay in the ACTIVE
state after a CP member terminates, because of a race between
the Hazelcast member shutdown and Raft node termination logic.
https://github.com/hazelcast/hazelcast/pull/16022[#16022]
* Fixed an issue where gathering MultiMap statistics was breaking
the split-brain healing with `LatestAccessMergePolicy`.
https://github.com/hazelcast/hazelcast/issues/16001[#16001]
* Fixed an issue where enabling REST API configuration
(`getRestApiConfig().setEnabled(true)`) was throwing
`NullPointerException` since its default value was null.
https://github.com/hazelcast/hazelcast/pull/15981[#15981] 
* Fixed an issue where the configuration validator was not checking
if the maximum size policy is appropriate for the selected in-memory
format.
https://github.com/hazelcast/hazelcast/pull/15964[#15964]
* Fixed an issue where `ManagementCenterService` was shutting down
itself when it encounters an exception during the creation of `TimedMemberState`.
This was causing the cluster to disappear from Management Center.
https://github.com/hazelcast/hazelcast/issues/15946[#15946]
* Fixed an issue in the query operation for offloaded cases.
https://github.com/hazelcast/hazelcast/pull/15944[#15944]
* Fixed the cache statistics handling: Previously used
`Config.findCacheConfig()` could only lookup
cache configurations added statically or dynamically
via `Config.addCacheConfig()`, but was missing configurations
of dynamically created caches via `CacheManager.createCache()`.
Now, `CacheService.getCacheConfigs()` is used to fix this.
https://github.com/hazelcast/hazelcast/pull/15937[#15937]
* Fixed an issue where an exception thrown from a dynamic
metric provider was stopping the dynamic metric collector task.
https://github.com/hazelcast/hazelcast/issues/15932[#15932]
* Fixed the extensive `Overwriting existing probe` logs when
starting a Hazelcast member.
https://github.com/hazelcast/hazelcast/pull/15910[#15910]
* Fixed the `InvocationTargetException` thrown by the metrics
service on JDK 11.
https://github.com/hazelcast/hazelcast/issues/15884[#15884]
* Fixed an issue where `tcp.connection.clientCount` was
collected and published twice.
https://github.com/hazelcast/hazelcast/issues/15883[#15883]
* Fixed an issue where the client connection count
was retrieved using an incorrect method.
https://github.com/hazelcast/hazelcast/pull/15861[#15861]
* Fixed an issue where calling the `IMap.removeAll()` method
without index was updating the last access and expiry time
for all records.
https://github.com/hazelcast/hazelcast/pull/15850[#15850]
* Fixed the consistency issue between the configuration replacers
and XML configuration imports.
https://github.com/hazelcast/hazelcast/pull/15810[#15810]
* Fixed a configuration failure with YAML for composite
key indexes.
https://github.com/hazelcast/hazelcast/issues/15806[#15806]
* Fixed an issue where the gauges could not be created from the
dynamic metrics.
https://github.com/hazelcast/hazelcast/issues/15718[#15718]
* Fixed an issue where the client's Near Cache was not being
invalidated after the `IMap.executeOnKeys()` method is called.
https://github.com/hazelcast/hazelcast/issues/15468[#15468]
* Fixed the inconsistent behavior for sending a null message
via `Topic.publish()` on the members and clients. Now, the client
side also is not allowed to send it.
https://github.com/hazelcast/hazelcast/issues/15338[#15338]
* Made the public `createCachingProvider()` method private
since its class, `HazelcastServerCachingProvider`, is a private one.
https://github.com/hazelcast/hazelcast/issues/15144[#15144]
* Fixed an issue where the `client.getDistributedObjects()` method
may cause recreation of the destroyed objects.
https://github.com/hazelcast/hazelcast/issues/14571[#14571]
* Fixed an issue where the query cache was missing key and value
information for entries.
https://github.com/hazelcast/hazelcast/issues/13423[#13423]

[[fixes-40beta1]]
==== 4.0-Beta-1

* Fixed an issue where a new CP member could create the Raft nodes before its
local CP member field is not initialized yet, when it is being promoted.
This could create non-determinism issues for CP groups relying on the
local CP member information.
https://github.com/hazelcast/hazelcast/pull/15803[#15803]
* Fixed an issue where the `CompletableFuture#defaultExecutor()` method
caused compilation failure on JDK 9 due to the "protected" access.
https://github.com/hazelcast/hazelcast/pull/15702[#15702]
* Fixed a race issue by initializing the local CP members before
initializing the metadata group.
https://github.com/hazelcast/hazelcast/pull/15684[#15684]
* Fixed an issue where the `node.isMaster()` method could cause
inconsistent behaviors when it is executed during a partition service lock.
https://github.com/hazelcast/hazelcast/pull/15617[#15617]
* Fixed an issue where the CP subsystems' restart operations were
not being canceled and waiting the running/scheduled discovery tasks.
https://github.com/hazelcast/hazelcast/pull/15567[#15567]
* Fixed an issue where the executor service message task
was blocking the partition thread.
https://github.com/hazelcast/hazelcast/pull/15522[#15522]
* Fixed an issue where the used memory in metrics was becoming
a negative value.
https://github.com/hazelcast/hazelcast/issues/15485[#15485]
* Fixed an issue where `ClientMessageWriter` was throwing an
exception while writing to buffer.
https://github.com/hazelcast/hazelcast/issues/15471[#15471]
* Moved the `checkWanReplicationQueues` operation from the caller side
to the callee. https://github.com/hazelcast/hazelcast/pull/15412[#15412]
* Fixed an issue where `WanConsistencyCheckIgnoredEvent`, when it is
sent to Management Center, was throwing a `NullPointerException`.
https://github.com/hazelcast/hazelcast/pull/15400[#15400]
* Fixed an issue where the map configuration options `readBackupData`
and `statisticsEnabled` were not being respected when a new
`MapConfig` is dynamically added from a client to a running Hazelcast cluster.
https://github.com/hazelcast/hazelcast/issues/15382[#15382]
* Fixed an issue where the comparators were not able to act on
both keys and values. A custom paging predicate comparator may act on
keys and values at the same time even if only the keys are requested, e.g., using
the `IMap.keySet()` method. Before this fix only the keys were fetched for
this method, making comparators unable to act on values.
https://github.com/hazelcast/hazelcast/pull/15380[#15380]
* Optimized the shutdown for on-heap indexes: These indexes are cleaned on shutdown and
the index entries are removed one by one. For large indexes, e.g.,
for array/collection attribute indexes, this was taking a considerable amount of time.
https://github.com/hazelcast/hazelcast/issues/15340[#15340]
* Fixed the deserialization filtering for Externalizables and Deadlock in the
map index. The deserialization filter was not properly protecting against the
vulnerable Externalizable classes. The filtering has been extended.
https://github.com/hazelcast/hazelcast/pull/15358[#15358]
* Fixed an issue where the named scheduled tasks was not respecting
the `HazelcastInstanceAware` marker.
https://github.com/hazelcast/hazelcast/pull/15352[#15352]
* Fixed a possible `NullPointerException` for the `remove-if-same` map
operation.
https://github.com/hazelcast/hazelcast/pull/15344[#15344]
* Fixed an issue where storing `MapStore` instances in `MapStoreConfig`
could cause member failures when the configuration is added
dynamically.
https://github.com/hazelcast/hazelcast/pull/15224[#15224]
* Fixed a `NullPointerException` in the query caches by setting
the `publisher-listener-id` if a query cache has already one.
https://github.com/hazelcast/hazelcast/pull/15215[#15215]
* Fixed an issue where `SimpleTokenCredentials` could not be
deserialized due to the missing handling in `SpiPortableHook`.
https://github.com/hazelcast/hazelcast/issues/15196[#15196]
* Fixed an issue where the commit phase of transactional maps
was not checking the member-wide upper limit for the entries in
write behind queues.
https://github.com/hazelcast/hazelcast/pull/15186[#15186]
* Fixed an issue where the queries like `labels[any] = 0` and `labels[any] = 1`
were optimized only to `false` since `labels[any]` was interpreted as a
regular attribute name having a single value.
https://github.com/hazelcast/hazelcast/pull/15163[#15163]
* For on-heap indexes, fixed an issue where a record's `lastAccessTime`
was not updated when it is being accessed through an index. 
Now, this way, the expiration `maxIdle` mechanism takes this into account.
https://github.com/hazelcast/hazelcast/pull/15136[#15136]
* Fixed an issue where `ExecutorServiceProxy` was unnecessarily
serializing the same task multiple times before submitting it
to multiple members.
https://github.com/hazelcast/hazelcast/pull/15069[#15069]
* Added the missing user code deployment section to the configuration
which is sent to Management Center.
https://github.com/hazelcast/hazelcast/pull/15044[#15044]
* Fixed an issue where two client listeners are not registered since
they listen on a single connection (not cluster wide listeners) by
adding cleanups for them.
https://github.com/hazelcast/hazelcast/pull/15041[#15041]
* Fixed the authentication mechanism between the clients and members
by adding a check to prevent re-verification while the client is changing
its owner member.
https://github.com/hazelcast/hazelcast/pull/15030[#15030]
* Added support for the missing aliased discovery strategies,
e.g., `gcp` and `kubernetes`, to `ClientConfigXmlGenerator`.
https://github.com/hazelcast/hazelcast/issues/15010[#15010]
* Fixed an issue where the client user code deployment was
becoming non-operational when assertions are enabled.
https://github.com/hazelcast/hazelcast/pull/15006[#15006]
* Some operations such as heartbeat checks and partition
migrations share common threads with the client login module.
In case of the long running client login module implementations,
some symptoms such as split brain syndrome can be seen. This has
been fixed by introducing a blocking executor which is used only
for the client authentications.
https://github.com/hazelcast/hazelcast/pull/14956[#14956]
* Fixed an issue where the `IMap.removeInterceptor()` method
was returning `void`.
https://github.com/hazelcast/hazelcast/pull/14955[#14955]
* Removed the `entryEvicted` event from the event firing mechanism
in the case of eviction. Before, both `entryEvicted` and `entryExpired`
events were being fired.
https://github.com/hazelcast/hazelcast/pull/14954[#14954]
* Fixed an issue where the Hazelcast IMDG configuration files, that
have an extension other than `.xml`, `.yaml` or `.yml` or do not have
an extension, were ignored silently. This was happening
when the configuration file is set by using the `hazelcast.config`
system property.
https://github.com/hazelcast/hazelcast/pull/14953[#14953]
* Fixed an issue where the client was not considering the new
address of a restarted member, which has the same UUID but could
have a different IP address after it is restarted.
https://github.com/hazelcast/hazelcast/pull/14842[#14842]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/14832[#14832]
* Fixed an issue where the outbound pipeline was not waking up
properly after various optimizations for write-through
persistence is made.
https://github.com/hazelcast/hazelcast/pull/14831[#14831]
* Fixed an issue caused by the cache being not ready to be used
immediately after the cache proxy was created.
https://github.com/hazelcast/hazelcast/pull/14821[#14821]
* Fixed an issue where the performance of `IMap.values()` was low when
using `PartitionPredicate`. Also, `PartitionPredicate` was not
respecting indexes. So, now global indexes are used for partition
queries.
https://github.com/hazelcast/hazelcast/pull/14814[#14814]
* Fixed a performance issue where there were unneeded iterations and
object creations while converting the client messages to user objects.
https://github.com/hazelcast/hazelcast/pull/13784[#13784]
* Fixed an issue where the locked entries with a time-to-live were not evicted.
With this fix, the lock operation checks if an entry has already expired.
https://github.com/hazelcast/hazelcast/issues/13272[#13272]
* Fixed an issue where there were excessive amount of logs on the target cluster
when `cache` config is missing for the WAN replication.
https://github.com/hazelcast/hazelcast/issues/12826[#12826]
* Fixed an issue where there was an inconsistent `removeIf` behavior among the
collection views of IMap.
https://github.com/hazelcast/hazelcast/issues/12198[#12198]
* Fixed a leak in the query cache due to `ListenerRegistrationHelper`, which
has been removed with this fix.
https://github.com/hazelcast/hazelcast/pull/11914[#11914]
* Fixed an issue where the `IMap.replace()` method was not loading entries
from the MapLoader when the keys could not be found in the memory.
https://github.com/hazelcast/hazelcast/issues/11300[#11300]

[[removed-40]]
=== Removed Features

[[removed-40beta2]]
==== 4.0-Beta-2

* Removed the deprecated `SimpleEntryView.evictionCriteriaNumber()`
method.
https://github.com/hazelcast/hazelcast/pull/15846[#15846]
* Removed the deprecated IMap methods accepting `EntryListener`.
This has been replaced with `MapListener`.
https://github.com/hazelcast/hazelcast/pull/15781[#15781]

[[removed-40beta1]]
==== 4.0-Beta-1

* Removed the User Defined Services (Hazelcast's SPI) feature.
https://github.com/hazelcast/hazelcast/pull/15403[#15403], 
https://github.com/hazelcast/hazelcast/pull/15401[#15401]
* Removed the `setLicenseKey()` method of `ClientConfig`.
* Removed the methods in the `Member` and `AddressPicker` classes.
* Removed the deprecated diagnostics property names.
* Removed the deprecated `EvictionPolicyType` class. Instead, use the
enhanced `EvictionPolicy` class.
* Removed the legacy `IdGenerator` interface. Instead, `FlakeIdGenerator` has been used.
* Removed the deprecated `AsyncAtomicLong` and `AsyncAtomicReference` classes.
* Removed the deprecated cache eviction configurations.
* Removed the MapReduce feature.
* Removed the deprecated `LOCAL` transaction type (`TransactionType.LOCAL`)
* Removed the deprecated `optimizeQueries` map configuration parameter.
* Removed the following deprecated system properties:
** `hazelcast.version.check.enabled`
** `hazelcast.icmp.enabled`
** `hazelcast.icmp.parallel.mode`
** `hazelcast.icmp.echo.fail.fast.on.startup`
** `hazelcast.icmp.timeout`
** `hazelcast.icmp.interval`
** `hazelcast.icmp.max.attempts`
** `hazelcast.icmp.ttl`
** `hazelcast.mc.url.change.enabled`
** `hazelcast.slow.invocation.detector.threshold.millis`
