

== 4.0

[[nf-40]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].
* **X.509 Certificate Authentication:** Added support for credential retrieval by the members
from the X.509 certificates configured on the clients.
See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

*_Hazelcast IMDG Open Source New Features:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].

[[enh-40]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].
* **Improvements in the JAAS Authentication Mechanism:**
** Added support for the standard JAAS callbacks, i.e., `NameCallback` and `PasswordCallback`
** Secrets, if not necessary, are not stored now
** Cleaned up the `Credentials` object.


*_Hazelcast IMDG Open Source Enhancements:_*

* Enabled the REST endpoints for the `cluster.sh` and
`healthcheck.sh` scripts to use HTTPS. Before, they were
using HTTP. See the
link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#using-the-script-cluster-sh[cluster.sh^] and link:https://docs.hazelcast.org/docs/3.12.2/manual/html-single/#health-check-script[healtcheck.sh^] sections.
* **???:** ???. See the https://docs.hazelcast.org/docs/4.0/manual/html-single/index.html#???[??? section].
* Updated Hazelcast JCache implementation to support JCache 1.1.1.
This version of JCache does not introduce new functionalities;
it resolves the errata and issues in JCache 1.1.0.
See the https://docs.hazelcast.org/docs/4.0/manual/html-single/#jcache-111[Upgrading to JCache 1.1.1 section].

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Added transaction specific backup operations: `TxnSetBackupOperation`
and `TxnDeleteBackupOperation`.
https://github.com/hazelcast/hazelcast/pull/15236[#15236]
* Added `Nullable` and `Nonnull` annotations to IQueue.
https://github.com/hazelcast/hazelcast/pull/15156[#15156]
* Added support for null keys for the client side implementations of
`IMap.addEntryListener()`.
https://github.com/hazelcast/hazelcast/issues/15155[#15155]
* Improved the Raft snapshotting so that the old log entries are not
kept when there is no follower with an unknown match index.
https://github.com/hazelcast/hazelcast/pull/15062[#15062]
* Added the full example configuration files (XML and YAML) for the
Hazelcast Java client.
https://github.com/hazelcast/hazelcast/pull/15056[#15056]
* Hazelcast IMDG now sends error messages and stack trace separately
(for WAN consistency check) to the Management Center.
https://github.com/hazelcast/hazelcast/pull/15052[#15052]
* Added support for `HazelcastJsonValue` over REST API: When a
`HazelcastJsonValue` is requested, now a UTF8 encoded JSON value is returned. The
response  has the JSON string in the payload and "Content-Type"
header is set to `application/json`.
https://github.com/hazelcast/hazelcast/pull/15017[#15017]
* Enhanced the queries (read-only operations) in the CP Subsystem so that
they are executed with linearizability but they are not appended to the Raft log.
By this way, the grow of Raft logs and snapshots of read-only operations are
prevented, leading to throughput improvement
https://github.com/hazelcast/hazelcast/pull/14986[#14986]
* Improved the WAN feature so that now lazy deserialization is used
when merging entries received via WAN. Otherwise, the unconditional
deserialization was causing overhead.
https://github.com/hazelcast/hazelcast/pull/14982[#14982]
* Added the support for Java 8 `Optionals` in the queries.
https://github.com/hazelcast/hazelcast/pull/14827[#14827]
* Fixed the Javadoc markup issues.
https://github.com/hazelcast/hazelcast/pull/14971[#14971]
* Introduced `PartitionIdSet`. This is a mutable set of partition IDs
which can be efficiently represented by a fixed size leading to a
better performance.
https://github.com/hazelcast/hazelcast/pull/14925[#14925]
* Made `AssertTask` an interface to enable lambdas to be used in
assert-eventually methods.
https://github.com/hazelcast/hazelcast/pull/14923[#14923]
* Updated the Hazelcast Kubernetes dependency to version 1.5.
https://github.com/hazelcast/hazelcast/pull/14898[#14898]
* Updated the map package so that it uses the Java 8 features.
https://github.com/hazelcast/hazelcast/pull/14891[#14891]
* Cleaned up the Maven repositories in Hazelcast's `pom.xml`
to simplify the usage of Maven proxies.
https://github.com/hazelcast/hazelcast/pull/14850[#14850]
* Eliminated the excessive logging when NIO networking is shutdown by
deregistering the IO threads.
https://github.com/hazelcast/hazelcast/pull/14823[#14823]
* Updated the web session manager dependency to its latest
version.
https://github.com/hazelcast/hazelcast/pull/14822[#14822]
* Separated the statistics for `IMap.set()` and `IMap.put()` methods.
https://github.com/hazelcast/hazelcast/pull/14811[#14811]
* Introduced a warning log for illegal reflective access operation when
using Java 9 and higher, and OpenJ 9.
https://github.com/hazelcast/hazelcast/pull/14798[#14798]
* Separated the statistic gathering for `IMap.set(K, V)` and
`IMap.put(K, V) operations`.
https://github.com/hazelcast/hazelcast/issues/14663[#14663]
* Improved the fluent interface of configuration classes by adding
the `return this` statements to the setter methods.
https://github.com/hazelcast/hazelcast/pull/11107[#11107]

[[bc-40]]
=== Breaking Changes

* Made `Projection` a functional interface so that it has becomes
lambda friendly.
https://github.com/hazelcast/hazelcast/pull/15204[#15204]
* Removed the usage of `com.hazelcast.core.IBifunction`, replaced
it with `java.util.function.Bifunction`.
https://github.com/hazelcast/hazelcast/pull/15201[#15201]
* Separated WAN private and public classes into different packages.
https://github.com/hazelcast/hazelcast/pull/15195[#15195]
* Moved the Event Journal configuration inside the map or
cache configuration. Before, it was configured as a parent-level
element.
https://github.com/hazelcast/hazelcast/pull/15185[#15185]
* Moved the Merkle tree configuration under map configuration.
https://github.com/hazelcast/hazelcast/pull/15180[#15180] 
* Removed the XSDs for Hazelcast IMDG 3.x versions.
https://github.com/hazelcast/hazelcast/pull/15177[#15177]
* Moved various classes (`Node`, `NodeContext`, etc.)
from the `com.hazelcast.instance` package to
the newly introduced `com.hazelcast.instance.impl`.
https://github.com/hazelcast/hazelcast/pull/15151[#15151]
* Renamed the `getId` method of `IdentifiedDataSerializable`
to `getClassId`.
https://github.com/hazelcast/hazelcast/pull/15127[#15127]
* Refactored and cleaned up the internal partition/migration listeners:
** Renamed `PartitionListener` to `PartitionReplicaInterceptor` and
removed registering child listeners, which is not used.
** Renamed `InternalMigrationListener` to `MigrationInterceptor` and
converted to interface with default methods.
+
https://github.com/hazelcast/hazelcast/pull/15051[#15051]
+
* Made the collection clones of IMap immutable so that
`UnsupportedOperationException` is thrown consistently
upon the attempts to update a collection returned by the `keySet`,
`entrySet`, `localKeySet`, `values` and `getAll` methods.
https://github.com/hazelcast/hazelcast/pull/15013[#15013]
* Removed deprecated client configuration methods such as
`isInsideAws()` and `newAliasedDiscoveryConfig()`.
https://github.com/hazelcast/hazelcast/pull/15012[#15012]
* Added `Nullable` and `Nonnull` annotations to IMap.
https://github.com/hazelcast/hazelcast/pull/15003[#15003]
* Removed the `hazelcast.executionservice.taskscheduler.remove.oncancel`
system property and related methods.
https://github.com/hazelcast/hazelcast/pull/14998[#14998]
* Made the `EntryProcessor` interface lambda friendly.
https://github.com/hazelcast/hazelcast/pull/14995[#14995]
* Removed the `LegacyAsyncMap` interface.
https://github.com/hazelcast/hazelcast/pull/14994[#14994]
* Removed the support for primitives for `setAttribute` and
`getAttribute` operations.
All member attributes support only string attributes now.
https://github.com/hazelcast/hazelcast/pull/14974[#14974]
* Changed the `application/javascript` "Content-Type" header used
by REST API to respond to the JSON documents. Now, it uses
`application/json`.
https://github.com/hazelcast/hazelcast/pull/14972[#14972]
* Removed the backward compatible `ADDED` event from the
`loadAll` method.
https://github.com/hazelcast/hazelcast/pull/14964[#14964]
* Added `EntryExpiredListener` to the `EntryListener` interface.
https://github.com/hazelcast/hazelcast/pull/14959[#14959]
* Changed the `non-space-string` XSD type to collapse all
whitespaces, so they are handled correctly in the declarative
Hazelcast IMDG configuration files.
https://github.com/hazelcast/hazelcast/issues/14919[#14919]
* Removed the `java.util.function` back ports.
https://github.com/hazelcast/hazelcast/pull/14912[#14912]
* The packages of the following classes have been changed:
+
[cols="3a,2,3,1a"]
|===

|Classes|Package Before IMDG 4.0|Package After IMDG 4.0|Details

|`ClassNameFilter`, `SerializationClassNameFilter` 
|`com.hazelcast.nio`
|`com.hazelcast.nio.serialization`
|https://github.com/hazelcast/hazelcast/pull/15171[#15171]

| All IMap classes
| `com.hazelcast.core`
| `com.hazelcast.map`
| https://github.com/hazelcast/hazelcast/pull/15149[#15149]

|`ReplicatedMap`
|`com.hazelcast.core`
|`com.hazelcast.replicatedmap`
|https://github.com/hazelcast/hazelcast/pull/15146[#15146]

|`IAtomicLong`, `IAtomicReference`, `ILock`, `ICondition`, `ISemaphore`, `ICountDownLatch`
|`com.hazelcast.core`
|`com.hazelcast.cp`
|https://github.com/hazelcast/hazelcast/pull/15143[#15143]

|`IndexAwarePredicate`, `VisitablePredicate`
|`com.hazelcast.query`
|`com.hazelcast.query.impl.predicates`
|https://github.com/hazelcast/hazelcast/pull/15142[#15142]

|Transaction collection classes (`TransactionalMap`, `TransactionalList`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.transaction`
|https://github.com/hazelcast/hazelcast/pull/15129[#15129]

|`IQueue`, `QueueStore`, `IList`, `ISet`, `ItemEvent`, `ItemListener`
|`com.hazelcast.core`
|`com.hazelcast.collection`
|https://github.com/hazelcast/hazelcast/pull/15127[#15127]

|`MultiMap`
|`com.hazelcast.core`
|`com.hazelcast.multimap`
|https://github.com/hazelcast/hazelcast/pull/15123[#15123]

|`ITopic`, `Message`, `MessageListener`
|`com.hazelcast.core`
|`com.hazelcast.topic`
|https://github.com/hazelcast/hazelcast/pull/15122[#15122]

|`RingbufferStoreFactory`, `RingbufferStore`
|`com.hazelcast.core`
|`com.hazelcast.ringbuffer`
|https://github.com/hazelcast/hazelcast/pull/15121[#15121]

|Operation classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.impl.operationservice`
|https://github.com/hazelcast/hazelcast/pull/15115[#15115]

|Partition SPI classes
|`com.hazelcast.spi`
|`com.hazelcast.spi.partition`
|https://github.com/hazelcast/hazelcast/pull/15088[#15088]

|Member and membership classes (`Cluster`, `Member`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.cluster`
.2+^.^|https://github.com/hazelcast/hazelcast/pull/15046[#15046]

|Client classes (`Client`, `ClientService`, etc.)
|`com.hazelcast.core`
|`com.hazelcast.client.api`

|Partition classes
|`com.hazelcast.core`
|`com.hazelcast.partition`
|https://github.com/hazelcast/hazelcast/pull/15039[#15039]

|===



[[fixes-40]]
=== Fixes

* Fixed an issue where storing `MapStore` instances in `MapStoreConfig`
could cause member failures when the configuration is added
dynamically.
https://github.com/hazelcast/hazelcast/pull/15224[#15224]
* Fixed a `NullPointerException` in the query caches by setting
the `publisher-listener-id` if a query cache has already one.
https://github.com/hazelcast/hazelcast/pull/15215[#15215]
* Fixed an issue where `SimpleTokenCredentials` could not be
deserialized due to the missing handling in `SpiPortableHook`.
https://github.com/hazelcast/hazelcast/issues/15196[#15196]
* Fixed an issue where the queries like `labels[any] = 0` and `labels[any] = 1`
were optimized only to `false` since `labels[any]` was interpreted as a
regular attribute name having a single value.
https://github.com/hazelcast/hazelcast/pull/15163[#15163]
* For on-heap indexes, fixed an issue where a record's `lastAccessTime`
was not updated when it is being accessed through an index. 
Now, this way, the expiration `maxIdle` mechanism takes this into account.
https://github.com/hazelcast/hazelcast/pull/15136[#15136]
* Fixed an issue where `ExecutorServiceProxy` was unnecessarily
serializing the same task multiple times before submitting it
to multiple members.
https://github.com/hazelcast/hazelcast/pull/15069[#15069]
* Added the missing user code deployment section to the configuration
which is sent to Management Center.
https://github.com/hazelcast/hazelcast/pull/15044[#15044]
* Fixed an issue where two client listeners are not registered since
they listen on a single connection (not cluster wide listeners) by
adding cleanups for them.
https://github.com/hazelcast/hazelcast/pull/15041[#15041]
* Fixed the authentication mechanism between the clients and members
by adding a check to prevent re-verification while the client is changing
its owner member.
https://github.com/hazelcast/hazelcast/pull/15030[#15030]
* Added support for the missing aliased discovery strategies,
e.g., `gcp` and `kubernetes`, to `ClientConfigXmlGenerator`.
https://github.com/hazelcast/hazelcast/issues/15010[#15010]
* Fixed an issue where the client user code deployment was
becoming non-operational when assertions are enabled.
https://github.com/hazelcast/hazelcast/pull/15006[#15006]
* Some operations such as heartbeat checks and partition
migrations share common threads with the client login module.
In case of the long running client login module implementations,
some symptoms such as split brain syndrome can be seen. This has
been fixed by introducing a blocking executor which is used only
for the client authentications.
https://github.com/hazelcast/hazelcast/pull/14956[#14956]
* Fixed an issue where the `IMap.removeInterceptor()` method
was returning `void`.
https://github.com/hazelcast/hazelcast/pull/14955[#14955]
* Removed the `entryEvicted` event from the event firing mechanism
in the case of eviction. Before, both `entryEvicted` and `entryExpired`
events were being fired.
https://github.com/hazelcast/hazelcast/pull/14954[#14954]
* Fixed an issue where the Hazelcast IMDG configuration files, that
have an extension other than `.xml`, `.yaml` or `.yml` or do not have
an extension, were ignored silently. This was happening
when the configuration file is set by using the `hazelcast.config`
system property.
https://github.com/hazelcast/hazelcast/pull/14953[#14953]
* Fixed an issue where the client was not considering the new
address of a restarted member, which has the same UUID but could
have a different IP address after it is restarted.
https://github.com/hazelcast/hazelcast/pull/14842[#14842]
* Fixed an issue where the migration operations were running
before the previous finalization is completed.
https://github.com/hazelcast/hazelcast/pull/14832[#14832]
* Fixed an issue where the outbound pipeline was not waking up
properly after various optimizations for write-through
persistence is made.
https://github.com/hazelcast/hazelcast/pull/14831[#14831]
* Fixed an issue caused by the cache being not ready to be used
immediately after the cache proxy was created.
https://github.com/hazelcast/hazelcast/pull/14821[#14821]
* Fixed a performance issue where there were unneeded iterations and
object creations while converting the client messages to user objects.
https://github.com/hazelcast/hazelcast/pull/13784[#13784]
* Fixed an issue where the locked entries with a time-to-live were not evicted.
With this fix, the lock operation checks if an entry has already expired.
https://github.com/hazelcast/hazelcast/issues/13272[#13272]
* Fixed an issue where there was an inconsistent `removeIf` behavior among the
collection views of IMap.
https://github.com/hazelcast/hazelcast/issues/12198[#12198]
* Fixed a leak in the query cache due to `ListenerRegistrationHelper`, which
has been removed with this fix.
https://github.com/hazelcast/hazelcast/pull/11914[#11914]
* Fixed an issue where the `IMap.replace()` method was not loading entries
from the MapLoader when the keys could not be found in the memory.
https://github.com/hazelcast/hazelcast/issues/11300[#11300]

[[deprecated-40]]
=== Deprecated Features

* ???.
* The following system properties are deprecated:
** `???`
* The following Hazelcast IMDG interfaces/classes are deprecated and replaced
with the ones provided by the Hazelcast IMDG CP Subsystem:
** `???`
* The following classes are deprecated:

[[removed-40]]
=== Removed Features

* Removed the methods in the `Member` and `AddressPicker` classes.
* Removed the deprecated diagnostics property names.
* Removed the `ILock` interface. The `ILock implementation is still being kept
as the development/unsafe mode of CP Subsystem's `FencedLock`.
* Removed the deprecated `AsyncAtomicLong` and `AsyncAtomicReference` classes.
* Removed the deprecated cache eviction configurations.
* Removed the MapReduce feature.
* Removed the deprecated `LOCAL` transaction type (`TransactionType.LOCAL`)



