== 4.1

NOTE: See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#upgrading-to-hazelcast-imdg-4-1[Hazelcast IMDG 4.1 Migration Guide^]
for the detailed guidelines to be followed when upgrading Hazelcast IMDG to 4.1.

[[nf-41]]
=== New Features

*_Hazelcast IMDG Enterprise New Features:_*

* **???:** ???.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#???[??? section^].

*_Hazelcast IMDG Open Source New Features:_*

* **SQL Implementation:** Implemented the SQL engine that
supports map scans, index scans, projections and filters.
It also introduces the `hazelcast-sql` module to handle the
SQL engine's dependencies on Apache Calcite.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#???[??? section^].

[[enh-41]]
=== Enhancements

*_Hazelcast IMDG Enterprise Enhancements:_*

* **???:** ???.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#???[??? section^].

*_Hazelcast IMDG Open Source Enhancements:_*

* **Improvements in Partial Network Disconnections:** Introduced properties
to be configured to detect and resolve the partial network issues among the
Hazelcast IMDG members.
See link:https://github.com/hazelcast/hazelcast/pull/16680[#16680^] and the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/index.html#???[??? section^].
* **Trusted Interfaces:** It is now possible to restrict the source IP addresses
from which the Management Center operations are allowed.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#limiting-source-addresses[Limiting Source Addresses section^].
* **Out-of-the-Box Kerberos Support:** Introduced support for Kerberos
authentication protocol which is one of the standard
solutions for single-sign-on. It also adds the GSSAPI authentication support in
LDAP configuration.
See the link:https://docs.hazelcast.org/docs/4.1/manual/html-single/#kerberos-authentication-type[Kerberos Authentication Type section^].

The following are the other improvements performed to solve the enhancement
issues opened by the Hazelcast customers/team.

* Improved the mechanism of partition table updates to
eliminate the latencies when these updates are sent to the clients by a member.
https://github.com/hazelcast/hazelcast/pull/16939[#16939]
* Improved the client configuration such that when the client
failover configuration is provided, the reconnect mode cannot
be set as `off`; it now fails fast in this case.
https://github.com/hazelcast/hazelcast/pull/16886[#16886]
* Introduced the `forEach()` loop support for IMap.
https://github.com/hazelcast/hazelcast/pull/16877[#16877]
* Added the `load()` method to `Config`, `ClientConfig` and
`ClientFailoverConfig` classes. This method loads the configuration
with the known locations. If not found, the default configuration is returned.
https://github.com/hazelcast/hazelcast/pull/16864[#16864]
* Improved the `deleteAll()` (MapStore) and ITopic Javadocs.
https://github.com/hazelcast/hazelcast/pull/16862[#16862],
https://github.com/hazelcast/hazelcast/pull/16861[#16861],
* Introduced the `ServerConnection` and `ClientConnection` interfaces
that extend `Connection` for cleaning up purposes.
https://github.com/hazelcast/hazelcast/pull/16849[#16849]
* Implemented the `root` operator for the SQL engine
responsible for getting the final result stream.
https://github.com/hazelcast/hazelcast/issues/16829[#16829]
* Added support for `IMap.computeIfAbsent()`.
https://github.com/hazelcast/hazelcast/pull/16808[#16808]
* Introduced SQL thread pools for query processing.
https://github.com/hazelcast/hazelcast/issues/16805[#16805]
* Introduced the network protocol, base executor and row
interfaces for the SQL engine.
https://github.com/hazelcast/hazelcast/issues/16799[#16799],
https://github.com/hazelcast/hazelcast/issues/16762[#16762]
* Added the `setAll()` and `setAllAsync()` methods for IMap.
https://github.com/hazelcast/hazelcast/pull/16787[#16787]
* Added the `writeOrdered()` method to the `Connection` class
for the purpose of ordered delivery of messages.
https://github.com/hazelcast/hazelcast/issues/16776[#16776]
* Added the creation time metric for the executor service.
https://github.com/hazelcast/hazelcast/pull/16775[#16775]
* Improved an unclear exception message for credentials.
https://github.com/hazelcast/hazelcast/pull/16756[#16756]
* Updated the related aspects of Hazelcast IMDG after the
changes done on the client protocol side to add the ability
to add new parameters, methods, services, events and custom types
to codecs.
https://github.com/hazelcast/hazelcast/pull/16718[#16718]
* Added the `offset` parameter that can be used while creating
inputs in `BufferObjectDataInput`.
https://github.com/hazelcast/hazelcast/pull/16701[#16701]
* Introduced the `putAllAsync()` method for MultiMap.
https://github.com/hazelcast/hazelcast/pull/16698[#16698]
* Defined metrics for ISet and IList collections.
https://github.com/hazelcast/hazelcast/pull/16665[#16665]
* Upgraded log4j2 version to 2.13.0.
https://github.com/hazelcast/hazelcast/pull/16654[#16654]
* Renamed MultiMap proxy implementation to follow the established naming convention:
`ObjectMultiMapProxy` -> `MultiMapProxyImpl`.
https://github.com/hazelcast/hazelcast/pull/16637[#16637]
* Introduced the `hazelcast.logging.details.enabled` property
to make the logging of cluster version, name and IP optional to
decrease the noise in the logs when, for example, you have a single-member cluster.
https://github.com/hazelcast/hazelcast/pull/16622[#16622]
* Upgraded the Hazelcast Kubernetes plugin version to 2.0.1.
https://github.com/hazelcast/hazelcast/pull/16590[#16590]
* * Added the support for automatically detecting the classloader
of a type for the user code deployment feature.
https://github.com/hazelcast/hazelcast/pull/16585[#16585]
* Made `IMap.putAllAsync()` and `IMap.submitToKeys()` methods public API.
https://github.com/hazelcast/hazelcast/issues/16449[#16449]
* Implemented the base type system for SQL: the base SQL data types
have been defined and mapped to the corresponding Java types.
Type information is used by executor stages to use the right strategy
of expression evaluation.
https://github.com/hazelcast/hazelcast/issues/15241[#15241]
* Clarified the exception message when you connect to a cluster with an
invalid group name.
https://github.com/hazelcast/hazelcast/issues/15099[#15099]
* Added a test for the `ClientConsoleApp` class. 
https://github.com/hazelcast/hazelcast/issues/12298[#12298]
* Improved the behavior of `ConcurrentMap.computeIfPresent`:
combined single client-server round trips instead of two (for `get` and
`replace` methods).
https://github.com/hazelcast/hazelcast/issues/11958[#11958]

[[bc-41]]
=== Breaking Changes

* The `TcpIpConnection` class has been renamed as `ServerConnection`.
https://github.com/hazelcast/hazelcast/pull/16839[#16839]



[[fixes-41]]
=== Fixes

* Fixed an issue in the cache service where its pre-join
operation was considering `CacheConfig` as resolved: it
was assuming that key/value types, user customizations and
other cache configurations have been loaded. This was an issue
when the cache is not touched yet.
https://github.com/hazelcast/hazelcast/pull/16917[#16917]
* Fixed an issue where `ServiceLoader` was round-tripping between URL and URI,
and consequently loses the associated `URLStreamHandler` when trying to load
Hazelcast from a custom class loader.
https://github.com/hazelcast/hazelcast/issues/16846[#16846]
* Fixed an issue where the class definitions, that are registered explicitly in
the serialization configuration and have the same class ID in different factories,
were not handled properly.
https://github.com/hazelcast/hazelcast/pull/16831[#16831]
* Fixed the `NullPointerException` in `IndexCopyBehavior.NEVER` mode.
https://github.com/hazelcast/hazelcast/pull/16784[#16784]
* Fixed an issue where the client permissions for Reliable Topic and Ringbuffer
we're missing.
https://github.com/hazelcast/hazelcast/pull/16755[#16755]
* Fixed an issue where the type information was missing the Metrics MBeans.
https://github.com/hazelcast/hazelcast/pull/16747[#16747]
* Fixed an issue where the RESP API was always requiring the call URLs
to end with a slash character.
https://github.com/hazelcast/hazelcast/pull/16688[#16688]
* Fixed an issue where the service URL for Eureka could not be set
using the declarative configuration.
https://github.com/hazelcast/hazelcast/pull/16679[#16679]
* Fixed an issue where the wait key of a blocking call within
a Raft invocation was still being reported as a live operation,
when the key times out.
https://github.com/hazelcast/hazelcast/pull/16614[#16614]
* Fixed an issue where the upload of classes using the client
user code deployment were not successful when they are retrieved not
in their created order.
https://github.com/hazelcast/hazelcast/pull/16612[#16612]
* Fixed an issue where the size() method was returning a negative
value when map, cache and multimap contain more than Integer.MAX_VALUE entries.
https://github.com/hazelcast/hazelcast/pull/16594[#16594]
* Fixed an invalidation issue when using a transactional map
from a cache with a Near Cache: the cache invalidation event occurs
when the `transactionalMap.put` method is called. As a result,
the entry was getting invalidated before the change is committed to the map.
https://github.com/hazelcast/hazelcast/pull/16579[#16579]
* Fixed an issue where `InPredicate` was not invoking value comparison when the
read attribute is null.
https://github.com/hazelcast/hazelcast/issues/15100[#15100]
* Fixed an issue where Map, Cache, MultiMap data structures
were returning negative values (`size()`) when the size is more than
`Integer.MAX_VALUE`.
https://github.com/hazelcast/hazelcast/issues/14935[#14935]

[[removed-41]]
=== Removed Features


[[heroes-41]]
===  Hazelcast Heroes

We'd like to thank to the following contributors from our
open source community that appear in this release notes
document:

* https://github.com/inelpandzic[Inel Pandzic]
* https://github.com/omidp[Omid Pourhadi]
* https://github.com/ryanlindeborg[Ryan Lindeborg]
* https://github.com/santhoshkumarbs[Santhosh Kumar]
* https://github.com/KowalczykBartek[Bartek Kowalczyk]
* https://github.com/webashutosh[Ashutosh Agrawal]
* https://github.com/aberkecz[Ádám Berkecz]
* https://github.com/HugeOrangeDev[HugeOrangeDev]
* https://github.com/pertsodian[Harry Tran]
* https://github.com/StephenOTT[Stephen Russett]
* https://github.com/ulfjack[Ulf Adams]
* https://github.com/abdulazizali77[Abdul Aziz Ali]

Thank you for your valuable contributions!


